[MVC 구현하기 - 1단계] 커찬(이충안) 미션 제출합니다.
woowacourse/java-mvc pull request #647
Opened 2024-09-16 23:56 UTC by leegwichan

안녕하세요 리비! 커찬입니다.

학습 테스트 및 1단계 요구사항 리뷰 부탁드립니다.
저에게 용건이 있으시거나, 이해하시기 어려운 부분이 있다면 언제나 DM주세요!
(물론 추석 끝나고 제 자리에 와서 물어보셔도 됩니다 ^^)

2024-09-19 06:03 UTC, Libienz requested changes
안녕하세요 커(요미)찬 😆

코드리뷰 스터디 하던게 얼마 전 같은데 시간이 벌써 많이 지났네요 🥲
다시 리뷰어로 만나게 되어 반갑습니다 👍

첫번째 제출 고생하셨습니다!
학습테스트와 요구사항 맞춰주신 것 확인했습니다.

다만 ManualMapping정보와 다르게 프로덕션 서버가 동작하지 않아요~
이 부분 다음 제출 때까지 확인해주시길 바랍니다.

질문 위주로 코멘트 남겨보았는데 코멘트도 확인해주세요~ 커찬과 많은 이야기 나누고 싶습니다리
미션동안 잘 부탁드립니다 🙇🏻‍♂️

2024-09-20 04:51 UTC, leegwichan reviewed
안녕하세요 리비! 같은 강의실에 있는 커찬입니다.
리비가 준 코멘트에 답변 & 리뷰 반영해보았습니다.

리뷰 부탁드릴께요! (궁금한 점 있으시면 옆자리로 찾아와주세요!)

2024-09-20 04:51 UTC, leegwichan commented on study/src/test/java/reflection/Junit4TestRunner.java
> +                method.invoke(clazz.getDeclaredConstructor().newInstance());
- `getConstructor()`
  - public 생성자만 가져옵니다. 즉, 해당 클래스의 공개 생성자만 검색합니다.
  - 상위 클래스에서 상속된 public 생성자도 가져올 수 있습니다.
- `getDeclaredConstructor()`
  - 모든 접근 제어자 (public, protected, private, default)의 생성자를 가져올 수 있습니다. 즉, 모든 선언된 생성자를 검색합니다. (만약 private 생성자에 접근하려면, setAccessible(true)를 사용하여 접근 제어를 무시해야 합니다.)
  - 상속된 생성자는 포함되지 않고, 오직 해당 클래스에 선언된 생성자만 검색합니다.

2024-09-20 04:51 UTC, leegwichan commented on study/src/test/java/reflection/ReflectionTest.java
> +                () -> assertThat(clazz.getCanonicalName()).isEqualTo("reflection.Question"));
일단 SimpleName은 class 이름만을 반환하고, Name, CanonicalName은 패키지를 포함한 클래스 이름을 반환한다고 이해했습니다.

아래 내용은 추가 작성해 보았습니다~
- SimpleName
  - 클래스의 간단한 이름을 반환합니다.
  - 패키지 이름을 포함하지 않은 클래스 자체의 이름만 반환됩니다.
  - 내부 클래스의 경우, 내부 클래스의 이름만 반환합니다.
- Name
  - 패키지 이름을 포함한 클래스의 이름을 반환합니다.
  - 내부 클래스의 경우, $ 기호로 구분된 내부 클래스를 포함한 이름을 반환합니다.
- CanonicalName
  - getName()와 유사하지만, 내부 클래스의 경우 . (점)으로 구분하여 반환합니다.
  - 만약 클래스가 익명 클래스, 지역 클래스, 또는 배열 클래스인 경우, 이 메서드는 null을 반환할 수 있습니다.

2024-09-20 04:51 UTC, leegwichan commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java
>      }
> 현재 서버를 실행하면 manualMapping에 정의되어 있는 요청들이 동작하지 않아요~ 해당 부분이 문제로 보여지는데 어떤 부분이 문제인지 확인해주세요!

직접 만나서 정상작동 확인 했습니다!

2024-09-20 04:51 UTC, leegwichan commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java
>      }
> Redirect와 forwarding의 차이도 학습하고 저에게 설명해주세요!

Redirect는 클라이언트에게 302 Found 응답을 반환하고 응답의 Location 값을 이용해 재요청합니다.
forwarding은 서버에 있는 자원으로 다시 응답을 만들어서 반환합니다.

>  추가적으로 redirect하기전에 request.setAttribute를 하고 있네요.
redirect는 loacation을 담아 클라이언트에게 "응답"해버리기 때문에 request에 setAttribute를 해도 이것이 의미있게 사용되지는 않을 것 같아요.

오 그렇네요! request.setAttribute를 redirect 요청 처리 이후에 하도록 변경했습니다!

2024-09-21 18:07 UTC, Libienz approved these changes
안녕하세요 케이찬~ 
코멘트 답변해주신것과 리뷰 반영해주신 것 확인했어요 👊

간단한 질문 코멘트만 남겼습니다. 
반영 요청드릴 부분이 더 없어서 Approve드리지만 코멘트 확인은 한 번 부탁드려요 🙌

2024-09-21 18:07 UTC, Libienz commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>              return;
먼저 드린 코멘트와 유사한데요~ 요청의 위임이 DispatcherServlet의 핵심이라고 생각해요.

추가적으로 response는 뷰 그 자체라고 생각합니다. 
그렇기에 저는 response의 속성에 따라 분기하는 로직이 뷰로직이라고 생각해요.

DispatcherServlet은 위임에만 집중하고 별다른 로직은 관심사를 가진 쪽에서 처리하면 객체지향적인 설계가 될 수 있다고 생각해요

현재 개선한 버전이 책임을 적절하게 옮겨준 버전이라고 생각해요~

2024-09-21 18:07 UTC, Libienz commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java
>      }
머쓱타드.. 제가 꼼꼼히 확인하지 못하고 코멘트 드린 점 다시 사과드려요 ㅠㅠ

> Redirect는 클라이언트에게 302 Found 응답을 반환하고 응답의 Location 값을 이용해 재요청합니다.
> forwarding은 서버에 있는 자원으로 다시 응답을 만들어서 반환합니다.

차이점도 잘 정리해주셨네요~
서버 내부의 동작이냐 서버 외부, 클라이언트의 흐름이냐로 정리할 수 있겠습니다 👊

2024-09-21 18:08 UTC, merged

2024-09-22 05:13 UTC, leegwichan commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            throws ServletException {
> DispatcherServlet은 누구에게 요청을 위임할까요!?

`요청이 들어오면 알잘딱하게 response를 설정해주는 역할`을 위해 다른 객체들에게 책임을 위임한다고 볼 수 있겠네요.
지금의 DispatcherServlet은 Controller, View에게 책임을 위임한다고 볼 수 있네요.

> 서블릿과 컨트롤러, 핸들러는 각각 다른 개념일까요!?

다른 개념이겠죠? 직접 찾아볼 수도 있겠지만 지금의 제 생각으로 답변을 해볼께요.
서블릿은 Tomcat(WAS) 입장에서 바라보았을 때 요청 처리 단위라고 생각해요. 여러 서블릿을 쓸 수 있지만, 지금은 DispatcherServlet 하나로 사용하는 것이죠.
지금 구현된 컨트롤러는 Spring 입장에서 바라보았을 때 요청 처리 단위라고 생각해요. 핸들러는 컨트롤러 각각의 메서드라고 생각합니다.