[MVC 구현하기 - 1단계] 타칸(최원준) 미션 제출합니다.
woowacourse/java-mvc pull request #658
Opened 2024-09-18 06:51 UTC by jhon3242

안녕하세요 제제! 🍊
타칸입니다!😊
스터디 이후로 오랜만에 코드 리뷰를 받게 되었네요! ㅎㅎ
리플랙션은 처음이라 조금 어색한 부분이 있을 수 있는데 더 개선될 방향이 있으면 알려주시면 감사하겠습니다!
잘 부탁드려용

2024-09-19 07:30 UTC, JINU-CHANG requested changes
안녕하세요 타칸! 오랜만이에요 MVC 미션 리뷰어로 만나게 되어 반갑습니다 😃
MVC 미션 1단계 잘 구현해주셨네요!
학습 테스트와 관련한 부분 그리고 코드 읽으면서 궁금한 부분들 질문 남겨두었어요.
천천히 확인해주세요~

2024-09-19 07:30 UTC, JINU-CHANG commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
메서드가 너무 잘게 쪼개져있는 느낌이 들어 오히려 읽기 어려운 것 같아요,,
메서드명이 scanAndInitializeHandlers, registerControllerMethods, registerHandler로 계속 중복된 느낌이 듭니다!

2024-09-19 07:30 UTC, JINU-CHANG commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Constructor<?> secondConstructor = questionClass.getDeclaredConstructor(String.class, String.class, String.class);
두번째 생성자를 가져오는데 첫번째 생성자와 호출방식이 같네요 👀

2024-09-19 07:30 UTC, JINU-CHANG commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Field[] fields = questionClass.getDeclaredFields();
getFields()와 getDeclaredFields() 의 차이점은 무엇일까요?

2024-09-19 07:30 UTC, JINU-CHANG commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
각각의 예외는 언제 발생할 수 있는 예외인가요?

2024-09-19 07:30 UTC, JINU-CHANG commented on study/src/test/java/reflection/ReflectionTest.java
> +        assertThat(clazz.getCanonicalName()).isEqualTo("reflection.Question");
getName()과 getCanonicalName() 메서드의 차이점은 무엇일까요?

2024-09-19 07:30 UTC, JINU-CHANG commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            return controllerClass.getConstructor().newInstance();
지금 당장 사용하지 않는 인스턴스를 생성할 필요가 있을까요?

2024-09-19 11:00 UTC, jhon3242 commented on study/src/test/java/reflection/ReflectionTest.java
> +        assertThat(clazz.getCanonicalName()).isEqualTo("reflection.Question");
getName()의 경우 Class 객체에 의해 표현되는 이름을 반환하고, getCanonicalName()은 자바 언어 스펙에서 제공하는 이름을 반환합니다! 배열 객체의 경우 getName은 인코딩된 문자열을 반환하고 getCanonicalName은 이름 그대로 문자열을 반환한다고 하더라고요!😁

2024-09-19 11:01 UTC, jhon3242 commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Constructor<?> secondConstructor = questionClass.getDeclaredConstructor(String.class, String.class, String.class);
네 맞아요 굳이 두번째 생성자를 사용할 필요가 없다고 느껴졌어요. 첫번째 생성자를 사용해봤는데 문제없이 테스트에 통과했습니다. 저는 왜 굳이 secondConstructor를 정의해주었는지 의도 파악이 안되더라고요.. 이 부분에 대해서 제제의 생각이 궁금합니다!😂

2024-09-19 11:02 UTC, jhon3242 commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Field[] fields = questionClass.getDeclaredFields();
getFields 는 public 필드를 가져오고 getDeclaredFields 는 정의된 모든 필드를 가져옵니다!

2024-09-20 08:00 UTC, JINU-CHANG commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Field[] fields = questionClass.getDeclaredFields();
상위 클래스에 대한 내용이 차이점으로 언급되면 좋을 것 같아요!

getDeclaredFields는 정의된 모든 필드를 가져오지만 상속된 필드는 제외하는 반면, getFields는 그 상위 클래스와 상위 인터페이스들에서 public으로 선언된 필드를 모두 반환합니다.
> getDeclaredFields > This includes public, protected, default (package) access, and private fields, but excludes inherited fields.
> getFields > If this {@code Class} object represents a class, then this method returns the public fields of the class and of all its superclasses and superinterfaces.

2024-09-20 08:06 UTC, JINU-CHANG commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
생성자를 호출할 수 없는지(`getConstructor()관련 예외`)와 인스턴스화할 수 없는지(`newInstance()관련 예외`)는 다른 예외인 것 같은데 같은 error 메시지를 호출하네요! 분리해볼 수 있을까요?

2024-09-20 08:35 UTC, JINU-CHANG commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java
> +        requestDispatcher.forward(request, response);
좋습니다~! 지금 DispatcherServlet에 JspView 관련 코드가 삭제되지 않은 것 같은데 이것만 확인 부탁드려요!

2024-09-20 08:43 UTC, JINU-CHANG commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Constructor<?> secondConstructor = questionClass.getDeclaredConstructor(String.class, String.class, String.class);
한 클래스내에 서로 다른 생성자가 있을 때 어떻게 다르게 생성할 수 있는지 학습해보라는 의미로 이해했습니다. 크게 중요한 사항은 아니지만 그래도 secondConstructor라고 명시해주었으니 첫 번째 생성자와 다르게 생성해보는 건 어떨까요 ?-?

2024-09-20 08:49 UTC, JINU-CHANG commented on study/src/test/java/reflection/ReflectionTest.java
> +        assertThat(clazz.getCanonicalName()).isEqualTo("reflection.Question");
> getCanonicalName()은 자바 언어 스펙에서 제공하는 이름을 반환합니다!

조금만 더 구체적으로 설명해주실 수 있을까요~!

2024-09-20 08:50 UTC, JINU-CHANG requested changes
타칸 빠르게 리뷰반영해주셨네요!
몇가지 더 궁금한 사항이 있어 RC 보냅니다~

2024-09-20 12:17 UTC, jhon3242 reviewed
안녕하세요 제제! 놓쳤던 부분에 대해서 리뷰 반영하고 커멘트 달아두었습니다! 리뷰 부탁드립니다!😁

2024-09-20 12:17 UTC, jhon3242 commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Constructor<?> secondConstructor = questionClass.getDeclaredConstructor(String.class, String.class, String.class);
제가 의도를 잘못 파악하고 있었네요! 수정했습니다!😁 ([리뷰 반영](https://github.com/woowacourse/java-mvc/pull/658/commits/100f35151d7f89947dbe0d9a3bbce4929ea8c353))

2024-09-20 12:17 UTC, jhon3242 commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Field[] fields = questionClass.getDeclaredFields();
오호 상속된 필드도 가져오는 것은 놓치고 있었네요! 감사합니다!☺️

2024-09-20 12:17 UTC, jhon3242 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java
> +        requestDispatcher.forward(request, response);
넵! 지워볼게요! 다만 DispatcherServlet 에서 뷰에 대해 처리해주는 것은 지금의 요구사항이 아닌 것 같아서 이후 단계에서 처리하겠습니다! ([리뷰 반영](https://github.com/woowacourse/java-mvc/pull/658/commits/7caa10ec778bd7dffbe6f233868a8fd91437d5e4))

2024-09-22 05:15 UTC, JINU-CHANG approved these changes
타칸 모두 잘 반영해주셨네요 👍
이번 단계는 이만 머지하겠습니다~!

2024-09-22 05:15 UTC, merged