[MVC 구현하기 - 1단계] 뽀로로(조경찬) 미션 제출합니다.
woowacourse/java-mvc pull request #664
Opened 2024-09-18 12:32 UTC by jcoding-play

2024-09-20 07:40 UTC, ChooSeoyeon commented on study/src/test/java/reflection/ReflectionTest.java
> +        assertThat(clazz.getCanonicalName()).isEqualTo("reflection.Question"); //내부 클래스는 '.'로 구분
차이를 잘 적어주셨군요!

2024-09-20 11:12 UTC, ChooSeoyeon requested changes
안녕하세요 뽀로로! 리뷰어-리뷰이로 만나다니 새롭네요!
기능 깔끔하게 잘 구현해주셔서 학습 관점에서 바라본 리뷰를 주로 남겼습니다:)
뽀로로가 흥미있는 내용 위주로 선별해서 파보셔도 괜찮을 거 같습니다.
추가로, 테스트도 작성해주시면 좋을 거 같습니다!

2024-09-20 11:12 UTC, ChooSeoyeon commented on mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java
> +    RequestMethod[] method() default {GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS, TRACE};
default 값을 모든 메서드로 지정하신 이유가 궁금합니다!

2024-09-20 11:12 UTC, ChooSeoyeon commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            throw new RuntimeException(e);
RuntimeException(e)보다 더 구체적인 예외를 던지는 건 어떨까요?!

2024-09-23 05:00 UTC, kang-hyungu requested changes
뽀로로 구현은 잘 했는데 테스트 코드가 없네요.
테스트 코드도 작성하시기 바랍니다.

2024-09-23 07:44 UTC, ChooSeoyeon commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            return controllerClass.getDeclaredConstructor().newInstance();
더 나아가서 contorller를 여러 HandlerExecution들이 서로 다른 instance로 가져야 할지, 하나의 instance를 쓰면 어떨지도 고민해보면 좋을 거 같습니다. spring은 왜 controller를 싱글톤으로 관리하는 걸까요? 싱글톤으로 관리하는 편이 언제나 좋을까요? 어떤 경우에 서로 다른 instance를 쓰는 게 적절할까요? (feat. Junt4TestRunner에선 Junt4Test 클래스를 싱글톤으로 관리하지 않았지요! 왜 싱글톤으로 관리하면 안될까요?)

2024-09-25 17:17 UTC, jcoding-play commented on study/src/test/java/reflection/Junit3TestRunner.java
> +        Method[] methods = clazz.getDeclaredMethods();
getDeclaredXxx()와 getXxx()는 동일하게 작동하니 구체적인 예를 들기 위해, `getDeclaredMethods()`와 `getMethods()`로 설명을 드리겠습니다.

---

### 1. getMethods()

해당 클래스의 퍼블릭 메서드를 반환하고, 상속받은 부모 클래스에 정의된 퍼블릭 메서드도 반환합니다.

### 2. getDeclaredMethods()

해당 클래스에 선언된 모든 메서드를 반환합니다. 
즉 접근 제어자가 무엇이든 모든 메서드들을 반환하고, getMethods()와 다르게 상속받은 부모 클래스에 메서드들은 반환하지 않습니다.

성능적인 부분에선 상황에 따라 달라질 것으로 생각이 되지만,
평균적으로 getMethods()는 상속된 메서드들도 전부 다 반환하기 때문에 상대적으로 더 느릴 수 있습니다.

2024-09-25 17:18 UTC, jcoding-play commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Field[] fields = student.getClass().getDeclaredFields();
`getClass()` 메서드는 객체의 런타임 클래스 정보를 반환하여 객체가 어떤 클래스의 인스턴스인지를 알 수 있습니다. 클래스는 메타데이터를 포함하고 있기 때문에, getClass() 메서드는 이러한 메타데이터에 접근할 수 있습니다.

`defineClass()`는 바이트 코드 배열을 사용하여 새로운 클래스를 정의하고 로딩하는 데 사용됩니다. 그래서 클래스를 동적으로 생성하고, 메타데이터를 얻을 순 없습니다.

---

한번 defineClass()를 직접 사용해보고 싶었는데, 지금 지원하지 않는것 같네요ㅠㅠ 😭
`@Deprecated` 되어있는 것은 확인했습니다.

<img width="552" alt="스크린샷 2024-09-25 오후 9 55 29" src="https://github.com/user-attachments/assets/b194a8d9-2736-4678-8a6c-d89a5db78ea9">

2024-09-25 17:18 UTC, jcoding-play commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Method[] methods = animalClass.getDeclaredMethods();
new Student().getClass().getDeclaredxx()는 새로운 Student 객체가 메모리에 생성되고, 해당 객체의 런타임 클래스 정보를 얻습니다. 그러므로 객체가 어떤 클래스의 인스턴스인지 알 수 있습니다.

Student.class.getDeclaredxx()는 새로운 인스턴스를 생성하지 않고 Student Class 객체를 직접 참조합니다.

다형성으로 인해 특정 인스턴스의 런타임 클래스에 따라 달라지는 메서드가 있다면 new Student().getClass().getDeclaredxx()에서는 확인할 수 있지만, Student.class.getDeclaredxx()는 확인할 수 없습니다.

2024-09-25 17:19 UTC, jcoding-play commented on study/src/test/java/reflection/Junit4TestRunner.java
> +                Junit4Test instance = clazz.getDeclaredConstructor().newInstance();
아뇨..ㅎㅎ 의도하지 않았습니다. 🥲

개인적으로 학습 테스트를 진행할 때, 리플렉션을 직접 코드로 작성해보는 것이 처음이라 각각의 작동 방식에 초점을 두고 진행하느라 신경쓰지 못했네요! 

궁금한 부분은 아래 커멘트에 달도록 할게요!

2024-09-25 17:19 UTC, jcoding-play commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java
> +        requestDispatcher.forward(request, response);
forward 메서드를 호출한 서버 측 포워딩 방식은 현재 요청과 응답 객체를 다른 리소스로 전달합니다. 다른 리소스로 전달되지만 사용자가 볼때 URL 주소는 변경되지 않으며, 요청은 서버 내에서 처리됩니다.

sendRedirect()를 이용한 클라이언트 측 리다이렉션 방식은 서버가 클라이언트에게 새로운 URL로 이동하라는 응답을 보냅니다. 클라이언트는 이 응답을 수신 후, 서버에 새로운 요청을 보내게 됩니다. 그래서 사용자는 새로운 URL 주소를 보게 됩니다.

>여기서 포워딩 후 요청은 어디로 갈까요?

요청은 지정된 경로(viewName)에 해당하는 리소스(JSP 페이지 또는 다른 서블릿)로 전달되고, 전달받은 리소스가 응답을 생성하게 됩니다.

2024-09-25 17:19 UTC, jcoding-play commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            return controllerClass.getDeclaredConstructor().newInstance();
>61라인을 59라인으로 옮기는 건 어떨까요?!

오호 좋은 것 같네요! 👍
controller가 상태를 가지지 않기 때문에 싱글톤으로 인해 발생할 수 있는 데이터 무결성, 동시성 문제에서 벗어난다 생각이 되네요!

수정했습니다!

>spring은 왜 controller 클래스를 싱글톤으로 관리하는 걸까요? 싱글톤으로 관리하는 편이 언제나 좋을까요? 어떤 경우에 서로 다른 instance를 쓰는 게 적절할까요?

일반적으로 controller는 일반적으로 상태를 가지지 않고, 싱글톤을 사용하면 새로운 인스턴스를 매번 생성하지 않아 메모리 사용을 최적화하고 성능을 향상시킬 수 있습니다.

그렇지만 무엇이든 상황에 맞게 사용하는 것이 좋은 것처럼 매번 싱글톤으로 관리하는 것이 좋은 것은 아닙니다.

싱글톤은 하나의 인스턴스를 반환하기 때문에 상태를 가지게 된다면 전역 상태를 가지게 됩니다.
이때 여러 클래스에서 싱글톤 패턴이 적용된 인스턴스를 사용하여 상태 값을 변경했다고 했을 때 각각의 사용자는 자신이 의도하지 않은 결과를 받을 것입니다. 

즉, 상태를 가지는 클래스에서 서로 다른 instance를 쓰는게 적절합니다.

>작성해주신 Junt4TestRunner에선 Junt4Test 클래스를 싱글톤으로 관리하지 않았지요! 왜 싱글톤으로 관리하면 안될까요?

개인적으로 Junit4Test도 상태를 가지지 않아 싱글톤으로 관리한다면 더 효율적이라 판단했는데, 도라는 왜 Junit4Test를 싱글톤으로 관리하면 안된다고 생각한건가요??

2024-09-25 17:20 UTC, jcoding-play commented on mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java
> +    RequestMethod[] method() default {GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS, TRACE};
단순히 `@RequestMapping()에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원해야 한다.`라는 요구 사항을 보고 RequestMapping Enum 클래스에 정의된 순서 그대로 디폴트 값을 설정하였습니다.

하지만 이렇게 설정하면 저장되는 순서에 따라 반환되는 HandlerExecution이 달라질 수 있다는 점을 고려하지 못했네요!.. 😭

클라이언트가 요청할 때 가장 일반적으로 사용되는 메서드가 먼저 처리될 수 있도록 자주 사용되는 HTTP 메서드를 우선순위로 두어 다음과 같은 순서로 변경했습니다. 
{GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD, TRACE}

2024-09-26 13:12 UTC, merged