[1단계 - @MVC 구현하기] 알파카(최휘용) 미션 제출합니다.
woowacourse/java-mvc pull request #668
Opened 2024-09-18 15:07 UTC by slimsha2dy

안녕하세요 이상! 이번 MVC 구현하기 미션을 함께하게 된 알파카입니다 🙇 
제가 코드 중간 중간에 학습을 위한 용도로 주석을 함께 남기고 있어서 조금 지저분해 보일 수도 있는데 너무 심하다 싶으시면 말씀해 주세요!
그럼 이번 미션 리뷰 잘 부탁드립니다!!

2024-09-19 04:54 UTC, kunsanglee requested changes
안녕하세요 알파카! 🦙
구현 잘 해주신 것 같아요! 주석도 남겨주셔서 어떤 의도를 가진 코드인지 알아보기 좋았습니다.
코멘트와 질문 간단히 남겨봤습니다.
그리고 다음 리뷰 요청 때는 다른 클래스들도 테스트 추가해주세요~~😇

2024-09-19 04:54 UTC, kunsanglee commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Student student = new Student();
이 부분도요~~

2024-09-19 04:54 UTC, kunsanglee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
method가 없는 HttpServletRequest 객체가 만들어질 수 있나요?? 🤔

2024-09-19 04:54 UTC, kunsanglee commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    @DisplayName("메서드와 url로 Handler를 찾아 실행한다")
DisplayName이 잘못 된 것 같습니당

2024-09-19 04:54 UTC, kunsanglee commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    }
👀

2024-09-19 04:54 UTC, kunsanglee commented on mvc/src/test/java/samples/TestController.java
> +    }
saveWithGet 메서드는 무슨 목적으로 추가된 걸까요? 🤔
그리고 RequestMapping의 value는 /post-test인데, log는 post method라고 되어있어요!

2024-09-19 05:02 UTC, slimsha2dy commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
미션 요구사항의
>@RequestMapping()에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원해야 한다.

때문에 추가한 부분입니다.
http 메서드가 비어 있을 경우 http 메서드와 상관 없이 url만 일치하는 핸들러를 찾는 로직이라 메서드 명을 저렇게 짓게 되었습니다!

2024-09-19 05:18 UTC, slimsha2dy commented on mvc/src/test/java/samples/TestController.java
> +    }
이것도 메서드가 없을 경우 모든 메서드를 지원해야 한다는 요구사항에서 생길 수 있는 예외 처리를 위한 메서드입니다.
실제로 스프링에서도 한 요청에 여러 핸들러가 매핑될 수 있는 상황이면 예외가 생기는 것으로 아는데, 그런 경우를 잘 예외로 처리하는지 테스트하기 위해 추가했습니다.
"/post-test"라는 url을 `GET`, `POST` 요청으로 처리할 수 있는데 메서드를 지정하지 않아서 두 개의 핸들러가 매핑되는 예외 상황을 발생시키기 위해 추가한 부분이라고 하면 될 것 같아요.
다만 메서드 명과 log는 좀 더 이해할 수 있게 바꿔볼 수 있을 것 같아서 이 부분은 반영해보겠습니다~

2024-09-19 05:39 UTC, slimsha2dy commented on study/src/test/java/reflection/Junit3TestRunner.java
> +        Junit3Test junit3Test = new Junit3Test();
`clazz.getDeclaredConstructor().newInstance()`를 의도하신게 맞을까요?
지금 코드를 해당 코드로 변경하면 기존 코드보다 길어지기도 하고 try-catch 문도 추가되어 가독성 측면에서 좋지는 않을 것 같다고 생각합니다!
또한 reflection 기능을 통해 인스턴스를 생성하는 학습 테스트는 `ReflectionTest`에 이미 있기도 하고 현재 학습 테스트의 의도에서도 벗어난다고 생각하는데 혹시 어떤 의도로 제안하신 건지 궁금합니다 ! 🫡

2024-09-19 05:44 UTC, slimsha2dy commented on study/src/test/java/reflection/Junit3TestRunner.java
> +                });
메소드를 실행하라는 요구사항 때문에 콘솔 로그로만 확인했었는데 검증을 추가하면 좀 더 테스트스러운 테스트가 되겠네요 ㅎㅎ
이전엔 잘 몰랐는데 마침 `verify`라는 검증 메서드를 알게 되어서 적용할 수 있을 것 같아요!
좋은 지적 감사합니다 👍

2024-09-19 11:45 UTC, kunsanglee commented on study/src/test/java/reflection/Junit3TestRunner.java
> +        Junit3Test junit3Test = new Junit3Test();
음 저도 확실치 않지만 말씀드리자면, 생성자를 호출하는 대신 리플렉션을 사용해서 클래스의 메타 정보를 읽고, 그 데이터를 바탕으로 이런저런 처리를 하는 것에 대한 학습이라고 생각해서 생성자로 인스턴스를 생성하지 않고 `clazz.getDeclaredConstructor().newInstance()` 메서드를 호출하는게 맞다고 생각했습니다! 😀

2024-09-20 12:30 UTC, kunsanglee commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    @DisplayName("메서드와 url로 Handler를 찾아 실행한다")
이 부분은 DisplayName이 중복되어 위 아래에 있어서 말씀드렸습니다! 😅

2024-09-20 12:30 UTC, kunsanglee commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    }
이 부분은 `@DisplayName("메소드 없이 요청을 보내면 모든 메소드를 지원해야 한다")` 전제가 잘못된 테스트인 것 같아서 코멘트 남겼어요! 😄

2024-09-22 14:09 UTC, slimsha2dy commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
제가 잘못 이해했었네요.. ㅎㅎ
요청이 아닌 어노테이션에서 메서드 설정이 안 돼있는 경우를 처리하도록 수정하겠습니답!

2024-09-22 14:31 UTC, slimsha2dy commented on study/src/test/java/reflection/Junit3TestRunner.java
> +        Junit3Test junit3Test = new Junit3Test();
오홍.. 이상의 말도 일리 있다고 생각합니다.
하지만 순서를 지정해 주신, 단계별로 테스트의 요구사항을 구현하면서 리플렉션의 사용법을 학습해나가는 **학습 테스트**의 목적을 생각해 봤을 때, 리플렉션을 모르는 사람이 가장 처음 단계인 메서드 처리 관련 학습 테스트에서 인스턴스를 리플렉션으로 만든다는 것은 자연스럽지 않다고 생각하긴 합니다. 학습 테스트의 `TODO`에도 전혀 관련 내용이 나와 있지 않아 학습테스트의 요구 사항이 아닌 것 같고요!
또한 앞서 말씀드린 것처럼 이미 뒷 단계에 인스턴스를 생성하는 테스트가 있기도 해서 이 앞부분에서 뒤에서 학습할 내용을 필수적으로 요구한다고 생각하는 것도 자연스러운 흐름은 아니라고 생각합니다.
만약 학습 테스트가 아니라 리플렉션의 사용법을 잘 알고 있는지를 확인하기 위한 테스트라면 이견의 여지 없이 이상의 말씀이 맞다고 생각합니다.
물론 학습 테스트를 마친 지금 시점에서야 금방 넣을 수는 있지만 필수 요구사항이 아닌 선택사항이라는 생각이 드네요.

2024-09-22 14:35 UTC, slimsha2dy commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    }
넵 이부분도 위에서 말씀드린 것처럼 요구사항을 잘못 이해한 부분이네요. 테스트를 요구사항에 맞게 수정해서 다시 제출하겠습니다.

2024-09-22 15:40 UTC, slimsha2dy commented on mvc/src/test/java/samples/TestController.java
> +    }
이 부분도 위 두개와 마찬가지로 요구사항 잘못 이해로 인해 생겨난 부분이네요..ㅎㅎ
요구사항을 테스트하기 위한 메서드로 수정하겠습니다.

2024-09-23 05:28 UTC, kunsanglee approved these changes
알파카 테스트도 꼼꼼히 작성해주시고 구현도 잘 해주셨어요! 💯
다음 미션 이어서 화이팅 해봅시다!! 🦙

2024-09-23 05:28 UTC, kunsanglee commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    void getWithoutMethod(RequestMethod requestMethod) throws Exception {
오 `@ParameterizedTest`와 `@EnumSource` 잘 사용해주셨네요 👍

2024-09-23 05:28 UTC, kunsanglee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
추후에 Stream으로 values를 순회하면서 추가하도록 리팩터링 하면 더 좋겠네요 👍

2024-09-23 05:28 UTC, kunsanglee commented on study/src/test/java/reflection/ReflectionsTest.java
> +        repositoryClasses.forEach(clazz -> System.out.println("@Repository class: " + clazz));
반영을 바라는건 아니고 말씀만 드릴게요 👍
저번 http 미션 때 학습했던 InputStream, OutputStream을 활용하면 실제로 출력되는 문자열들을 검증에 사용할 수 있습니다! 나중에 학습해보시지요~

2024-09-24 11:19 UTC, merged