[MVC 구현하기 - 1단계] 메이슨(김경원) 미션 제출합니다
woowacourse/java-mvc pull request #674
Opened 2024-09-19 04:49 UTC by masonkimseoul

안녕하세요 조조!

추석은 잘 보내셨나요?
이번 MVC 미션 1단계를 완료하여 리뷰를 요청합니다.
몇 가지 질문 사항이 있는데, 코멘트로 남겨두겠습니다.

감사합니다!

2024-09-19 06:51 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +        Constructor<?> constructor = clazz.getDeclaredConstructor();
public으로 선언된 클래스의 생성자가 없을 수도 있을 것 같아 getDeclaredConstructor()로 생성자를 가져왔습니다.
그런데 제가 생각한 예외 말고도 다른 예외가 추가로 발생할 수 있을 것 같은데요(인자가 필요한 경우 등).
조조는 이 부분을 어떻게 구현했는지 궁금합니다!

2024-09-19 17:35 UTC, eun-byeol requested changes
메이슨 안녕하세요! 리뷰어 조조입니다~

객체 분리와 테스트에 신경을 많이 써주셨네요! 코드가 전반적으로 깔끔해서 읽기 편했어요👍
간단히 학습용으로 정리할 부분 + 코드에 대한 개인적인 질문을 남겼어요. 물론 꼭 다 반영할 필요는 없어요!

다음번에 요청주시면 approve 하겠습니다~
리뷰는 주말포함 24시간룰 적용해서 최대한 하고, 늦어지는 경우에는 따로 DM 드릴게요!

2024-09-19 17:35 UTC, eun-byeol commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +        Constructor<?> constructor = clazz.getDeclaredConstructor();
> 그런데 제가 생각한 예외 말고도 다른 예외가 추가로 발생할 수 있을 것 같은데요(인자가 필요한 경우 등).

인자가 필요한 경우라면, 스프링에서 DI 시에 다른 객체를 들고있는 상황이라고 생각해요. controller가 service 객체를 갖고 있는것처럼요.
그걸 구현해야 한다면, 필드를 조회해서 일치하는 생성자를 찾는 방법을 쓸 것 같아요.
지금 스펙에서는 메이슨과 유사하게 구현했고, 대신 try/catch문으로 감싸서 로그를 찍고 있습니다.

2024-09-19 17:35 UTC, eun-byeol commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +    }
❓매번 컨트롤러의 인스턴스를 새롭게 만들 필요가 있을까요? 스프링처럼 싱글턴으로 동작할 순 없을까요? 꼭 반영할 필요는 없지만, 고민해보셔도 좋을 것 같아요.

2024-09-19 17:35 UTC, eun-byeol commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeys.java
> +public class HandlerKeys {
클래스 분리 깔끔하고 좋네요👍

2024-09-19 17:35 UTC, eun-byeol commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeysTest.java
> +public class HandlerKeysTest {
꼼꼼한 테스트👍

2024-09-19 17:35 UTC, eun-byeol commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeys.java
> +        return handlerKeys;
방어적 복사를 적용하는건 어떤가요?😮

2024-09-19 17:35 UTC, eun-byeol commented on study/src/test/java/reflection/ReflectionTest.java
> +        assertThat(clazz.getCanonicalName()).isEqualTo("reflection.Question");
❓`getName()`, `getCanonicalName()`는 어떤 차이가 있을까요?

2024-09-19 17:35 UTC, eun-byeol commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
❓for문과 stream을 사용하는 기준이 있으실까요?
for문 안에 있는 stream은 메서드로 분리해도 좋을 것 같아요!

2024-09-21 09:22 UTC, masonkimseoul commented on study/src/test/java/reflection/Question.java
> +                && Objects.equals(createdDate, question.createdDate);
앗 그렇네요! 패키지 단위로 자동 정렬을 하다보니 저렇게 된 것 같습니다. 수정하겠습니다.

2024-09-21 09:37 UTC, masonkimseoul commented on study/src/test/java/reflection/ReflectionTest.java
> +        final Constructor<?>[] constructors = questionClass.getConstructors();
getConstructors()는 상속 받은 생성자를 포함하여, 접근 제어자가 public인 모든 생성자를 반환합니다.
getDeclaredConstructors()는 상속 받은 생성자를 제외하고, 접근 제어자와 상관 없이 클래스 내부에서 선언된 모든 생성자를 반환합니다.

2024-09-21 10:08 UTC, masonkimseoul commented on study/src/test/java/reflection/ReflectionTest.java
> +        assertThat(clazz.getCanonicalName()).isEqualTo("reflection.Question");
`getName()`은 JVM에서 사용하는 바이트코드 레벨에서의 이름을 반환합니다.
`getCanonicalName()`은 정규화된 형태로, 고유하게 식별할 수 있도록 전체 경로(패키지 + 클래스)를 포함한 이름을 반환합니다.

두 메서드 모두 일반적으로 사용할 때에는 반환하는 결과 값이 같지만, 내부 클래스에 대해 조회하는 경우 반환하는 결과 값이 달라집니다.
`getName()`은 `$` 기호를 사용하여 외부 클래스와 내부 클래스를 구분하며, `getCanonicalName()`은 `.` 기호를 사용하여 외부 클래스와 내부 클래스를 구분합니다.

Question.class 내부에 InnerClass.class가 존재하고 이를 조회할 경우,
getName() 사용 시 결과 : `reflection.Question$InnerClass`
getCanonicalName() 사용 시 결과 : `reflection.Question.InnerClass`

2024-09-21 13:44 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
private 메서드가 많아지는 것을 방지하기 위해 stream을 사용하는 편입니다.
private 메서드가 너무 많이 연결되면 가독성이 오히려 떨어지는 것 같습니다.
분리를 시도해봤는데, 메서드명도 어색하고 기능에 비해 메서드가 많아지는 것 같아요.
그래서 분리를 하지 않을려고 하는데, 어떻게 생각하시나요?

2024-09-22 04:46 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeys.java
> +        return handlerKeys;
👍 적용해보도록 하겠습니다!

2024-09-22 04:46 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeys.java
> +    private static final List<HandlerKey> handlerKeys = new ArrayList<>();
오 👍 짚어주셔서 감사합니다

2024-09-22 06:28 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +    }
컨트롤러 인스턴스의 생성 로직을 변경해보겠습니다!

2024-09-22 16:17 UTC, eun-byeol approved these changes
메이슨, 리뷰 잘 반영해주셨네요👍
개념도 잘 정리해주셔서 덕분에 저도 공부가 됐어요.

몇가지 간단한 질문을 남겼는데, 다음 step에서 반영해주셔도 될 것 같아서
이만 merge 하겠습니다!

2024-09-22 16:17 UTC, eun-byeol commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeys.java
> +    }
❓이 방식을 선택한 이유가 궁금해요. 반환된 리스트와 내부 객체의 변경에 대해서는 고려해보셨을까요?🤔

2024-09-22 16:17 UTC, merged