[MVC 구현하기 - 1단계] 트레 미션 제출합니다.
woowacourse/java-mvc pull request #677
Opened 2024-09-19 07:39 UTC by takoyakimchi

안녕하세요 테바 🐼
페어 프로그래밍 굉장히 즐겁게 했던 기억이 있는데, 리뷰어-리뷰이로 다시 만나게 되어 기쁘네요!

처음부터 깔끔하게 코드를 작성하지 않아서 그런지, 메서드 분리가 어색한 부분이 있다고 느껴지네요.
전반적으로 조금이라도 어색한 부분 있으면 피드백 부탁드립니다!

2024-09-21 15:55 UTC, ksk0605 requested changes

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
```suggestion
        RequestMethod requestMethod = RequestMethod.from(request.getMethod());
        String url = request.getRequestURI();
        
        HandlerKey handlerKey = new HandlerKey(url, requestMethod);
        return handlerExecutions.get(handlerKey);
    }
```

위 순서 중 from 은 예외를 발생시킬 수 있는 함수네요. 메서드에서 필요한 정보를 초기화 하는 작업 중 예외가 발생할 수 있는 상황들은 가능한 앞쪽에 배치하는게 좋을 수 있겠습니다. 위 메서드에서는 사소한 부분이긴 하지만 항상 예외는 빠르게 발생시킬 수록 불필요한 작업을 줄일 수 있으니까요!

```java
String url = request.getRequestURI();
```
그리고 마찬가지로 사소한 부분입니다만 리퀘스트에서 uri를 가져오는 변수의 이름은 url이네요.
아래의 `addMappings` 메서드에서는 `HandlerKey`의 인자로 넘어가는 변수의 이름이 uri 로 적혀있구요. 
uri와 url은 비슷하지만 확실히 다릅니다. 통일성의 문제도 있겠지만 요청 매핑 작업에서 필요한 것이 uri인지 url인지는 생각해볼 지점일 것 같아요!

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +
> @RequestMapping()에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원해야 한다.

는 요구사항을 구현한 부분이네요. 매우 적절한 구현이지만 구현과 별개로 코드의 의미를 알기 위해 시간이 필요하다는 단점이 있다고 느껴집니다. 아래와 같이 메서드를 분리해서 의미를 분명하게 담아보는건 어떨까요?

```suggestion
private void addMappings(Method mapperMethod, Object controllerInstance) {
    RequestMapping annotation = mapperMethod.getAnnotation(RequestMapping.class);
    String uri = annotation.value();
    
    RequestMethod[] requestMethods = getRequestMethods(annotation);
    // ...
}

// 요청 메서드 목록을 가져오는 메서드
private RequestMethod[] getRequestMethods(RequestMapping annotation) {
    // 메서드가 명시되지 않으면 모든 HTTP 메서드를 기본값으로 사용
    RequestMethod[] requestMethods = annotation.method();
    if (requestMethods.length == 0) {
        return RequestMethod.values()
    }
    return requestMethods;
}
```

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        };
오우 바로 오버라이딩해서 반환해버리는 센스~

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
>      }
요구사항은 아니었지만 `ManualHandlerMapping` 과 같은 기능을 하는 initialize(), getHandler() 가 있는 것으로 보아 인터페이스로 추상화 해볼 수 있겠네요!

실제 스프링 MVC 의 interface - abstract class - concrete class 로 발전할 여지도 있구요

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
>      public Object getHandler(final HttpServletRequest request) {
요구사항은 아니었지만, 위 두 함수는 `ManualHandlerMapping` 와 같은 기능을 하고 있으니 인터페이스로 추상화 해볼 수 있겠네요. 

스프링에서 자주 사용하는 interface - abstract class - concrete class 구조의 기반이 될 수 있을 것 같아요!

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
> @RequestMapping()에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원해야 한다.

는 요구사항을 구현한 코드인 것 같아요! 구현은 매우 적절하지만 `requestMethods.length == 0` 가 위 요구사항의 의미를 적절히 반영하고 있는지는 생각해봐야 할 것 같아요. 아래와 같이 메서드를 분리해보는 것은 어떤가요? 

```suggestion
    private void addMappings(Method mapperMethod, Object controllerInstance) {
    RequestMapping annotation = mapperMethod.getAnnotation(RequestMapping.class);
    String uri = annotation.value();
    
    RequestMethod[] requestMethods = getRequestMethods(annotation);
    // ...
}

// 요청 메서드 목록을 가져오는 메서드
private RequestMethod[] getRequestMethods(RequestMapping annotation) {
    // 메서드가 명시되지 않으면 모든 HTTP 메서드를 기본값으로 사용
    RequestMethod[] requestMethods = annotation.method();
    if (requestMethods.length == 0) {
        return RequestMethod.values();
    }
    return requestMethods;
}
```

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        };
바로 오버라이딩 해서 리턴이라니 센스만점~

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    void methodIsNotDefined(String method) throws Exception {
트레는 테스트 코드에서 ParameterizedTest 를 적절히 잘 사용하는 능력이 있네요!

2024-09-21 15:55 UTC, ksk0605 commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    }
null 발생 가능성도 테스트에 넣어놓으신 것 너무 좋네요! 

다만 DispatcherServlet에서 실제로 NullPointerException의 발생 가능성에 대한 대응은 없는 것으로 보여요.
어떻게 개선해볼 수 있을까요?

2024-09-21 15:58 UTC, ksk0605 commented
안녕하세용 트레! 리뷰가 늦어서 죄송해요 ㅠㅠ 
요구사항이 1단계라 많지 않기도했고 트레가 워낙 잘 구현해줘서 리뷰할 내용이 많지는 않았어요. 

자세한 내용은 코멘트 확인해주세요!

2024-09-23 05:04 UTC, kang-hyungu reviewed
트레 간단한 피드백 남겼으니 참고하세요

2024-09-23 05:04 UTC, kang-hyungu commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final HttpServletRequest request,
자바 스타일 가이드에서도 이렇게 쓰나요? 이건 코틀린 스타일 아닌가요?

2024-09-23 07:25 UTC, takoyakimchi commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
1. 저도 예외를 빠르게 발생시키는 방식을 좋아해요! 사소한 부분인데 꼼꼼히 봐주셔서 감사합니다! 😄 
2. URI는 식별자, URL은 자원의 위치를 나타내는군요. RFC2616에서도 Request **URI**라고 표시하고 있기 때문에 URI가 더 적절하겠네요.

2024-09-23 07:33 UTC, takoyakimchi commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +
`@interface`는 `default`라는 옵션으로 디폴트 값을 줄 수 있다는 것을 몰랐었어요.
따라서 현재는 `RequestMapping`으로 옮겼습니다!

2024-09-23 07:38 UTC, takoyakimchi commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        };
근데 뭔가 코드가 깔끔하지 않은 것 같아서 `HandlerExecution` 내부로 지금은 로직 옮겼습니다!

2024-09-23 07:38 UTC, takoyakimchi commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    void methodIsNotDefined(String method) throws Exception {
고마워요 히히히 👍

2024-09-23 08:42 UTC, takoyakimchi commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final HttpServletRequest request,
구글 스타일 가이드에서는 해당 내용을 찾지 못했습니다. [Twitter에서 권장하는 방법](https://github.com/twitter-archive/commons/blob/master/src/java/com/twitter/common/styleguide.md#indent-style)을 사용해 보겠습니다!

2024-09-23 11:45 UTC, takoyakimchi commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
> +    }
NPE를 터뜨릴 게 아니라 404 상태 코드 + 404.jsp 화면을 보여주도록 고쳐볼게요!

2024-09-23 11:46 UTC, takoyakimchi commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
>      public Object getHandler(final HttpServletRequest request) {
다음 단계에서 리팩토링 진행해볼게요~~!

2024-09-25 14:22 UTC, ksk0605 approved these changes
안녕하세요 트레! 전체적으로 코드도 많이 깔끔해지고
고민도 많이 한 흔적이 보여서 리뷰는 많이 남기지 않았습니다. 
간단한 코멘트만 확인해주시고 빠르게 머지하겠습니다. 

다음 미션에서 더 많은 이야기 나누시죠!

2024-09-25 14:22 UTC, ksk0605 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        for (Class<?> controllerClass : findControllerClasses()) {
initialize는 생성자에서  사용되고 있음에도 public 메소드로 사용할 수 있는 여지를 남겨두고 있어요. 
트레의 의도가 있을까요?

2024-09-25 14:22 UTC, merged