[MVC 구현하기 - 1단계] 제우스(신재우) 미션 제출합니다.
woowacourse/java-mvc pull request #679
Opened 2024-09-19 07:48 UTC by zeus6768

안녕하세요 백호! 👋

MVC 구현하기 미션으로 만나게 되어 정말 반가워요. 😄

리뷰 잘 부탁드립니다!

2024-09-19 10:08 UTC, Arachneee requested changes
안녕하세요. 제우스!

리뷰어로 만나서 반갑습니다.

코드를 깔끔하게 작성해주셔서 리뷰하기 편했어요!

코멘트 남겨드렸으니 답변 부탁드려요~

2024-09-19 10:08 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +                .flatMap(controller -> Arrays.stream(controller.getDeclaredMethods()))
getDeclaredMethods()와 getMethods()의 차이는 무엇인가요?

2024-09-19 10:08 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) handler.invoke(controller, request, response);
handler method의 파라미터 인자가 request, response가 아닌 경우 어떻게 되나요?

2024-09-19 10:08 UTC, Arachneee commented on mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java
> +    RequestMethod[] method() default {GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS, TRACE};
오! default를 바꿔버리는 방법도 있겠군요! 👍 

RequestMethod가 바뀔 일은 거의 없겠지만 혹시나 추가되면 변경 포인트가 2개가 될 것 같아요.

2024-09-19 10:08 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        HandlerKey handlerKey = new HandlerKey(requestUri, RequestMethod.valueOf(method));
RequestMethod에 없는 method이면 어떻게 되나요?

2024-09-19 10:08 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            handlerExecutions.put(handlerKey, execution);
HandlerKey가 중복되었을 때 검증이 있을면 좋을 것 같아요.

2024-09-19 10:08 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +                .collect(Collectors.toSet());
Set을 사용하신 이유가 있으신가요?
Method는 equal과 hashCode를 어떻게 재정의하고 있나요?

2024-09-22 06:47 UTC, zeus6768 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) handler.invoke(controller, request, response);
백호의 리뷰를 받고 테스트를 해봤습니다. 

파라미터 인자가 다를 경우 IllegalArgumentException이 발생합니다. 

파라미터 개수가 안 맞을 경우
<img width="794" alt="Screenshot 2024-09-22 at 12 35 34 PM" src="https://github.com/user-attachments/assets/9dae4f1b-9f12-43d9-a7f0-25c66919112f">

파라미터의 타입이 다를 경우
<img width="785" alt="Screenshot 2024-09-22 at 12 35 55 PM" src="https://github.com/user-attachments/assets/42adb1f8-c4d7-46b7-862a-5f2bde73d9ab">

메서드 시그니처가 항상 같다는 보장이 없으니 예외처리를 해주는 게 좋겠네요.

반영하겠습니다!

2024-09-22 07:02 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +                .flatMap(controller -> Arrays.stream(controller.getDeclaredMethods()))
getDeclaredMethods 를 사용하신 이유는 private 으로 선언해도 동작하는 기능을 제공하고 싶어서 의도하신거군요!

2024-09-22 07:13 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +                .collect(Collectors.toSet());
자세한 설명 감사합니다!

설명해 주신 equals 조건에 의해 Method가 중복될 가능성은 없겠네요.
그렇다면 ArrayList를 사용하는 것도 문제가 없겠죠?
HashSet이 ArrayList보다 메모리를 더 소모하는데 굳이 Set을 사용할 필요가 있을까? 해서 남긴 질문이었습니다.
꼭 반영하지 않으셔도 괜찮아요.

2024-09-22 07:15 UTC, Arachneee approved these changes

2024-09-22 07:16 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
👍

2024-09-22 07:16 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +                && types[RESPONSE_PARAMETER_INDEX].equals(HttpServletResponse.class);
👍

2024-09-22 07:17 UTC, Arachneee commented
안녕하세요 제우스! 

리뷰 반영해주셔서 감사해요!

이만 머지하고 다음 단계를 진행해도 좋을 것 같아요!

2024-09-22 07:17 UTC, merged