[MVC 구현하기 - 1단계] 땡이(정지호) 미션 제출합니다
woowacourse/java-mvc pull request #680
Opened 2024-09-19 07:52 UTC by J-I-H-O

잉크 안녕하세요! 처음으로 인사 드리네요 😊

2단계가 Legacy MVC와 `@MVC`를 통합하는 미션인 만큼, 기존에 작성되어있던 Controller들은 아직 지원을 하지 않도록 했어요.
즉 현재는 `@Controller`와 `@RequestHanlder` 어노테이션이 붙은 클래스와 메서드만 지원합니다.
이에 따라 Application은 정상적으로 동작하지 않을거에요! 학습 테스트와 AnnotationHandlerMappingTest 가 정상적으로 동작하는지 위주로 확인해주시면 감사드리겠습니다.

그럼 잘 부탁드려요!

2024-09-22 08:28 UTC, yechop requested changes
안녕하세요 땡이!
리뷰가 늦어져 죄송합니다
열심히 뜯어봤는데 워낙 잘 해주셔서 남길게 많이 없었네요
mvc 미션동안 잘 부탁드립니다

2024-09-22 08:28 UTC, yechop commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +                .stream()
stream() 없이 forEach() 만 사용해도 되겠네요!

2024-09-22 08:28 UTC, yechop commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private void putHandlerExecution(String mappingUrl, RequestMethod requestMethod, Class<?> clazz, Method method) {
전체적으로 메서드 파라미터에 final 유무를 통일해주시면 의도가 더 잘 전달될 것 같아요

2024-09-22 10:05 UTC, J-I-H-O commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +                .stream()
오~~ 좋아요! 반영했습니다!

2024-09-25 10:41 UTC, J-I-H-O commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private void putHandlerExecution(String mappingUrl, RequestMethod requestMethod, Class<?> clazz, Method method) {
개인적으로 파라미터에 final 키워드 붙이는걸 선호하지는 않는데요, 
기반 코드에 final 키워드가 붙어있는 만큼 모두 붙이는 쪽으로 통일 시켜주었습니다~~

2024-09-25 10:47 UTC, J-I-H-O commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        reflections.get(SubTypes.of(TypesAnnotated.with(Controller.class)).asClass())
![image](https://github.com/user-attachments/assets/cb7c130d-fcb4-4d3b-8a0a-74bd82c7451d)

내부적으로 제가 작성한 형태와 거의 같은 형태로 메서드를 호출하네요 😅
해당 부분 말씀해주신 메서드를 호출하도록 변경했습니다! 훨씬 더 간결해 보이고 좋네요 👍

2024-09-25 11:20 UTC, J-I-H-O commented
잉크 안녕하세요~~
말씀해주신 내용 반영하고 다시 리뷰 요청 드립니다!
테스트도 아주 조금 짜봤는데 적절한지 함께 확인 부탁드리겠습니다!

2024-09-26 02:00 UTC, yechop approved these changes
잘 반영해주셨네요 
1단계 고생하셨습니다!

2024-09-26 02:02 UTC, yechop commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private void putHandlerExecution(String mappingUrl, RequestMethod requestMethod, Class<?> clazz, Method method) {
파라미터에 final 붙이는건 왜 선호하지 않으시는지 궁금합니다!

2024-09-26 02:06 UTC, merged