[MVC 구현하기 - 1단계] 페드로(류형욱) 미션 제출합니다
woowacourse/java-mvc pull request #687
Opened 2024-09-19 16:53 UTC by hw0603

반갑습니다 <img src="https://emoji.slack-edge.com/TFELTJB7V/moly/cdc41a6e3758ade4.jpg" height=20></img>

첫 페어 이후로 미션에서는 오랜만에 보네요🙂

리뷰 잘 부탁드립니다~

2024-09-20 14:04 UTC, jminkkk requested changes
안녕하세요 페드로 너무너무 반갑네요~~~~~~~~~~~~

굉장히 꼼꼼하게 코드 작성해주신 것 같아, 저도 많이 배웠습니다 👍🍀
미처 챙기지 못한 부분들도 덕분에 알게 되었어요.

코멘트 남겨보았으니 확인해주시면 감사하겠습니다 
이번 미션 함께 재미나게 보내봅시다 🔥

2024-09-20 14:04 UTC, jminkkk commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private boolean explicitHttpMethodNotExist(RequestMethod[] requestMethods) {
이 메서드의 시그니처를 봤을 때 메서드명이 명확하게 전달되지 않는 것 같아요 🤔
`hasNotExplicitHttpMethods` 또는 `hasNoHttpMethods` 등등은 어떨까요?

2024-09-20 14:10 UTC, hw0603 commented on mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java
> +                .collect(java.util.stream.Collectors.toMap(RequestMethod::name, e -> e));
엥ㅋㅋㅋㅋ 분명 import 했던 것 같은데 왜 풀려있는지 모르겠네요😅 수정했습니다~

2024-09-20 14:12 UTC, hw0603 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java
> +public record HandlerKey(String url, RequestMethod requestMethod) {
개인적으로 간단한 VO들은 레코드를 즐겨 쓰는데요, 이미 레코드라는 좋은 기능이 있는데 굳이 `equals()` `hashCode()`, 심지어는 `toString()`까지 직접 오버라이드를 해 주면서까지 일반 클래스 구현을 유지할 이유가 없다고 생각했어요!

2024-09-20 14:16 UTC, hw0603 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    @Serial
`HttpServlet`이 `Serializable` 인터페이스를 구현하고 있으므로, 하위 클래스들은 잠재적으로 직렬화 가능한 구현을 가져야 하는데요, 사실 현재는 `ManualHandlerMapping`이 직렬화 가능하지 않기 때문에 정확한 구현이 아니긴 해요.

해당 필드를 `transient` 키워드를 통해 직렬화 불능으로 명시해 주거나, `ManualHandlerMapping`도 직렬화 가능하도록 해 주어야 하는데 이번 미션의 범위가 아닌 것 같아 일단 그대로 두었습니다ㅎㅎ;

2024-09-20 14:22 UTC, hw0603 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private boolean explicitHttpMethodNotExist(RequestMethod[] requestMethods) {
`hasNo~` prefix 너무 좋습니다👍 메서드명 짓다가 저게 생각이 안 나서 지금처럼 두었었는데 잘 짚어주셨네요😀

2024-09-20 14:40 UTC, hw0603 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
확실히 `AnnotationHandlerMapping`의 주된 책임은 적절한 핸들러를 찾아서 반환하는 것임에 비해 구현 코드는 초기 데이터를 구축하는 로직이 대부분이긴 하네요🥲 `Map` 구축 과정 전체를 다른 객체에서 담당하도록 분리하면 깔끔할 것 같은데 좀 더 구조가 확실해지면 리팩토링 해보도록 하겠습니다!

2024-09-21 07:42 UTC, jminkkk approved these changes
안녕하세요 페드로
레벨1 첫 미션에서 페어를 같이 했을 때 자바를 거의 처음 사용한 걸로 알고 있어요. 하지만 당시 제 예상대로 자바 고수가 되어 돌아오셨네요 ㅋㅋㅋㅋ
미션과 학습 테스트 모두 꼼꼼하게 진행해주셔서 많이 배웠습니다 ⚡️

1단계 수고하셨습니다 👍
남은 단계도 달려봅시다 🔥

2024-09-21 07:42 UTC, jminkkk commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    @Serial
그렇군요 !

> HttpServlet이 Serializable 인터페이스를 구현하고 있으므로, 하위 클래스들은 잠재적으로 직렬화 가능한 구현을 가져야 하는데요, 

페드로 답변을 보고 급 궁금증들이 생각나 좀 찾았는데 심심하실 때 보시면 좋을 것 같아 공유드립니다 😁

---

HttpServlet이 Serializable를 왜 구현하고 있고, DispatcherServlet의 실제 구현은 왜 해당 필드가 명시적으로 선언되어 있지 않는가

#### 궁금했던 이유

서블릿은 서버가 시작될 때 새로 한번 생성되고 대부분의 서블릿 컨테이너는 서블릿 인스턴스를 서버 메모리에 계속 유지합니다.
왜 HttpServlet이 Serializable를 왜 구현하고 있을까요?

-> 초기 J2EE 스펙에서는 서블릿의 직렬화를 지원했고, HttpServlet에서 직렬화를 구현하고 있는 것은 EJB 때의 레거시라고 하네요. 실제로 대부분의 서블릿 컨테이너에서 서블릿을 직렬화를 하는 경우는 실제로 거의 없고, 톰캣 역시 마찬가지라고 해요

스프링의 DispatcherServlet도 그 관점에서 serialVersionUID를 따로 선언하고 있지 않는 것 같는 것 같기도 합니다 (추측 100%)

[Why does HttpServlet implement Serializable?](https://stackoverflow.com/questions/179743/why-does-httpservlet-implement-serializable)

2024-09-21 07:42 UTC, merged