[MVC 구현하기 - 2단계] 명오(김형호) 미션 제출합니다.
woowacourse/java-mvc pull request #699
Opened 2024-09-21 08:53 UTC by HyungHoKim00

안녕하세요 아톰~ 2단계로 돌아왔습니다.
최대한 기존 코드에 변경을 만들지 않으려 했는데, 쉽지 않네요.
보시기에 어색한 부분이나 궁금한 부분이 있다면 리뷰 남겨주세요~

2024-09-22 04:33 UTC, le2sky requested changes
명오 안녕하세요 아톰입니다. 2단계도 잘 구현해주셨네요. 👍👍
피드백 남겨놨습니다. 남은 주말 잘 보내시길 바랍니다.
(JspView 상수 개행 확인해주세요)

2024-09-22 04:33 UTC, le2sky commented on app/src/main/java/com/techcourse/ControllerExecution.java
> +        String executed = controller.execute(request, response);
viewName은 어떨까요?

2024-09-22 04:33 UTC, le2sky commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    public static final String CONTROLLER_PACKAGE = "com.techcourse.controller";
public이어야하는 이유가 있나요? 👀

2024-09-22 04:33 UTC, le2sky commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>      private static final long serialVersionUID = 1L;
serialVersionUID 상수는 어디서 사용되는건가요?

2024-09-22 04:33 UTC, le2sky commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerMappings.initialize();
initialize 처리는 mappings 내부에서 처리하는건 어떨까요?

2024-09-22 04:33 UTC, le2sky commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        );
manual handler mapping은 사용자 커스텀 매핑으로 보이는데 dispatcher servlet에서 알고 있는게 맞나요? 명오의 의견이 궁금해요. 👀

2024-09-22 04:33 UTC, le2sky commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.renderView(request, response);
상위 협력이 보이면 좋았겠다고 생각했어요. modelAndView에서 view.render를 호출하면 어떤 이점이 있나요?

2024-09-22 04:33 UTC, le2sky commented on app/src/main/java/com/techcourse/ManualHandlerMapping.java
> +        return new ControllerExecution(controller);
이건 adapter인가요? 어떤 역할을 수행하는데 계속 생성되는건가요?

2024-09-22 04:33 UTC, le2sky commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +public class AnnotationHandlerMapping implements HandlerMapping {
이제 다른 매핑에 중복 매핑 정보가 있으면 예외로 쳐야하는 게 아닌지 궁금해요!

2024-09-22 04:33 UTC, le2sky commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappings.java
> +    }
handler mapping의 순서는 상관없나요?

2024-09-22 04:33 UTC, le2sky commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/Execution.java
> +public interface Execution {
실제 스프링 MVC 구조에서 어떤 역할을 수행하는건가요?

2024-09-22 08:04 UTC, HyungHoKim00 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    public static final String CONTROLLER_PACKAGE = "com.techcourse.controller";
수정했습니다!

2024-09-22 08:18 UTC, HyungHoKim00 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>      private static final long serialVersionUID = 1L;
DispatcherServlet 클래스는 간접적으로 Serializable 인터페이스를 구현하고 있습니다. Serializable 인터페이스를 구현한 객체는 직렬화, 역직렬화가 가능합니다.
클래스가 변하면 직렬화된 객체를 역직렬화할 때 에러가 발생하는데, 이를 방지하기 위해 버전 관리를 해줍니다. serialVersionUID는 버전 번호를 의미합니다.

2024-09-22 08:26 UTC, HyungHoKim00 commented on app/src/main/java/com/techcourse/ManualHandlerMapping.java
> +        return new ControllerExecution(controller);
일종의 adapter 역할을 하고 있는데, 객체를 계속 생성하는 것이 어색하네요. 이 부분은 mvc 패턴의 adapter처럼 수정해보았습니다.

2024-09-22 08:45 UTC, HyungHoKim00 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappings.java
> +    }
요청을 처리할 핸들러가 하나라면 상관없다고 생각합니다!

2024-09-22 09:12 UTC, HyungHoKim00 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +public class AnnotationHandlerMapping implements HandlerMapping {
예외로 쳐야 한다고 생각합니다! 하지만 initialize 과정에서 검사하기에는 어려움을 겪었습니다. 대안으로 요청이 발생했을 때 예외가 발생하도록 수정했습니다. 안정성은 initialize 과정에서 검사하는 것 보단 떨어지지만, 있는 것이 좋다고 생각했습니다.

2024-09-22 09:18 UTC, HyungHoKim00 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/Execution.java
> +public interface Execution {
spring mvc 구조에서의 역할은 없습니다. 굳이 따지자면 adapter 쪽인데, 약간 다른 역할을 가지고 있죠.
이런 방식으로 구현한 이유는 'Adapter라는 클래스를 꼭 만들어야 하나?' 라는 의문이 있기 때문입니다. 저와 같은 방법을 가져가면, 굳이 handlerExecution을 adapt하는 클래스를 별도로 만들 필요가 없죠.
하지만 지금의 방식에는 치명적인 단점이 있었습니다. 바로 'ModelAndView를 반환하지 않는 새로운 handler 구조가 생기는 경우'를 고려하지 않았습니다. 이 경우, Execution같은 인터페이스를 또 다시 만들어야겠네요.
결론적으로, Adapter의 구조를 변경하였습니다.

2024-09-22 10:24 UTC, HyungHoKim00 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.renderView(request, response);
상위 협력이 무슨 뜻인지 잘 모르겠습니다. 설명해주실 수 있나요?
modelAndView에서 view.render를 호출하면 render를 하기 위해 handle에서 반환된 modelAndView에서 view와 model을 꺼내오는 로직을 수행할 필요가 없다는 장점이 있습니다.

2024-09-22 10:25 UTC, HyungHoKim00 commented on app/src/main/java/com/techcourse/ControllerExecution.java
> +        String executed = controller.execute(request, response);
뭐에 대해 말씀하신건지 설명해 주실 수 있나요?

2024-09-22 10:27 UTC, HyungHoKim00 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerMappings.initialize();
그게 더 좋아보이네요!

2024-09-22 10:45 UTC, HyungHoKim00 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        );
reflection을 활용하도록 변경했습니다!

2024-09-22 10:47 UTC, HyungHoKim00 reviewed
안녕하세요 아톰! 리뷰 반영했습니다. Execution 인터페이스가 사라지고 Adapter가 추가되었습니다. 아톰 코멘트에 대해 궁금한 점도 남겨두었으니 확인해주시면 감사하겠습니다.

2024-09-23 07:17 UTC, le2sky commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/Execution.java
> +public interface Execution {
👍👍 좋은 추론해주셨네요.

2024-09-23 08:38 UTC, le2sky commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +public class AnnotationHandlerMapping implements HandlerMapping {
사용자 입장에서 중복을 허용하고 매핑의 순서를 결정하는게 나은 선택일지 명오의 선택이 나은 선택일지 궁금하네요. 👀
각각 어떤 장단점이 있는 걸까요? 스프링 MVC는 이런 경우 어떤 선택을 하는건지도 궁금해요. 😀

2024-09-23 08:55 UTC, le2sky requested changes
명오 안녕하세요 아톰입니다. 거의 다 온 것 같네요. 
피드백 한 가지와 명오의 의견이 궁금한 부분이 있어서 RC 드립니다.
시간 나실 때, 확인 부탁 드립니다. 😀

2024-09-23 08:55 UTC, le2sky commented on app/src/main/java/com/techcourse/ManualHandlerAdapter.java
> +public class ManualHandlerAdapter implements HandlerAdapter<Controller> {
ControllerHandlerAdapter는 어떨까요?

2024-09-23 08:55 UTC, le2sky commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.renderView(request, response);
제가 말한 상위 협력이란 스프링 MVC에서 제어권을 가진 부분에서 일어나는 협력입니다. (일반적으로 동작원리를 검색했을 때 나오는 그림처럼요) 명확한 용어를 사용하지 않은 점 죄송합니다. 🥲 
프레임워크의 큰 그림이 service 메서드 내부에서 드러났으면 좋겠다고 생각했어요.
그리고 굳이 ModelAndView에서 HttpServletRequest, Response를 의존하지 않아도 되지 않을까?라고 생각했습니다.

2024-09-23 08:57 UTC, le2sky commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.renderView(request, response);
제가 말한 상위 협력이란 스프링 MVC에서 제어권을 가진 부분에서 일어나는 협력입니다. (일반적으로 동작원리를 검색했을 때 나오는 그림처럼요) 명확한 용어를 사용하지 않은 점 죄송합니다. 🥲
프레임워크의 큰 그림이 service 메서드 내부에서 드러났으면 좋겠다고 생각했어요.
그리고 굳이 ModelAndView에서 HttpServletRequest, Response를 의존하지 않아도 되지 않을까?라고 생각했습니다.

2024-09-23 10:56 UTC, HyungHoKim00 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +public class AnnotationHandlerMapping implements HandlerMapping {
매핑의 순서를 결정한다면 매핑 순서의 기준이 어떻게 될지도 중요할 것 같아요. 이 순서는 User가 커스텀할 수 없기에, 순서에 의존하지 않는 것이 안전하다고 생각했어요. 의도하지 않은 동작이 발생할 수 있다고 생각했어요.
하지만 MVC에서 기본 HandlerMapping이 제공된다면 이야기가 다를 것 같아요. 기본 HandlerMapping과 커스텀 HandlerMapping이 충돌이 일어나서는 안되겠죠. 사용자 커스텀이 더 우선순위가 되어야 할 것 같네요.
실제 MVC 구조에서도 순서에 의존하고 있는 것으로 확인했습니다.
```java
        private List<HandlerMapping> handlerMappings;

	protected HandlerExecutionChain getHandler(HttpServletRequest request) throws Exception {
		if (this.handlerMappings != null) {
			for (HandlerMapping mapping : this.handlerMappings) {
				HandlerExecutionChain handler = mapping.getHandler(request);
				if (handler != null) {
					return handler;
				}
			}
		}
		return null;
	}
```

2024-09-23 11:19 UTC, HyungHoKim00 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.renderView(request, response);
ModelAndView 클래스가 view 필드를 가지고 있는데 model의 일급 컬렉션처럼 동작하는 걸 좀 경계했던 것 같아요. 현재는 View가 JSPView로 고정되어 있어 이와 같은 구조가 가능했지만, 결국 나중에는 바꿔야 할 것 같다는 생각이 드네요. 실제 ModelAndView 클래스는 view 필드를 Object 타입으로 가지면서 viewName으로도 생성이 가능하더라구요.
상위 협력이 조금 더 드러나게 변경했습니다. viewResolver는 아직 필요하지 않다고 생각하여 만들지 않았어요.

2024-09-23 11:22 UTC, HyungHoKim00 reviewed
안녕하세요 아톰~ 양질의 리뷰 감사합니다.
이번 미션을 진행하면서 제가 MVC 구조에 대해 모르는 게 많다는 것을 깨달았어요.
레벨2에 배우면서 일단 적용해야 하니 넘어간 부분들이 덕분에 조금씩 보이네요.
덕분에 소스 코드도 보게 되어 미션이 더 재밌어졌습니다. 스프링 개발자들과 저의 차이도 느끼고, 방식의 선택 기준에 대해 더 생각해봤던 것 같아요.
이번에도 잘 부탁드립니다!!

2024-09-24 02:15 UTC, le2sky commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.renderView(request, response);
👍👍 명오 덕분에 저도 성장하고 있네요.

2024-09-24 02:18 UTC, le2sky approved these changes
명오 안녕하세요. 아톰입니다.
스프링 MVC에 대해서 열심히 학습해주셨네요. 👍👍
2단계에서 더 이상 드릴 피드백이 없어서 이만 approve하겠습니다.
고생 많으셨고, 다음 단계에서 뵙겠습니다.

2024-09-24 02:18 UTC, merged