[MVC 구현하기 - 1단계] 호기(조호연) 미션 제출합니다.
woowacourse/java-mvc pull request #707
Opened 2024-09-22 06:53 UTC by hoyeonyy

안녕하세요 폭포! 호기입니다!

분명 저번 미션에선 반대였던 것 같은데,, 이렇게 되었네요..?!
잘부탁드립니다!

2024-09-22 08:10 UTC, BurningFalls requested changes
안녕하세요 호기! 이번엔 리뷰어가 된 폭포입니다 ㅎㅎ. 😄 

전체적으로 구현 잘해주셨습니다! 리뷰 몇 가지 작성했는데 확인부탁드릴게요.
리뷰 유형을 쉽게 구분하실 수 있게 앞에 태그를 달아두었습니다. 각 태그는 다음을 의미합니다.

| 태그   | 의미                                                                                           |
|--------|------------------------------------------------------------------------------------------------|
| 학습   | 리뷰어가 리뷰이의 코드를 보고 새롭게 배운 부분입니다.                                            |
| 공유   | 리뷰어가 구현한 다른 방식을 공유합니다. 참고용이므로, 반영하실 필요는 없습니다.                |
| 질문   | 해당 구현 방식에 대한 이유나 의도를 궁금해하는 질문입니다.                                      |
| 제안   | 리뷰어가 개선할 수 있는 부분을 제안합니다. 선택적으로 반영하시면 됩니다.         |

+ `JspView`, `AnnotationHandlerMapping`, `HandlerExecution` 코드를 작성하셨지만, 이 코드들이 실제로 동작을 잘 수행할지 보장할 수단이 없는 것 같아요! 따라서, 이 클래스들에 대한 테스트 코드가 필요해보입니다. 이미 있는 `AnnotationHandlerMappingTest` 코드를 참고해서 각 클래스들의 테스트 코드를 구현해 볼까요? 파이팅입니다!! 👍

2024-09-22 08:10 UTC, BurningFalls commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +	}
**[제안]** 과도한 분리라고 생각해서 아래와 같이 리팩토링할 수 있을 것 같은데, 어떻게 생각하시나요?

```java
private void processRequestMapping(Method method, Object instance) {
    RequestMapping requestMapping = method.getAnnotation(RequestMapping.class);
    String uriPattern = requestMapping.value();
    RequestMethod[] requestMethods = requestMapping.method();

    if (requestMethods.length == 0) {
        requestMethods = RequestMethod.values();
    }

    for (RequestMethod requestMethod : requestMethods) {
        registerHandler(uriPattern, requestMethod, instance, method);
    }
}

private void registerHandler(String uriPattern, RequestMethod requestMethod,
                             Object instance, Method method) {
    HandlerKey handlerKey = new HandlerKey(uriPattern, requestMethod);
    handlerExecutions.put(handlerKey, new HandlerExecution(instance, method));
}
```

2024-09-24 01:02 UTC, hoyeonyy commented on study/src/test/java/reflection/Junit3TestRunner.java
> +        // Junit3Test의 인스턴스를 생성합니다.
주석 전부 죽이러 갑니다.

2024-09-24 12:49 UTC, hoyeonyy commented on study/src/test/java/reflection/Junit3TestRunner.java
> +                method.invoke(instance);
되게 좋은 방법인 것 같아요!

폭포 덕분에 좋은 인사이트 얻어갑니다!

2024-09-24 12:51 UTC, hoyeonyy commented on study/src/test/java/reflection/ReflectionTest.java
> +		assertThat(secondQuestion.getContents()).isEqualTo("내용2");
저도 뭐가 잘못됐지..? 찾는데 오래걸렸는데,, 폭포의 눈썰미란,,,👍

2024-09-24 12:52 UTC, hoyeonyy commented on study/src/test/java/reflection/ReflectionTest.java
> +		final Constructor<?>[] constructors = questionClass.getConstructors();
getDeclaredConstructors 는 찾아보니 private 도 뜯어볼 수 있더라구요! 감사합니다!

2024-09-24 12:54 UTC, hoyeonyy commented on study/src/test/java/reflection/ReflectionTest.java
> +		final Field[] fields = student.getClass().getDeclaredFields();
getFields():
해당 클래스의 public 필드만 반환합니다!
상속된 필드도 포함합니다!

getDeclaredFields():
해당 클래스에 직접 선언된 모든 필드를 반환합니다(private, protected, default, public)
상속된 필드는 포함하지 않습니다!

마찬가지로 method도 같은 내용이더라구요!

폭포 최고!

2024-09-24 12:55 UTC, hoyeonyy commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java
> +	public void render(final Map<String, ?> model, final HttpServletRequest request,
폭포가 말씀하신대로 중복 코드를 제거하고 jspView 의 코드를 사용해서 리팩토링 했습니다!

2024-09-24 12:57 UTC, hoyeonyy commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +	}
저도 메서드 분리를 하면서
아 쫌 과한가,,라는 생각이 들었는데 폭포도 같은 생각인 것 같아 확신을 가지고 리팩토링 했습니다!

2024-09-24 15:08 UTC, BurningFalls approved these changes
수고하셨습니다, 호기! 남겨주신 코멘트를 보니, 제가 많은 도움이 될 수 있었던 것 같아서 기분이 좋네요. 😄 

나중에 `AnnotationHandlerMappingTest`에 *RequestMapping에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원한다*를 보장하는 테스트 코드를 추가하시면 좋을 것 같아요! 테스트가 있으면 2~3단계에서 리팩토링을 하는 도중에 해당 기능이 실제로 잘 동작하는지를 확인할 수 있어서 꽤 도움이 될 거라고 생각합니다.

2단계도 파이팅입니다!!

2024-09-24 15:08 UTC, BurningFalls commented on study/src/test/java/reflection/ReflectionTest.java
> +		final Question secondQuestion = (Question)secondConstructor.newInstance("gugu", "제목2", "내용2");
**[제안]** 
`Question` 클래스에는 다음과 같이 두 개의 생성자가 있습니다.
```java
public Question(String writer, String title, String contents) {
    this(0, writer, title, contents, new Date(), 0);
}

public Question(long questionId, String writer, String title, String contents, Date createdDate,
                int countOfComment) {
    this.questionId = questionId;
    this.writer = writer;
    this.title = title;
    this.contents = contents;
    this.createdDate = createdDate;
    this.countOfComment = countOfComment;
}
```

아마 이 테스트의 의도는 `firstConstructor`는 위의 생성자, `secondConstructor`는 밑의 생성자를 불러와서 사용해보는 것 같아요. 그래서 테스트 의도와 일치하는 코드는 아래와 같다고 생각합니다.

```java
final Constructor<?> firstConstructor = questionClass.getConstructor(String.class, String.class, String.class);
final Constructor<?> secondConstructor = questionClass.getConstructor(long.class, String.class, String.class, String.class, Date.class, int.class);

final Question firstQuestion = (Question) firstConstructor.newInstance("gugu", "제목1", "내용1");
final Question secondQuestion = (Question) secondConstructor.newInstance(1L, "gugu", "제목2", "내용2", new Date(), 0);
```

2024-09-24 15:08 UTC, merged