[MVC 구현하기 - 1단계] 폴라(장유진) 미션 제출합니다.
woowacourse/java-mvc pull request #724
Opened 2024-09-23 08:16 UTC by jinchiim

안녕하세요 러쉬! ☺️
휴 저번주부터 좀 프로젝트 부터 공부까지 좀 정신 없는 하루를 보내서 `MVC` 는 `HTTP` 만큼 
많은 시간을 투자해 공부하며 진행하지 못해 아쉽습니다 🥹

**그래도 일단 기간은 기간이니 학습테스트부터 미션 코드까지 열심히 작성해보았습니다!**

아마 `KeyMaker` 라는 클래스에 대해 의문이 있을 수 있을 것 같은데 **만약 `@RequestMapping`이 아닌 매핑을 해주는 다른 어노테이션이
생긴다면 코드가 많이 길고 복잡해지겠다는 생각에 미리 실험삼아 만들어본 객체입니다!**

(만약 `PostMapping` 이 추가되더라도 `AnnotationHandlerMapping` 이 바뀔일도 없고 해당하는 어노테이션을 담당하는 객체는
스스로 본인이 어떤 `RequestMethod`를 넣어줄지 알게 될 것 같다는 생각이 들었어요 근데 좀 야그니 일수도? 싶고 이름도 뭔가 마땅한 이름이 떠오르지 않아 일단 `Maker`라고 했습니다 ㅋㅋㅋ 🤣)

아무튼 러쉬 리뷰 잘 부탁드려요! 😋

2024-09-23 13:28 UTC, xogns1514 requested changes
안녕하세요 폴라! 러쉬입니다~~
요구사항에 맞게 잘 구현해주셨네요ㅎㅎ 
확장성을 고려해서 KeyMaker인터페이스를 활용하신점이 흥미로웠습니다👍🏻

안타깝게도 작동하지 않는 test가 있는 것 같아요 😢
<img width="276" alt="image" src="https://github.com/user-attachments/assets/3b2582fc-f360-4e43-9345-d4b52c54af3b">

해당 부분 확인해주시면 감사하겠습니다ㅎㅎ

몇가지 코멘트와 제안 남겨두었어요~ 궁금한점 있다면 DM 말고 직접 자리에 찾아와주시길 바랍니다 😉

2024-09-23 13:28 UTC, xogns1514 commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/keyMaker/RequestMappingKeyMakerTest.java
> +                        .isEqualTo(RequestMethod.values().length)
```suggestion
                () -> assertThat(requestMappingKeyMaker.makeKeys(method))
                        .hasSize(RequestMethod.values().length)
```
hasSize() 메서드도 있으니 참고바랍니다ㅎㅎ

2024-09-23 13:28 UTC, xogns1514 commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerRegistryTest.java
> +        assertThat(controller.hashCode()).isEqualTo(afterSaveController.hashCode());
```suggestion
        assertThat(controller).hasSameHashCodeAs(afterSaveController);

```
또한 위와 같은 메서드도 지원하니 참고바랍니다ㅎㅎ

2024-09-23 13:28 UTC, xogns1514 commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerRegistryTest.java
> +    void getOrCreateController() throws Exception {
불필요한 예외처리 지워도 괜찮아보입니다ㅎㅎ

2024-09-23 13:42 UTC, jinchiim commented on study/src/test/java/reflection/Junit3TestRunner.java
> +        Method[] methods = clazz.getMethods();
`gerDeclaredMethods`도 있는 것으로 알고 있습니다!

![image](https://github.com/user-attachments/assets/8209f7d0-65bf-43cc-8b40-1ce2c5b62038)
설명된 바와 같이 `getMethods` 는 모든 `public method` 와 상속되어진 `superClass` 같은 것들도 가져오는 것과 다르게
이름과 똑같이 선언된 `method` 를 접근제어자 상관없이 전부 가져옵니다!

2024-09-23 13:43 UTC, jinchiim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerRegistry.java
> +
오 잊었네요 감사합니다!

2024-09-23 13:44 UTC, jinchiim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/keyMaker/KeyMaker.java
> +package com.interface21.webmvc.servlet.mvc.tobe.keyMaker;
ㅋㅋㅋㅋㅋㅋ 정신 없었나 보네요 감사합니다

2024-09-23 13:46 UTC, jinchiim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/keyMaker/KeyMaker.java
> +public interface KeyMaker {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 이게 기본 인터페이스가 길어지면 다른 클래스들도 이름이 너무 길어져서 좀 꺼려지더라고요
그래도 `Handler` 라는 명칭이 들어가는게 낫겠죠? 🤔

2024-09-23 14:16 UTC, jinchiim commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerRegistryTest.java
> +        assertThat(controller.hashCode()).isEqualTo(afterSaveController.hashCode());
오 몰랐네요 꿀팁 좋습니다 👍🏻

2024-09-23 14:18 UTC, jinchiim commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/keyMaker/RequestMappingKeyMakerTest.java
> +                        .isEqualTo(RequestMethod.values().length)
오 너무 좋네요!

2024-09-23 14:19 UTC, jinchiim commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerRegistryTest.java
> +    void getOrCreateController() throws Exception {
매의 눈이네요 좋습니다!

2024-09-23 14:27 UTC, jinchiim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
>      public ModelAndView handle(final HttpServletRequest request, final HttpServletResponse response) throws Exception {
🥹 눈치를 못채고 있었네요... 감사합니다! 구체적인 예외를 던지도록 수정했습니다!

2024-09-23 14:34 UTC, jinchiim commented
안녕하세요 러쉬! 
제가 몰랐던 부분들을 많이 말씀해주셔서 많이 배웠습니다! ☺️
훨씬 가독성이 좋아지네요!

클래스 이름도 길어서 걱정이었는데 길더라도 직관적인게 좋은 것 같네요 😅
재 리뷰 요청 보냅니다!

12시 타이머 시작합니다.

2024-09-23 14:41 UTC, jinchiim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/keyMaker/KeyMaker.java
> +public interface KeyMaker {
막상 변경해보니 차라리 직관적인게 좋더라구요.  😅
역시 해보는게 짱이네요 감사합니다! 덕분에 가독성 좋아졌네요 👍🏻

2024-09-25 04:18 UTC, xogns1514 approved these changes
수고하셨습니다 폴라~~! 리뷰 잘 반영해주셨네요. 이번 단계는 요구사항을 다 충족하신거 같으니 `merge` 드립니다. 다음 단계에서 다시 봅시당~

2024-09-25 04:18 UTC, xogns1514 commented on study/src/test/java/reflection/Junit3TestRunner.java
> +        Method[] methods = clazz.getMethods();
잘 알고계신군요👍🏿

2024-09-25 04:18 UTC, xogns1514 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        log.info("initialized Handler ma");
오타겠죠?

2024-09-25 04:18 UTC, xogns1514 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +        }
👍🏻

2024-09-25 04:18 UTC, xogns1514 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/keygenerator/HandlerKeyGenerator.java
> +public interface HandlerKeyGenerator {
음 어떤 인터페이스인지 잘 알겠군요

2024-09-25 04:18 UTC, merged

2024-09-25 04:20 UTC, jinchiim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        log.info("initialized Handler ma");
핸들러 마! init 되어라!