[MVC 구현하기 - 2단계] 프린(남기범) 미션 제출합니다.
woowacourse/java-mvc pull request #730
Opened 2024-09-24 12:03 UTC by GIVEN53

안녕하세요 짱짱수 :) 2단계도 잘 부탁드립니다

#### notice
https://github.com/woowacourse/java-mvc/pull/690#discussion_r1769601554 1단계 리뷰를 반영하기 위해 애플리케이션 로드 타임때 모든 bean 등록을 구현하려고 했으나 배보다 배꼽이 더 커지는 상황이 오더라구요
요구사항에만 집중하자는 생각으로 `BeanFactory`는 삭제했습니다

2024-09-25 08:05 UTC, zangsu requested changes
프린은 예외 처리가 정말 꼼꼼해서 코드를 볼 때 마다 '본받아야겠다.' 라는 생각이 들어요.
코드도 깔끔하게 잘 읽혀서 쉽게 리뷰할 수 있었습니다 ^^

코멘트 반영하면서 `DispatcherServlet` 의 구조가 어느 정도 바뀔 것 같아요.
그 때 조금 더 이야기를 나누어 보는 걸로 하죠!

2024-09-25 08:05 UTC, zangsu commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>  import com.interface21.webmvc.servlet.view.JspView;
👀

2024-09-29 05:03 UTC, GIVEN53 reviewed
안녕하세요 짱수!
데모데이 준비하느라 바빠서 코멘트가 많이 늦었네요 😂

리뷰 반영한 부분 및 코멘트 확인부탁드려요!

2024-09-29 12:48 UTC, zangsu requested changes
데모데이 끝나고 열심히 반영해 주셨네요!
고생하셨습니다~~~

회원가입 페이지 조회 부분만 다시 확인해 주세요!

2024-09-29 12:48 UTC, zangsu commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private Object getHandler(HttpServletRequest request) {
저도 이 부분을 `null` 을 리턴할지, `Optional` 을 리턴할지, 예외를 던질지 고민이 되어서 질문 드렸어요!
어떤 선택이던 적절한 근거가 있다면 좋아 보입니다!
프린의 설명에도 동의해요!

2024-09-29 12:48 UTC, zangsu commented on app/src/main/java/com/techcourse/ManualHandlerMapping.java
> +public class ManualHandlerMapping implements HandlerMapping {
오, 그렇군요.
단순히 "기존의 코드를 변경하지 않고 새로운 타입의 `HandlerMapping` 을 도입하여라." 라는 요구사항으로 이해해서 리뷰를 남겼던 것인데요.
(저는 이 때문에 `HandlerMapping` 을 `HandlerMappingAdapter` 로 감싸게 되었어요)
`ManualHandlerMapping` 코드를 변경한다면 저도 프린과 동일하게 인터페이스로 추상화 하는 선택을 했을 것 같아요.

해당 리뷰는 무시하셔도 될 것 같습니다!

2024-09-29 12:48 UTC, zangsu commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +    @RequestMapping(value = "/register", method = RequestMethod.GET)
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/9f849608-d2b2-48a2-97f4-7b501a1933cd">

이렇게 보이고, 로그인 페이지에 연결되어 있는 링크로 이동한 상태입니다!

2024-09-29 12:48 UTC, zangsu commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            Object handler = handlerType.getDeclaredConstructor().newInstance();
사실 저는 단순하게 `Map<Class, Object>` 형식의 필드를 가지는 것을 생각했긴 했습니다...ㅎㅎ
해당 책임을 `Scanner` 로 분리하여도 보기 좋군요! 👍

2024-09-29 16:27 UTC, GIVEN53 commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +    @RequestMapping(value = "/register", method = RequestMethod.GET)
로그인 페이지에서 버튼에 매핑된 엔드포인트를 수정하지 않았군요 😅
짱수덕분에 해결했습니다 👍🏻 https://github.com/woowacourse/java-mvc/pull/730/commits/2ac89bab454e2c207bb8b795e0c68561279958b9

2024-09-30 04:38 UTC, zangsu commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +    @RequestMapping(value = "/register", method = RequestMethod.GET)
동작 확인 했습니다!

2024-09-30 04:39 UTC, zangsu approved these changes
2단계도 고생 많으셨습니다~
3단계도 빠르게 달려보시죠 🔥

2024-09-30 04:39 UTC, merged