[MVC 구현하기 - 2단계] 제우스(신재우) 미션 제출합니다.
woowacourse/java-mvc pull request #744
Opened 2024-09-25 11:03 UTC by zeus6768

안녕하세요 백호! 👋

타입 기반의 컨트롤러와 애너테이션 기반의 컨트롤러를 모두 지원하게 구현하는게 쉽지 않았습니다. 😭

어려운 점이 있었는데, `ManualHandlerMapping`과 `AnnotationHandlerMapping`의 `getHandler()` 메서드의 반환타입이 `Controller`와 `HandlerExecution`으로 서로 다르다는 것이었습니다.

게다가 `Controller`의 `execute()` 메서드의 반환타입은 `String`이고 `HandlerExecution`의 반환타입은 `ModelAndView`로 또 달랐습니다.

이 부분을 해결하기 위해 스프링의 `DispatcherServlet`과 LMS의 힌트를 참고해 `HandlerAdapter` 인터페이스를 만들고 핸들러가 항상 `ModelAndView` 타입을 반환하도록 구현했습니다.

아쉬운 점이 있다면 `DispatcherServlet`이 `HandlerMappingRegistry`와 `HandlerAdapterRegistry` 객체를 직접 생성하는 등 객체를 사용하는 쪽에서 생성도 하고 있다는 것입니다. 

빈 컨테이너의 필요성이 느껴졌습니다. 🥲

다만 어떻게 컨테이너를 만들지는 잘 모르겠습니다. 어떤 경로에서 스캔할지, 어떤 클래스를 스캔할지 등 고려할 게 많다고 생각되네요. 

2단계도 잘 부탁드립니다!

2024-09-27 15:29 UTC, Arachneee requested changes
안녕하세요 제우스!

2단계 리뷰요청이 오지않아서 리뷰가 늦어졌네요.

Adaptor를 잘 활용하신 것 같아요. 👍 

> 아쉬운 점이 있다면 DispatcherServlet이 HandlerMappingRegistry와 HandlerAdapterRegistry 객체를 직접 생성하는 등 객체를 사용하는 쪽에서 생성도 하고 있다는 것입니다.
>빈 컨테이너의 필요성이 느껴졌습니다. 🥲
>다만 어떻게 컨테이너를 만들지는 잘 모르겠습니다. 어떤 경로에서 스캔할지, 어떤 클래스를 스캔할지 등 고려할 게 많다고 생각되네요.

우선 스캔 범위를 크게 2가지로 나누면 좋을 것 같아요.
1. app패키지 스캔
2. mvc패키지 스캔

그리고 스캔을 할 객체는 handleradaptor, handlermapping, controller가 될 것 같습니다.

그런데 각 객체들이 app과 mvc에 나눠서 분포해 있는 것이 문제죠.

그래서 어플리케이션이 처음 실행될 때 각 패키지마다 handleradaptor, handlermapping, controller 구현체 class를 전부 스캔해 온 후 컨테이너에 등록하여 싱글톤으로 관리할 수 있도록 하면 될 것 같아요.

이후에 Registry가 컨테이너에서 해당 빈을 꺼내올 수 있도록 하면 좋을 것 같아요.

그리고 테스트코드가 하나도 없는데 추가해주세요.

2024-09-27 15:29 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java
> +    }
ControllerScanner를 유틸리티 클래스로 만드는 것은 어떨까요?
Reflections를 상태로 가지면 어떤 장점이 있을까요?

그리고 class를 스캔하는 역할과 인스턴스를 생성하는 역할 2개가 부여된 것 같아요.
scan 을 반복 수행하면 인스턴스가 여러번 생성되는데 싱글톤을 유지하지 못할 수 있을 것 같아요.

2024-09-27 15:29 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +        this.method = method;
declaredObject를 따로 추가하신 이유가 있으신가요?

HandlerExectution이 Object와 Method를 인자로 따로 받는다면 Object와 Method가 매칭되지 않는 경우가 발생할 것 같아요.
인스턴스를 한번만 생성하기 위해 Object도 받으신 것 같은데 빈 컨테이너를 활용해보면 좋을 것 같아요.

2024-09-27 15:29 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java
> +    }
여기서 스캔한 인스턴스를 관리하는 빈 컨테이너가 있어도 좋을 것 같아요.

2024-09-27 15:29 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapter.java
> +}
인터페이스 활용 👍

2024-09-27 15:29 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java
> +}
인터페이스 활용 👍

2024-09-29 04:16 UTC, zeus6768 reviewed
안녕하세요 백호!

빈 컨테이너 관련해 조언 정말 큰 도움이 되었어요. 👍

MVC 관련 객체를 저장하는 컨테이너를 클래스를 만들어봤습니다. 

리플렉션과 제네릭 문법에 익숙하지 않아 꽤 시간이 걸렸어요 🫠

아쉬운 점이 있다면 어떤 타입의 클래스를 스캔할지 메서드에 구현이 되어 있는데, 이것까지 외부에서 주입하는 방식으로 변경할 수 있다면 더 좋을 것 같습니다. 

또 테스트코드도 추가했습니다! 😅

2024-09-29 04:16 UTC, zeus6768 commented on app/src/main/java/com/techcourse/HandlerAdapterRegistry.java
> +public class HandlerAdapterRegistry {
처음에는 HandlerAdapterRegistry와 HandlerMappingRegistry가 DispatcherServlet을 위한 구현이라고 생각했는데, 컨테이너를 만들고 보니 백호 말씀대로 mvc 패키지에 위치하는 게 더 적절해 보이네요. 

반영했습니다!

2024-09-29 04:16 UTC, zeus6768 commented on app/src/main/java/com/techcourse/HandlerAdapterRegistry.java
> +    }
반영했습니다!

2024-09-29 04:16 UTC, zeus6768 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java
> +    }
> Reflections를 상태로 가지면 어떤 장점이 있을까요?

Reflections은 굳이 상태로 가질 필요가 없었다고 생각합니다. 

백호의 리뷰를 보고 mvc 관련 객체를 관리하는 Container를 만들어봤습니다. 

그러면서 ControllerScanner는 자연스럽게 필요없어졌어요. 그래서 삭제했습니다!

2024-09-29 04:16 UTC, zeus6768 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +        this.method = method;
컨테이너를 만들며 해당 내용 적용했습니다~!

2024-09-29 08:31 UTC, Arachneee approved these changes
안녕하세요 제우스!

컨네이너를 빠르게 구현해 주셨네요 👍 

추가 코멘트 남겼는데 답변만 해주세요~

이만 머지하고 다음 단계를 진행해도 좋을 것 같아요.

2024-09-29 08:31 UTC, Arachneee commented on mvc/src/main/java/com/interface21/context/container/Container.java
> +        container.put(name, instance);
컨테이너에 이름 중복 검증이 있어도 좋을 것 같아요.

2024-09-29 08:31 UTC, Arachneee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +                .flatMap(handlerMapping -> Stream.ofNullable(handlerMapping.getHandler(request)))
로직이 잘 이해가 안되서 그런데 flatMap을 사용해야하는 이유가 있나요?
map으로는 안되나요?

2024-09-29 08:38 UTC, merged

2024-09-30 04:36 UTC, zeus6768 commented on mvc/src/main/java/com/interface21/context/container/Container.java
> +        container.put(name, instance);
정말 그렇네요! 다음 단계에 추가하겠습니다!

2024-09-30 04:40 UTC, zeus6768 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +                .flatMap(handlerMapping -> Stream.ofNullable(handlerMapping.getHandler(request)))
`getHandler` 메서드에서 null을 반환할 수 있기 때문에 optional과 flatMap을 사용해서 null을 없애고 있었습니다. 

해당 부분은 아래의 코드와 동일해요. 

```suggestion
                .map(handlerMapping -> handlerMapping.getHandler(request))
                .filter(Objects::nonNull)
```

제가 생각해도 flatMap을 사용하면 이해하기 어려운 것 같아요 ㅎㅎ... 

다음 단계에서는 map과 filter를 사용한 코드로 변경해볼게요~!