[MVC 구현하기 - 2단계] 폭포(이성주) 미션 제출합니다.
woowacourse/java-mvc pull request #751
Opened 2024-09-26 00:48 UTC by BurningFalls

안녕하세요, 켬미! java-mvc step2로 돌아왔습니다. 😄 

이번 미션은 어떻게 구현해야하는지 감을 잡기가 정말 쉽지 않았던 것 같아요. 설계하는데만 해도 시간이 꽤나 소요되었고, 켬미의 리뷰에 도움이 되고자 제가 어떤 근거를 가지고 이 구조를 선택하게 되었는지 공유드립니다. 

### 로직 근거

* Legacy MVC: `HandleMapping`에서 Controller 핸들러를 얻음 -> 핸들러를 실행(execute)해서 viewName을 얻음
* MVC: `HandlerMapping`에서 HandleExecution 핸들러를 얻음 -> 핸들러를 실행(handle)해서 viewName을 얻음 

* `HandlerMapping`에서 핸들러를 찾고 핸들러를 실행하는 흐름은 동일하지만 구현이 조금씩 달랐습니다. 따라서 핸들러를 찾아주는 `HandlerMapping`과 핸들러를 받아서 변환하고 실행하는 `HandleAdapter`를 인터페이스로 만들고 각각을 구현체로 만들었습니다.
* 두 개의 `HandlerMapping`(또는 `handlerAdapter`)를 관리하고, 하나를 어떤 기준으로 선택하는 로직이 필요했습니다. `DispatcherServlet`이 갖고 있으면 책임이 너무 무거워지고, 이를 관리해주는 클래스를 따로 분리하면 좋겠다고 생각하여 `HandlerMappingRegistry`와 `HandlerAdapterRegistry`를 만들었습니다. 

### 로직 구현 흐름

* `HandlerMapping` 인터페이스 및 Manual과 Annotation 구현체 생성
* `HandlerAdapter` 인터페이스 및 Manual과 Annotation 구현체 생성
* 이들을 관리하는 `HandlerMappingRegistry`, `HandlerAdapterRegistry` 저장소 생성
* `DispatcherServlet` 리팩토링

### 질문

* registry는 저장소의 역할이므로 handler를 실행하는 부분까지 분리하고 싶었으나, registry와 executor의 책임이 너무 가벼워지고 과도한 분리라고 생각해서 하지 않았습니다. 저는 위와 같이 `HandleMapping`, `HandlerAdapter`, `HandlerRegistry`로 구현했는데, 켬미는 이번 미션의 전체적인 구현 구조를 어떤 식으로 구성하셨는지 궁금합니다!
* 테스트를 위해 `ManualHandlerMapping` 클래스가 필요했으나 모듈이 달라 참조하지 못하는 현상이 발생했습니다. 따라서 인터페이스를 상속받으며 비슷한 기능을 수행하는 test용 클래스 `TestManualHandlerMapping`를 만들어 사용했습니다. 켬미는 전체적인 테스트르 어떤 방식으로 구현했는지도 궁금합니다!

2024-09-28 00:25 UTC, kyum-q requested changes
안녕하세요 폭포 ! 리뷰가 늦어서 죄송해요 🥲
폭포~ 구현을 너무 깔끔하게 해주셨네요 ! 최고 입니다 ~!

제가 생각하는 범위에서 궁금한 점과 코멘트 달아두었습니다. 제 생각을 열심히 말했는데 제가 잘 말한지 모르겠네요 ㅎㅎ 이해가 안되는 부분이 있으면 언제든지 DM 환영 입니다 ~

그리고 폭포가 질문한 내용에 답변은 관련된 코드에 코멘트로 남겼습니다 ~

추가적으로 학습테스트에 FilterTest, ServletTest 테스트도 구현해주면 좋을 것 같아요 ~ 

(플러스) AnnotationHandlerMapping이 잘되는지 확인하기 위해 로그인이나 회원가입 컨트롤러 중 하나를 AnnotationHandlerMapping을 사용하도록 컨트롤러를 변경해보면 더 좋을 것 같아요 ~!

2024-09-28 00:25 UTC, kyum-q commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +public class HandlerMappingRegistry {
tmi일수도 있으나 저는 어떻게 했냐면 ...
추가적으로 registry가 수동으로 필요한 정보를 받는 것이 아닌 자동으로 모든 값들을 필드에 넣으면 좋겠다고 판단했습니다.
그래서 HandlerMappingRegistry 은 생성시 basePakage를 받아서 해당 패키지에 있는 HandlerMapping을 상속한 클래스를 모두 필드에 추가해줬습니다.
HandlerAdapterRegistry 도 동일하게 했습니다.

2024-09-28 00:25 UTC, kyum-q commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +    }
> registry는 저장소의 역할이므로 handler를 실행하는 부분까지 분리하고 싶었으나, registry와 executor의 책임이 너무 가벼워지고 과도한 분리라고 생각해서 하지 않았습니다. 저는 위와 같이 HandleMapping, HandlerAdapter, HandlerRegistry로 구현했는데, 켬미는 이번 미션의 전체적인 구현 구조를 어떤 식으로 구성하셨는지 궁금합니다!

일단 해당 질문을 나눠볼게요 

---

>  registry는 저장소의 역할이므로 handler를 실행하는 부분까지 분리하고 싶었으나, registry와 executor의 책임이 너무 가벼워지고 과도한 분리라고 생각해서 하지 않았습니다

저도 동의합니다 ! 저도 해당 부분에서 handler를 실행하도록 하였습니다 ! registry를 저장소라고 볼 수 있지만, 저장소를 만든 이유를 생각하면 저장소에서 원하는 조건에 맞는 객체를 빠르게 찾기 위해서라고 생각합니다. 
그래서 굳이 분리하지 않아도 될 것 같아요 ~

---

> 켬미는 이번 미션의 전체적인 구현 구조를 어떤 식으로 구성하셨는지 궁금합니다!

저도 폭포와 동일하게 HandleMapping, HandlerAdapter, HandlerRegistry로 구현하였습니다. ! (HandlerRegistry 명칭이 container이긴 하지만 )
그래서 제 구조를 이야기해볼게요 (제 PR에 썼던 내용을 가져왔습니다)

어떻게하면 레거시 MVC와 @MVC 둘 다 작동할 수 있게 할 수 있을까 고민에 고민을 하였습니다.
그래서 두 가지 HandlerMapping은 HandlerMapping이라는 인터페이스를 생성해서 구현체로 하였습니다. 그리고 두 Mapping이 반환 값이 다르므로 이를 해결하기 위해 HandlerAdapter라는 인터페이스를 생성해서 두 개의 구현체를 만들었습니다.

이제 이를 어떻게 사용할까 고민하다 만든 것이 HandlerMappingContainer 와 HandlerAdapterContainer 입니다.

HandlerMappingContainer : HandlerMapping을 상속한 하위 클래스를 알아내 맞는 Mapping 클래스를 알아내도록 구현
HandlerAdapterContainer : HandlerAdapter을 상속한 하위 클래스를 알아내 맞는 Adapter 클래스를 알아내도록 구현

2024-09-28 00:25 UTC, kyum-q commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +    public Optional<Object> getHandler(final HttpServletRequest request) {
Optional 반환으로 하셨네요 ! 
바로 예외를 처리하지 않은 이유가 궁금해요 !

2024-09-28 00:25 UTC, kyum-q commented on mvc/src/test/java/samples/TestManualHandlerMapping.java
> +public class TestManualHandlerMapping implements HandlerMapping {
> 테스트를 위해 ManualHandlerMapping 클래스가 필요했으나 모듈이 달라 참조하지 못하는 현상이 발생했습니다. 따라서 인터페이스를 상속받으며 비슷한 기능을 수행하는 test용 클래스 TestManualHandlerMapping를 만들어 사용했습니다. 켬미는 전체적인 테스트르 어떤 방식으로 구현했는지도 궁금합니다!

저는 위에 말했다시피 registry에 수동으로 매핑 값을 넣은게 아니라 basepakage를 받아 해당 패키지에 있는 mapping이나 adapter를 모두 알아내도록 구현했습니다.
그래서 패키지를 현재 가장 큰 베이스 패키지인 com으로 설정해서 따로 sample 클래스를 제작할 필요가 없었습니다 !

그래서 폭포와 같이 참조하지 못하는 문제가 발생했을 때 어떻게 처리해야할지 모르겠네요..! ㅜㅜ

아니면 테스트 시에 필요한 mapping을 추가할 때, 저처럼 리플렉션을 이용해서 해당 어댑터를 찾아서 추가하는건 어떨까요?

2024-09-28 00:25 UTC, kyum-q commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistryTest.java
> +        registerHandlerAdapter(new AnnotationHandlerAdapter());
추가적으로 테스트에 AnnotationHandlerAdapter 테스트도 있으면 좋겠어요 !
간단하겠지만 해당 로직이 잘 작동해야지 HandlerAdapterRegistryTest 도 잘 작동하니 테스트 하는 로직이 있으면 더 굳! 할 것 같아요 ~

2024-09-28 16:20 UTC, BurningFalls commented on app/src/main/java/com/techcourse/ManualHandlerMapping.java
> +    private final Map<String, Object> handlers;
`HandlerMapping`은 요청에 따른 적절한 핸들러를 매핑해주는 클래스라고 생각했습니다. 이때, 요구사항에 맞춰 구현하면 `ManualHandlerMapping`과 `AnnotationHandlerMapping`으로 나눠지게 됩니다. 이는 각각 '수동으로 매핑하는 클래스'와 '어노테이션을 기반으로 자동으로 매핑하는 클래스'의 의미를 갖습니다. 즉, **매핑 방법**적인 측면에서 클래스가 나누어졌습니다. 

따라서 `ManualHandlerMapping`의 value에는 `Controller`만이 아닌 다른 어떤 것들도 전부 포함될 가능성이 있다고 판단해서 `Object`를 사용했습니다. 만약에 **요청 분류**를 기준으로 클래스를 나누어 이름이 `ControllerHandlerMapping`이 되었다면, `Controller`를 사용했을 것 같습니다.

원래 구현 의도는 위와 같았지만, 켬미의 코멘트를 읽고 새로운 관점을 얻었습니다.

* `supports` 메서드에서 instance type이 `Controller`인지 판단하는 작업은 올바르게 타입캐스팅이 되었는지 확인하는 의도이다. 따라서 `Adapter`는 `MaunualHandlerMapping`의 반환 값이 `Controller`일 것이라고 생각하고 있다.

이 부분은 미처 생각해보지 못했었고, 이 관점도 완전 동의합니다. 👍 공유해주셔서 감사합니다!

2024-09-28 16:52 UTC, BurningFalls commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
>                      .forEach(method -> handlerMapping(getControllerInstance(controllerClass), method));
https://github.com/woowacourse/java-mvc/pull/751/commits/23cf75cc65f7e055b5d45d159b88eef59c50e8f1 해당 커밋으로 전부 반영했습니다!

> getControllerInstance는 컨트롤러 클래스에만 종속되는 코드로 동일한 클래스의 메서드들은 인스턴스가 동일합니다 !
그럼 재사용을 위해 해당 getControllerInstance 메서드 호출 시기를 controllerClasses.forEach 단에서 하면 더 좋을 것 같아요 ~!

확실히 `getControllerInstance` 로직은 `RequestMapping`에만 적용되는 것이 아니라 컨트롤러 전체에 적용되므로, 메서드 반복문 바깥에 있는 것이 훨씬 어울리네요! 굉장히 지엽적이라 놓치기 쉬운 부분이었는데, 이걸 짚어주시다니 놀랍습니다. 그만큼 켬미가 제 코드리뷰를 열심히 해주신 것 같아서 감사해요 ㅎㅎ 😄 

> 추가적으로 controllerClasses.forEach(controllerClass -> { forEach의 중괄호가 들어간 순간 부터 전 이중 for문과 비슷하다고 생각 들어요 !
메서드를 분리하면 어떨까여?

메서드를 분리하면 너무 과도한 분리가 될 것 같아 하지 않고 있었는데, 애초에 제가 메서드 의도와 맞지 않는 네이밍을 해서 생긴 문제였었네요. 메서드를 분리하고 `handlerMapping`, `methodMapping`으로 메서드 네이밍을 개선해서, 과도한 분리라고 느껴지지 않도록 수정했습니다.

2024-09-28 17:17 UTC, BurningFalls commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapter.java
> +    String handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception;
**코드의 중복도**와 **에러 발생 위치**를 기준으로 그때그때 다르게 판단합니다.

---

예를 들면, 언급해주신 `handle` 메서드는 인터페이스화 되어있어서 두 곳에서 보여집니다.

```java
// ManualHandlerAdapter.java
@Override
public String handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
    return ((Controller) handler).execute(request, response);
}
```

``` java
// AnnotationHandlerAdapter.java
@Override
public String handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
    return ((HandlerExecution) handler).handle(request, response).toString();
}
```

이때 try-catch문을 작성하게 되면, 핸들러를 실행하는데 실패하는 흐름이 똑같은 로직임에도 불구하고, 양쪽 모두 try-catch로 감싼 뒤 동일한 에러 메시지 처리를 해야 합니다. 따라서 코드의 중복과 구현의 불편함 때문에 바깥에서 에러를 한번에 잡아서 처리하도록 `throws`를 사용했습니다.

---

아래는 `throws` 대신 `try-catch`를 사용한 예시입니다.

```java
private void handlerMapping(final Class<?> controllerClass) {
    final Object instance = getControllerInstance(controllerClass);

    Arrays.stream(controllerClass.getDeclaredMethods())
            .filter(method -> method.isAnnotationPresent(RequestMapping.class))
            .forEach(method -> methodMapping(instance, method));
}

private Object getControllerInstance(final Class<?> controllerClass) {
    try {
        return controllerClass.getDeclaredConstructor().newInstance();
    } catch (Exception e) {
        throw new RuntimeException("컨트롤러 인스턴스 생성에 실패했습니다.");
    }
}
```

이 에러는 컨트롤러 인스턴스 생성에 실패해서 발생하는 에러이고 컨트롤러 인스턴스를 가져오는 메서드 안에 들어있습니다. 이때 예외를 던져서 밖에서 잡게 되면, 핸들러 매핑을 하는 곳인데 컨트롤러 인스턴스 생성 오류를 처리하고 있어 어색하게 느껴졌습니다. 따라서 제가 메서드 분리를 한 의도와 일치하는 위치에서 `try-catch`를 사용해서 에러를 처리했습니다.

2024-09-28 17:19 UTC, BurningFalls commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistry.java
> +public class HandlerAdapterRegistry {
registry 네이밍은 LMS의 힌트를 참고했습니다! container도 좋은 것 같아요!

https://techcourse.woowahan.com/s/Cjiz6fNL/ls/6ajJzObL

2024-09-29 04:19 UTC, BurningFalls commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistry.java
> +    }
저도 그 부분을 많이 고민했습니다. 일단 LMS에 있는 힌트를 보고 `addHandlerAdapter`를 만든 다음, 왜 이렇게 구성되어있는지 이유를 찾아보려고 했습니다. 제가 생각해본 근거는 다음과 같았습니다.

* `DispatcherServlet` 생성 시점 이후, 동적으로 새로운 `HandlerAdapter`를 등록해야 할 상황이 발생한다.
* `DispatcherServlet`의 생성 시점에 모든 `Adapter`를 알아야 하는 의존성을 끊을 수 있다.

하지만 GPT를 사용해 검색해보니, 특정 상황(커스텀 설정, 테스트)을 제외하면 일반적인 운영 환경에서는 `HandlerAdapter`와 `HandlerMApping`은 애플리케이션 컨텍스트 초기화 시에만 설정되며, 일반적인 Spring MVC 애플리케이션에서는 `DispatcherServlet`이 `HandlerAdapter`를 가지지 않는 경우는 드물다고 합니다.

따라서, 생성자 시점에서 주입받아도 문제 없을 것 같습니다!

2024-09-29 04:43 UTC, BurningFalls commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +public class HandlerMappingRegistry {
`Registry`에서 basePackage를 기반으로 스캔하는 방법이 있네요! 좋은 인사이트 얻어갑니다. 위의 코멘트에서 말씀드렸던대로 참조 문제 때문에 수동으로 필요한 정보를 받는 방식으로 필드 초기화를 했습니다. step3에서 legacy MVC를 제거하게 된다면, 생성자 선언과 동시에 초기화를 진행하게 될 것 같습니다.

2024-09-29 04:50 UTC, BurningFalls commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +    }
> 저도 동의합니다 ! 저도 해당 부분에서 handler를 실행하도록 하였습니다 ! registry를 저장소라고 볼 수 있지만, 저장소를 만든 이유를 생각하면 저장소에서 원하는 조건에 맞는 객체를 빠르게 찾기 위해서라고 생각합니다.
그래서 굳이 분리하지 않아도 될 것 같아요 ~

**저장소에서 원하는 조건에 맞는 객체(`view`)를 빠르게 찾기 위해서**라는 이유로 정의내리니까 납득이 가기 쉽네요! 👍 감사합니다.

> HandlerMappingContainer : HandlerMapping을 상속한 하위 클래스를 알아내 맞는 Mapping 클래스를 알아내도록 구현
HandlerAdapterContainer : HandlerAdapter을 상속한 하위 클래스를 알아내 맞는 Adapter 클래스를 알아내도록 구현

켬미의 생각을 들으니 코멘트를 순서대로 작성할 때마다 점점 설득되고 있습니다. 제가 현재 겪고 있는 고민 및 문제점들이 패키지 스캐닝을 통한 자동 등록으로 해결될 수 있어 보이네요! step3때 수정해보도록 하겠습니다.

2024-09-29 05:23 UTC, BurningFalls commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +    public Optional<Object> getHandler(final HttpServletRequest request) {
이 부분은 제가 미처 고려하지 못한 부분이었네요! 짚어주셔서 감사합니다. 수정 완료했습니다. https://github.com/woowacourse/java-mvc/pull/751/commits/87c56e85e2931c287e4d43072d27d40cc3a79f2e

2024-09-29 05:24 UTC, BurningFalls commented on mvc/src/test/java/samples/TestManualHandlerMapping.java
> +public class TestManualHandlerMapping implements HandlerMapping {
이 부분도 이전 코맨트와 똑같이 step3에서 Legacy MVC를 제거하면서 리플렉션 사용을 고려해보도록 하겠습니다!

2024-09-29 06:00 UTC, BurningFalls commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistryTest.java
> +        registerHandlerAdapter(new AnnotationHandlerAdapter());
간단해서 그냥 넘어갔는데 켬미의 코멘트를 듣고 테스트를 구현해보니, 제 생각보다 중요한 부분이었네요. 짚어주셔서 감사합니다! 해당 클래스의 테스트를 추가했습니다. https://github.com/woowacourse/java-mvc/pull/751/commits/cfd2be589b6bd4099f8a9c3646ea2dec679a6e45

2024-09-29 09:47 UTC, BurningFalls commented
> (플러스) AnnotationHandlerMapping이 잘되는지 확인하기 위해 로그인이나 회원가입 컨트롤러 중 하나를 AnnotationHandlerMapping을 사용하도록 컨트롤러를 변경해보면 더 좋을 것 같아요 ~!

basePacakge를 "com"으로 변경하고 RequestMapping을 사용하는 LoginController 클래스를 만들어서 테스트 해보았는데, 핸들러 매핑 초기화는 잘 돼서 맵에 담기는데 계속 핸들러 매핑 과정에서 실패합니다. 아마 임의로 만든 LoginController가 잘못 된거 같은데 아무리 해봐도 해결책을 못찾겠네요 ㅠㅠ. 이 부분은 step3에서 마저 도전해보도록 하겠습니다.

2024-09-29 11:55 UTC, kyum-q commented on app/src/main/java/com/techcourse/ManualHandlerMapping.java
> +    private final Map<String, Object> handlers;
폭포의 의도를 알려줘서 고마워요 ~ 뭐든 의도가 명확하니 상관없을 것 같네요 ~!

2024-09-29 11:57 UTC, kyum-q commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
>                      .forEach(method -> handlerMapping(getControllerInstance(controllerClass), method));
어우 너무 예쁘게 반영하셨네요 ~ 코드 가독성이 엄청 좋아졌어요 굿구 ~!

>  그만큼 켬미가 제 코드리뷰를 열심히 해주신 것 같아서 감사해요 ㅎㅎ 😄

더 열심히해야겠다는 욕구가 활활 타오르네요 ~ ㅋㅋㅋ

2024-09-29 11:58 UTC, kyum-q commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapter.java
> +    String handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception;
오 좋은 인사이트네요 ~ 
앞으로 고민될 때 폭포의 기준을 생각해봐야겠어요 ~! 굿 !

2024-09-29 12:00 UTC, kyum-q commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistry.java
> +    }
굿굿 ~! 제가 생각하기에도 어떤 선택지도 문제 없다고 생각해요 ~!

2024-09-29 12:32 UTC, kyum-q requested changes
안녕하세요 폭포 ! 리뷰 반영 너무 잘해주셨네요 ! 
그리고 코멘트로 폭포의 생각을 자세하게 알려줘서 이해하기 쉬웠어요 !

테스트 몇 개가 작동하지 않습니다ㅜㅜ 확인 부탁드려요 작동하지 않는 테스트 목록은 코멘트로 남겨두었습니다. 궁금하신 점있으시거나 테스트 수정되었으면 DM 주세요 ~! 빠르게 approve 드릴게요 ~

2024-09-29 12:32 UTC, kyum-q commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerAdapterTest.java
> +    @Test()
괄호가 없어도 될 것 같아요 ~

2024-09-29 12:32 UTC, kyum-q commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistryTest.java
> +        assertThat(handler).isInstanceOf(TestController.class);
해당 테스트가 통과되지 않고 있어요 ～! 확인 부탁드려요 ~
AnnotationHandlerMapping은 반환값이 컨트롤러가 아니라 HandlerExecution 여서 그런 것 같아요 ~!

2024-09-29 12:32 UTC, kyum-q commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistryTest.java
> +        assertThat(handler).isInstanceOf(TestController.class);
이 외에도 다음 테스트들이 통과되지 않고 있습니다 확인해주세요 ~!
![image](https://github.com/user-attachments/assets/8c2affe5-695b-4187-b71b-a3d682eefa22)

2024-09-29 12:32 UTC, kyum-q commented on study/src/main/java/servlet/com/example/CharacterEncodingFilter.java
> +        response.setCharacterEncoding("UTF-8");
request까지 인코딩 해주는군요 ~ 굿ㄱ ~

2024-09-29 13:31 UTC, BurningFalls commented
페이지 로딩 문제를 해결하려고 계속 코드를 조금씩 수정하다보니, 테스트가 깨지고 있는 것을 미처 파악하지 못하고 있었네요.

`AnnotationHandlerMapping`을 사용하도록 `LoginController`를 만들고, 기존의 컨트롤러는 `LegacyLoginController`로 두었습니다. 그리고 `AnnotationHandlerMapping`을 사용하기 위해 `ManualHandlerMapping`에서 `LoginController`를 등록하는 부분을 주석처리해서 테스트 해보았고, 잘 동작하는 것을 확인했습니다.

여러 부분에서 문제가 발생했어서 코드 변경점이 상당히 많았습니다. 이에 맞춰서 테스트도 전부 통과하도록 최종수정 완료했습니다!

2024-09-29 13:35 UTC, kyum-q approved these changes
폭포 테스트 확인했습니다 ～ 수고하셨어요 ～!
3단계까지 화이팅 해봐요 ~

2024-09-29 13:35 UTC, merged