[MVC 구현하기 - 2단계] 리니(이예린) 미션 제출합니다.
woowacourse/java-mvc pull request #752
Opened 2024-09-26 01:02 UTC by linirini

안녕하세요, 망쵸🖐️
2단계 미션 제출합니다~!
Legacy 컨트롤러 인터페이스도 지원하기 위해서 어댑터 패턴을 사용해서 dispatcher servlet이 다양한 방식의 컨트롤러를 처리할 수 있도록 변경했습니다.
이번에도 리뷰 잘 부탁드립니다🙇‍♀️

2024-09-28 02:30 UTC, 3Juhwan requested changes
안녕하세요 리니 😀 망쵸입니다. 
2단계 깔끔하게 작성해 주셨네요 👍 제가 작성한 코드와 비슷해서 보는 데에 비교적 편했네요. 
궁금한 점 코멘트로 남겼으니 확인하고 답변해 주시면 감사하겠습니다 🙌

- 추가로, 새로 추가된 인터페이스와 구현체들(맵핑, 어댑터 등)의 패키지 위치에 대해 어떤 이유로 지금처럼 두었는지 궁금해요! 
- 마지막 컨벤션 커밋을 확인하지 않아서 그런지, 일부 코드가 컨벤션에 맞지 않네요! 일단 보는 대로 남겼는데, 이미 반영된 거라면 넘기셔도 괜찮을 것 같아요. 컨벤션 먼저 바로 잡고, 이후 코드에 대한 리뷰를 요청해 주시면 감사하겠습니다!

2024-09-28 02:30 UTC, 3Juhwan commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyTest.java
> +    }
동등성이 아닌 동일성을 비교한 이유는 무엇인가요?

2024-09-28 02:30 UTC, 3Juhwan commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>      public void init() {
또, 디스패처 서블릿은 언제 생성되고 언제 초기화될까요?

2024-09-28 02:30 UTC, 3Juhwan commented on app/src/main/java/com/techcourse/TomcatStarter.java
> +    public TomcatStarter(String webappDirLocation, int port) {
우리 `app`을 보면 `tomcat`을 실행시키는 코드만 있는데, 어떻게 우리가 만든 `mvc`를 사용할 수 있을까요?

2024-09-28 13:14 UTC, linirini commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerAdapters = addHandlerAdapters();
일급 컬렉션으로 분리하면서, 말씀해주신 부분도 수정했습니다!
네이밍이 어울리지 않기도 하고, [이 코멘트](https://github.com/woowacourse/java-mvc/pull/752#discussion_r1779328557)에서 말씀해주신 것처럼 하나의 메서드에서 두가지 역할을 하고 있었던 것 같아요!

DispatcherServlet이 처음 초기화되는 시점에 HandlerMappings와 HandlerAdapters를 초기화했습니다.
그리고 `DispatcherServlet.init`이 호출되는 시점에 사용자 정의 HandlerMapping을 추가(`add`)해준 후에 초기화(`initialize`)할 수 있도록 책임을 분리했습니다!

2024-09-28 13:41 UTC, linirini commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private HandlerMapping getHandlerMapping(HttpServletRequest request) {
`find*` 네이밍은 탐색 결과가 없더라도 내부에서 예외를 발생시키지 않습니다. 반면, `get*`은 무조건 1개 이상의 탐색 결과가 있을 것을 기대합니다. 따라서,  `get*` 네이밍은 탐색 결과가 없을 경우 예외를 발생시킵니다.

코드에서 네이밍을 혼용해서 사용하고 있었던 것 같아요!
일급 컬렉션을 분리하면서 네이밍을 좀 더 분명하게 구분해서 사용했습니다.
일급 컬렉션(`HandlerMappings`, `HandlerAdapters`)에서 값을 handler/adapter를 찾아오고(`find*`), `dispatcherServlet`에서 값이 없을 경우에는 예외를 발생시키고 handler/adapter를 반환(`get*`)할 수 있도록 리팩터링했습니다.

2024-09-28 13:43 UTC, linirini commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyTest.java
> +    }
`HandlerKey`는 내부에서 값이 존재하면 재사용하고, 존재하지 않으면 새로운 인스턴스를 생성할 수 있도록 구현했습니다. 따라서, 이미 존재하는 인스턴스를 재사용하는지를 검증하고자 동일성을 비교했습니다.

2024-09-28 15:21 UTC, linirini commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>      public void init() {
Spring Framwork에서 DispatcherSerlvet은 서블릿 컨테이너(Tomcat)에 의해 관리됩니다.
서블릿 컨테이너에 의해 DIspatcherServlet이 생성되는 시점에는 아직 초기화 작업이 이루어지지 않고, 인스턴스만 메모리에 로드됩니다.
이후, 서블릿 컨테이너가 `init()` 메서드를 호출하는 시점에 초기화 작업이 이루어집니다. 이 시점에 필요한 의존성 주입이나 설정 작업(HandlerMapping, ViewResolver 등)이 이루어집니다. 
즉, 초기화 작업을 서블릿이 실제로 사용하는 시점까지 지연시켜 서블릿이 필요한 시점에만 초기화합니다. 이러한 전략 덕분에 메모리와 리소스를 효율적으로 관리하고, 애플리케이션이 빠르게 구동될 수 있습니다.
DispatcherServlet이 이처럼 생성과 초기화가 분리된 구조는 유연성과 확장성 높입니다.
생성 단계와 분리되어 초기화 단계에 설정이나 의존성을 주입하여 DispatcherServlet을 커스터마이징할 수 있습니다.

2024-09-28 15:50 UTC, linirini commented on app/src/main/java/com/techcourse/TomcatStarter.java
> +    public TomcatStarter(String webappDirLocation, int port) {
Tomcat이 실행될 때 `SpringServletContainerInitializer`가 자동으로 실행됩니다.
`SpringServletContainerInitilizer`는 `@HandlerTypes` 어노테이션을 가지고 있습니다. 그리고 어노테이션에 명시된 `WebApplicationInitializer`를 구현한 모든 클래스를 찾습니다.
이 과정에서 감지된 `DispatcherServletInitializer를` 포함한 구현체들은 `onStartup` 메서드가 호출되어 서블릿 컨텍스트에 등록됩니다.
그리고 `DispatcherServletInitializer`는 `DispatcherServlet을` 등록하고 매핑경로를 설정하여 우리가 만든 `mvc`를 사용할 수 있게 됩니다.

2024-09-28 16:15 UTC, linirini commented
> * 추가로, 새로 추가된 인터페이스와 구현체들(맵핑, 어댑터 등)의 패키지 위치에 대해 어떤 이유로 지금처럼 두었는지 궁금해요!
`HandlerMapping`과 `HandlerAdapter` 인터페이스는 framework에서 제공하므로, webmvc 패키지 내에 위치시켰습니다. 그리고 이에 대한 구현체는 구현체를 사용하는 패키지 내부에 위치시켰는데요,
이렇게 인터페이스와 구현체의 패키지 위치를 분리한 이유는 사용하는 쪽에서는 인터페이스에 대한 의존성을 유지하면서 구현체의 변경에도 영향 받지 않게 하기 위함입니다.

그 안에서도,
- `AnnotationHandlerMapping`은 프레임워크에서 제공하지만, `ManualHandlerMapping`은 개발자 정의 핸들러 매핑이기 때문에 위치하는 모듈을 다르게 유지했습니다.
- Controller 인터페이스는 프레임워크에서 제공하므로, `AnnotationHandlerAdapter`와 함께 `ControllerHandlerAdapter` 모두 프레임워크 모듈 내 관련된 패키지에 위치했습니다.

2024-09-29 01:39 UTC, 3Juhwan commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerAdapters = addHandlerAdapters();
일급 컬렉션으로 분리하셨군요..! 분리하신 이유가 무엇인가요? 스프링은 어떻게 구현되어 있나요?

2024-09-29 01:47 UTC, 3Juhwan commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>      public void init() {
열심히 답변해 주셔서 감사해요 👍 

저도 찾아보니, 2가지 정도 이유가 있었어요. 1) JDK 1.0 [이슈](https://stackoverflow.com/questions/2381976/why-can-not-we-call-servlet-constructor-instead-of-init-method-to-initialize-the) 2) 무거운 초기화 과정을 생성 시점에서 분리하여 빠른 구동과 유연성 증가

궁금한 점이 생겼어요. DispatcherServlet의 초기화는 사용자의 첫 요청이 들어온 시점에 초기화되고, 이로 인해 응답 지연이 발생하는데요. 애플리케이션 구동 시간이 조금 더 오래 걸리더라도, 필요한 빈들은 초기화해두고 서비스를 시작하는 것이 더 낫지 않을까요? [실제](https://mangkyu.tistory.com/232)로 첫 요청은 지연되는 문제가 있어요.

2024-09-29 01:54 UTC, 3Juhwan commented on app/src/main/java/com/techcourse/TomcatStarter.java
> +    public TomcatStarter(String webappDirLocation, int port) {
> Tomcat이 실행될 때 SpringServletContainerInitializer가 자동으로 실행됩니다.

자동으로 실행된다는 게 조금 명확하지 않은 것 같아요. Tomcat은 어떻게 SpringServletContainerInitializer를 아나요? 그리고 서블릿 컨텍스트를 초기화하는 방법은 어떤 것이 있을까요?

2024-09-29 02:12 UTC, 3Juhwan requested changes
리니~ 빠르게 피드백 반영해 주셨네요 😀 
몇 가지 궁금한 점이 있어서 질문 남겼는데, 답변해주시면 머지하도록 할게요! 
힘내세요 ✊✊

2024-09-29 02:12 UTC, 3Juhwan commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +    @RequestMapping(value = "/register", method = RequestMethod.GET)
페이지 라우팅도 수정해야겠어요

2024-09-29 03:51 UTC, linirini commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerAdapters = addHandlerAdapters();
일급컬렉션으로 분리하면서 "저장소"로서의 역할을 분리할 수 있었어요!
덕분에 각 일급 컬렉션에 초기화/핸들러 매핑&핸들러 어댑터 추가 및 조회의 책임을 위임할 수 있었습니다.
## Spring 에서의 구현
스프링에서는 우선 크게보면, DispatcherServlet이 init 될 때 내부적으로 `handlerAdapters`라는 리스트에 등록됩니다. 그리고 getHandlerAdapter메서드에서는 이 list를 loop 돌면서 인자로 받은 handler를 처리할 수 있는 handlerAdapter를 찾아서 반환합니다. 만약, 찾지 못한다면 ServletException을 발생시킵니다.
HandlerMapping도 비슷하게 DispatcherServlet이 init 되는 과정에서 handlerMapping들이 `handlermappings`라는 리스트에 등록됩니다. 해당 list를 loop돌면서 요청에 맞는 `HandlerMapping` 찾아 반환합니다. 만약 찾지 못한다면, null을 반환하는 구조를 가지고 있습니다.
``` java
	@Nullable
	protected HandlerExecutionChain getHandler(HttpServletRequest request) throws Exception {
		if (this.handlerMappings != null) {
			for (HandlerMapping mapping : this.handlerMappings) {
				HandlerExecutionChain handler = mapping.getHandler(request);
				if (handler != null) {
					return handler;
				}
			}
		}
		return null;
	}
```
아래에 추가적으로 `HandlerMapping` 을 찾아 최종적으로 handler를 찾아오는 과정(`mapping.getHandler()`)까지  정리해봤습니다.
### AbstractHandlerMapping.getHandler
실제로 Handler를 가져오는 `getHandler`는 추상 클래스인 `AbstractHandlerMapping`에 정의되어 있는데요, 내부적으로 `getHandlerInternal`을 통해서 handler를 찾아와서 `HandlerExecutionChain`을 return 하는 구조를 취하고 있습니다.
### AbstractHandlerMethodMapping.getHandlerInternal
`AbtractHandlerMapping`을 구현하고 있는 `AbstractHandlerMethodMapping`에서 `getHandlerInternal` 메서드를 구현하고 있습니다.
메서드 내부에서는 요청에서 분석한 lookupPath를 기반으로 handler method를 찾아옵니다. 이때, handler method를 찾기 위해 `mappingRegistry`에 접근합니다. 내부 클래스인 `MappingRegistry`에서 `handler method`에 대한 `mapping`을 유지 관리하고 있습니다.
### MappingRegistry
`MappingRegistry`는 내부적으로 `LinkedMultiValueMap`에 key는 url, value로 여러 handlerMethod에 대한 정보를 담아놓습니다.
`lookupHandlerMethod()`에서는` mappingRegistry.getMappingsByUrl()`로 현재 url에 mapping되는 handler method들의 RequestMappingInfo들을 가져옵니다.
가져온 값들을 기반으로 request와 가장 일치하는 값을 기반으로 최종적으로 handlerMethod를 반환합니다.

2024-09-29 04:14 UTC, linirini commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +    @RequestMapping(value = "/register", method = RequestMethod.GET)
`login.jsp`에서 register view url을 수정하지 않았었습니다😂
수정하고 페이지 동작하는 거 확인했습니다-!

2024-09-29 04:41 UTC, linirini commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>      public void init() {
>  in JDK 1.0 (for which servlets were originally written), constructors for dynamically loaded Java classes (such as servlets) couldn't accept arguments. So, in order to provide a new servlet any information about itself and its environment, a server had to call a servlet's init() method and pass along an object that implements the ServletConfig interface.

이건 처음 알았네요! 레퍼런스 공유해주셔서 감사합니다 ㅎㅎ

> DispatcherServlet의 초기화는 사용자의 첫 요청이 들어온 시점에 초기화되고, 이로 인해 응답 지연이 발생하는데요. 애플리케이션 구동 시간이 조금 더 오래 걸리더라도, 필요한 빈들은 초기화해두고 서비스를 시작하는 것이 더 낫지 않을까요?

공유해주신 블로그를 저도 봤었는데요, 저도 첫 요청 지연 문제보다 지연 초기화로 얻는 이점(JDK 1.0 이슈, 무거운 초기화 과정을 생성 시점에서 분리하여 빠른 구동과 유연성 증가)이 더 큰지는 와닿지 않았어요!
어떤 것이 더 나을지를 판단하기에는 제 경험이나 학습이 아직은 부족한 것 같습니다. 추후에 더 학습해보도록 하겠습니다🥲

2024-09-29 05:02 UTC, linirini commented on app/src/main/java/com/techcourse/TomcatStarter.java
> +    public TomcatStarter(String webappDirLocation, int port) {
> Tomcat은 어떻게 `SpringServletContainerInitializer`를 아나요?

`META-INF/services/jakarta.servlet.ServletContainerInitializer` 경로에 `ServletContainerInitializer` 를 구현한 클래스인 `SpringServletContainerInitializer` 의 경로가 포함되어있습니다.
Tomcat과 같은 서블릿 컨테이너는 애플리케이션을 로드할 때 이 파일을 확인하여 서블릿 초기화 인터페이스인 `ServletContainerInitializer`의 구현체들을 불러와서 `onStartup` 메서드를 호출하게 됩니다.

> 서블릿 컨텍스트를 초기화하는 방법은 어떤 것이 있을까요?

서블릿  컨텍스트를 초기화하는 방법은 크게 2가지가 있습니다.

1) `web.xml`을 통한 초기화
Servlet 2.x 시절에는 `web.xml` 파일을 통해 서블릿과 필터를 정의하고 초기화했습니다.
`web.xml`은 서블릿 초기화 매개변수, 필터 설정, 서블릿 매핑 등을 설정하는 데 사용됩니다. 그러나 최신 스프링 애플리케이션에서는 점점 덜 사용되고 있습니다.

2) `ServletContainerInitializer`를 통한 초기화
서블릿 3.0부터는 `ServletContainerInitializer`를 통해 프로그램적으로 서블릿을 등록할 수 있습니다. Spring에서는 `SpringServletContainerInitializer`가 이 역할을 합니다.
`SpringServletContainerInitializer`는 `@HandlesTypes` 어노테이션을 사용하여 `WebApplicationInitializer` 인터페이스를 구현한 클래스를 탐색합니다.
탐색된 클래스들은 `onStartup()` 메서드를 호출하여, `DispatcherServlet`과 같은 서블릿을 ServletContext에 등록할 수 있습니다.

2024-09-29 15:05 UTC, 3Juhwan commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>      public void init() {
다 읽어보셨군요 😄 의견 공유해 주셔서 감사해요. 

> 어떤 것이 더 나을지를 판단하기에는 제 경험이나 학습이 아직은 부족한 것 같습니다.

저도 궁금하네요 🧐 빨리 구동하더라도 첫 요청을 빠르게 처리하지 못하는 상황인데요! 만약 스프링 빈 초기화로 인해 지연 시간이 증가한다면, 애플리케이션을 띄우고 웜업하는 과정을 거치는 게 좋을까요? 그렇다면 빨리 구동하는 게 메리트가 있는지... 모르겠네요. 유사한 사례로 JVM에서도 이슈가 있어요. [카카오 2022 if](https://www.youtube.com/watch?v=CQi3SS2YspY&t=14)에서 다뤄지기도 했답니다.

2024-09-29 15:09 UTC, 3Juhwan approved these changes
리니~ 마지막까지 꼼꼼히 답변해 주셔서 감사합니다 👍 
다음 단계로 넘어가시죠 🙌

2024-09-29 15:09 UTC, merged