[MVC 구현하기 - 2단계] 냥인(최가희) 미션 제출합니다.
woowacourse/java-mvc pull request #753
Opened 2024-09-26 02:32 UTC by cutehumanS2

2024-09-26 02:39 UTC, cutehumanS2 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            }
아토 ~ 이 부분은 이번 단계 요구사항을 만족시키려고 하다 보니 
다시 이쪽으로 로직을 옮기게 되었어요. 😿

2024-09-27 10:09 UTC, hyxrxn requested changes
냥인 안녕하세요! 또다시 아토입니다.
이번 단계 요구사항도 잘 구현해주신 것 같아요!

`같아요`인 이유는... 제가 아직 요구사항을 완벽히 이해하지 못했기 때문이랍니다 😹
그래서 간단한 질문 몇 가지 남겨보았어요!
편하게 답변 주시길 바랍니다~~~

테코톡과 데모데이가 모두 지나갔으니... 앞으로는 꼭 빠른 리뷰... 약속드리며 물러갑니다...

2024-09-27 10:09 UTC, hyxrxn commented on study/src/main/java/servlet/com/example/CharacterEncodingFilter.java
> +        //response.setLocale(Locale.KOREA);
전체 테스트를 돌릴 때 필터 테스트가 간헐적으로 터지네요 ㅠㅠ
이유가 뭘까요

2024-09-27 10:09 UTC, hyxrxn commented on study/src/test/java/servlet/com/example/ServletTest.java
> +        assertThat(Integer.parseInt(response.body())).isEqualTo(3);
제가 받았던 질문인데요! (라고 하면 제 pr에 스포일러가 있다고 알려주는 꼴이지만...)
어플리케이션을 실행시킨 후 이 테스트를 여러 번 돌려보시면 두 번째부터는 테스트가 실패합니다.
이유가 뭘까요??

2024-09-27 10:09 UTC, hyxrxn commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistry.java
> +        }
요기서 null을 리턴하게 되면 어떤 일이 생기나요?

2024-09-28 05:50 UTC, cutehumanS2 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    protected void service(HttpServletRequest request, HttpServletResponse response) throws ServletException {
음 왠지 HttpServletRequest와 HttpServletResponse는 재할당될 수 없을 거로 생각했는데,
찾아 보니 재할당될 여지가 있네요. 😅

다시 붙여주었어요. ㅎ ㅎ

2024-09-28 05:51 UTC, cutehumanS2 commented on study/src/main/java/servlet/com/example/CharacterEncodingFilter.java
> +        //response.setLocale(Locale.KOREA);
아토의 코멘트를 보고 servlet 패키지에 있는 테스트를 일괄적으로 많이 실행해 봤습니다. 
ServletTest는 간헐적으로 실패해도 FilterTest는 한 번도 실패하지 않아서 실패 원인을 찾을 수 없었어요. 😿

혹시 실패한 상황을 화면 캡처 등의 수단으로 보여주실 수 있을까요…?

2024-09-28 05:51 UTC, cutehumanS2 commented on study/src/test/java/servlet/com/example/ServletTest.java
> +        assertThat(Integer.parseInt(response.body())).isEqualTo(3);
오.. 그러네요. 
포트 충돌이 나서 발생하는 문제로 판단됩니다. 

TomcatStarter와 HttpUtils 코드를 수정해서 테스트마다 포트를 달리 지정해 주면 해결될 것 같은데, 
이번 학습 범위에서는 벗어나는 것 같아 코드를 변경하지는 않았어요. ㅎ ㅎ

2024-09-28 05:52 UTC, cutehumanS2 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistry.java
> +        }
해당 메서드를 호출하는 곳에서 null 처리를 안 해주면 NPE가 발생합니다. 

DispatcherServlet.service() 메서드에서 null처리를 하도록 변경했다가, 
null 대신 옵셔널을 사용하도록 리팩토링하여, isEmpty인 경우 404 응답을 던져주도록 또 다시 변경하였습니다.

2024-09-28 05:56 UTC, cutehumanS2 commented
아토 안녕하세요 ~ 😸
테코톡과 데모 데이가 끝나 조금 후련하실 것 같아요. ㅎ ㅎ

남겨 주신 코멘트에 답변 달아 두었으니 확인 부탁드려요.
즐거운 주말 보내세요. 🤍

<hr>

추가적인 변경 사항을 아래 간략히 적어 둘게요.

- null 처리 방식 → 옵셔널을 사용하여 처리하는 방식
- ControllerScanner 클래스 구현
- HandlerMappingRegistry, HandlerAdapterRegistry 생성 위치를 DispatcherServlet의 생성자로 변경

2024-09-29 05:52 UTC, hyxrxn commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    protected void service(HttpServletRequest request, HttpServletResponse response) throws ServletException {
final을 붙이며 줄 길이가 우테코 자바 컨벤션을 넘어갔네용!
사소하지만 한 번 확인 부탁드려요~~~
이 메서드의 안에도 한 줄 확인해봐야 하겠어요!

2024-09-29 05:54 UTC, hyxrxn commented on study/src/main/java/servlet/com/example/CharacterEncodingFilter.java
> +        //response.setLocale(Locale.KOREA);
<img width="1565" alt="image" src="https://github.com/user-attachments/assets/4221509d-3246-4fe6-96bb-5d18326c6db5">

밑의 로그를 더 보고싶으시면 DM 주세요!

2024-09-29 05:55 UTC, hyxrxn commented on study/src/test/java/servlet/com/example/ServletTest.java
> +        assertThat(Integer.parseInt(response.body())).isEqualTo(3);
그렇다면 포트 충돌이 나는데 중간에 테스트가 중단되지 않는 이유는 뭘까요???

2024-09-29 06:01 UTC, hyxrxn commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistry.java
> +        }
좋아요~~~~~

2024-09-29 06:03 UTC, hyxrxn commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            ModelAndView modelAndView = modelAndViewOptional.get();
isEmpty와 get을 사용하는 부분이 조금 가독성을 떨어뜨리지 않나 싶은데요,
옵셔널의 메서드를 활용해 없다면 예외를 던지고 아래에서 그것을 캐치해 상태코드를 설정해주는 방식은 어떤가요??
예외를 던지는 것이 맞을지 고민을 조금 해보아야겠지만...
생각 해보시고 답변 주세요!

2024-09-29 06:06 UTC, hyxrxn commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java
LGTM

2024-09-29 06:13 UTC, hyxrxn commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
이번 미션을 하며 생긴 개인적인 궁금증인데요!

패키지명인 asis / tobe는 어떤 의미일까요?
as is는 그대로 두고, to be는 변경하라는 의미인가 싶었는데,
그렇다면 구현 이후 패키지명을 본인의 의도에 맞게 바꾸어야하지 않나 싶어서요~

냥인의 생각이 궁금해 코멘트 남깁니다!

2024-09-29 06:14 UTC, hyxrxn requested changes
아마도 마지막 rc일 듯 합니다!
필터 테스트를 제외하고는 질문에 대한 답변 정도만 주시면 될 것 같아요~~
화이팅입니닷

2024-09-29 07:36 UTC, cutehumanS2 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    protected void service(HttpServletRequest request, HttpServletResponse response) throws ServletException {
반영하였습니다. ㅎ ㅎ

2024-09-29 07:36 UTC, cutehumanS2 commented on study/src/main/java/servlet/com/example/CharacterEncodingFilter.java
> +        //response.setLocale(Locale.KOREA);
보여주셔서 감사합니다. ㅎㅎ
이전에 말씀드렸던 것과 동일한 포트 충돌 문제네요. 😅
아토도 같은 문제를 겪으셨던 건가요? 그렇다면 어떻게 해결하셨나요? 
포트가 충돌되지 않도록 코드를 변경해 주었나요? ?

2024-09-29 07:37 UTC, cutehumanS2 commented on study/src/test/java/servlet/com/example/ServletTest.java
> +        assertThat(Integer.parseInt(response.body())).isEqualTo(3);
테스트가 중단되지 않았다는 게, 포트 충돌이 나면 톰캣이 서버를 시작하려고 시도하다가 중지해 버리는데, 왜 HttpUtils.send() 요청이 나가냐는 말씀이신 거 맞죠…? 

아토의 코멘트를 이렇게 파악하고 찾아봤는데, 잘 모르겠어요. 😿
그래서 아토가 리뷰어께 답변하신 코멘트도 봤는데 “톰캣이 내부적으로 자원 정리를 진행한다”는 게 어떻게 “포트가 충돌 나도 테스트가 중단되지 않는 이유”가 되는지 와닿지 않습니다..

아토가 설명해 주실 수 있나요…? 🥺

2024-09-29 07:38 UTC, cutehumanS2 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            ModelAndView modelAndView = modelAndViewOptional.get();
반영하였습니다. 

예외를 handlerMappingRegistry.getHandler()와 handlerAdapterRegistry.execute() 안에서 던지는 방법도 생각해 봤는데, 
테스트 코드 포함 변경점이 좀 있을 것 같아 이 부분은 다음 단계에서 반영하겠습니다. ㅎ ㅎ

2024-09-29 07:38 UTC, cutehumanS2 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
말씀하신 대로 저도 asis는 기존 코드고, tobe는 리팩토링 하거나 새로 구현한 것들을 둔다고 생각했어요. 
구현 완료 후 패키지명을 의도에 맞게 변경해야 한다는 점, 동의합니다. 👍

아마 이 작업은 3단계 요구사항을 구현하면서 이루어질 듯 싶네요. 
스포지만 asis를 지우는 요구사항이 있더라고요. ㅎ ㅎ

2024-09-29 11:09 UTC, hyxrxn commented on study/src/main/java/servlet/com/example/CharacterEncodingFilter.java
> +        //response.setLocale(Locale.KOREA);
몰랐는데... 저도 같네요
포트 충돌을 피하는 것까지 필요할까 싶은데...
저도 아직 잘 모르겠군요 ㅠㅠ
더 고민해봐야겠어요

2024-09-29 11:11 UTC, hyxrxn commented on study/src/test/java/servlet/com/example/ServletTest.java
> +        assertThat(Integer.parseInt(response.body())).isEqualTo(3);
그 질문 맞습니다!

저도 정확히는 모르겠어요 😹
더 자세히 알게 되면... 설명해드리겠습니다...
혹시 냥인이 저보다 더 잘 알 수 있지 않을까 해서 물어봤습니다 ㅋㅋㅋㅋ

2024-09-29 11:13 UTC, hyxrxn commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
오! 다음 단계에 있었군요 ㅋㅋㅋㅋㅋ
알겠습니다~~~

2024-09-29 11:14 UTC, hyxrxn approved these changes
확인 잘 했습니다!
포트 관련 의문점은... 각자 더 알아보는 것으로 해요.
다음 단계로 갑시다~~~

2024-09-29 11:14 UTC, merged