[MVC 구현하기 - 2단계] 카키(서현준) 미션 제출합니다.
woowacourse/java-mvc pull request #761
Opened 2024-09-26 15:18 UTC by hyeon0208

안녕하세요 뽀로로 ~
2단계 미션 요구사항데로 인터페이스 기반 컨트롤러와 어노테이션 기반 컨트롤러가 공존하도록 만들어 봤습니다.
저번 리뷰로도 많은 점을 배울 수 있었어요 
이번 리뷰도 잘 부탁드립니다

2024-09-28 16:06 UTC, jcoding-play requested changes
리뷰 늦어 정말 죄송합니다.. 😭
다음에는 정말 요청 오면 곧바로 응답 드리겠습니다..ㅎㅎ

코드가 많이 바뀐 부분이 없고, 코드 문제 없이 잘 짜셨다고 생각 들어서 간단한 코멘트 몇개 남겼습니다!
확인해보시고 리뷰 요청 보내주시면 감사하겠습니다~

2024-09-28 16:06 UTC, jcoding-play commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/CompositeHandlerMappingTest.java
> +        };
인터페이스 활용 좋네요 👍

2024-09-29 07:23 UTC, hyeon0208 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        annotationHandlerMapping.initialize();
이 부분 생각을 못했었네요 😅
RegisterController도 어노테이션 기반 컨트롤러로 변경해도 정상 동작하도록
techcourse의 컨트롤러 패키지를 가리키도록 수정했습니다 !

2024-09-29 07:26 UTC, hyeon0208 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/CompositeHandlerMapping.java
> +        throw new IllegalArgumentException("해당 요청을 처리할 수 있는 핸들러가 존재하지 않습니다. : " + invalidRequestInfo);
감사합니다 👍  반영 완 !

2024-09-29 07:36 UTC, hyeon0208 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            }
좋은 것 같아요 👍 
핸들러 실행 로직을 메서드로 분리하여 메서드별로 책임이 명확해 질 수 있도록 수정했습니다 !

2024-09-29 07:37 UTC, hyeon0208 commented
좋은 리뷰 감사합니다 뽀로로 👍 
말씀해주신 부분들 반영해서 다시 리뷰 요청 드려요 !

2024-09-29 09:45 UTC, jcoding-play approved these changes
리뷰 반영 확인했습니다!!
2단계도 수고 많으셨고, 3단계도 화이팅입니다!~~ 👍

2024-09-29 09:45 UTC, merged