[MVC 구현하기 - 2단계] 카고(정민호) 미션 제출합니다.
woowacourse/java-mvc pull request #768
Opened 2024-09-27 13:48 UTC by devhoya97

안녕하세요 안나! 

힌트를 보면서 2단계 미션을 진행했는데요.

> 찾은 Class를 controller 라는 오브젝트로 생성해주는 것 까지 HandlerMapping의 역할일까요? 😲

힌트에 나와있는 ControllerScanner 객체를 보고 안나가 앞서 리뷰해줬던 내용이 바로 떠올랐습니다! 깊은 뜻이 있었네요 :)
ControllerScanner 객체를 만들면서 책임 분리가 됐고, 리뷰 반영이 자연스럽게 된 것 같아요.

이번에도 리뷰 잘 부탁드립니다!

2024-09-28 05:45 UTC, Mingyum-Kim requested changes
안녕하세요 카고 ~ 
요구사항 잘 반영해주셨네요 👍👍👍

객체지향 코드를 너무 잘 구현하셔서 읽기 좋았습니다.
몇 가지 의견 남겨놓았으니 확인해주세요! 좋은 주말 보내세요 ~

2024-09-28 05:45 UTC, Mingyum-Kim commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.getView().render(Map.of(), request, response);
와우 추상화를 아주 잘 사용하셨네요! `canHandle`을 사용해서 인스턴스 타입 검사를 각 구현 클래스에 위임하신 것도 너무 좋습니다 👍

2024-09-28 05:45 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/adapter/ControllerAdapter.java
> +        return new ModelAndView(view);
Controller 인터페이스를 사용하는 컨트롤러들은 모두 JspView만 사용할 수 있네요!
ControllerAdapter가 어떤 뷰를 사용할 지도 정해주는 역할을 하고 있는 것 같아요. 

만약 컨트롤러에서 여러 뷰를 사용한다고 했을때, 어떻게 개선해볼 수 있을까요?

2024-09-28 05:45 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
> -        }
NULL 처리를 여기서 하지 않고 외부 스트림에서 아예 제외해주었네요. 
만약 요청이 매핑될 핸들러가 없다면 전부 NULL을 반환해야한다는 제약 조건이 생기기는 하지만 .... 

매번 HandlerMapping 구현체에서 예외를 던지기보다 Registry 에서 한번에 처리하는 것이 나을 것 같기도 하네요 😀
카고도 이를 의도하고 하신 게 맞죠?

2024-09-28 05:45 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
ControllerScanner로 분리하신 점 너무너무 좋습니다 ! 👍 
하지만 여전히 메서드 추출 과정에서의 코드도 많이 남아있는게 아쉬워요. 
AnnotationHandlerMapping이 주요 메서드인 getHandler() 메서드를 가시적으로 확인할 수 있게 메서드 추출 과정도 별도의 클래스로 분리하는 게 어떨까요? 

제안이니 선택적으로 반영해주시면 됩니다!

2024-09-28 05:45 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
> +            methods.forEach(method -> addHandlerExecution(controllers.get(controllerClass), method));
`Set` 자료구조에서 `Map` 자료구조로 변경하신 이유가 무엇일까요?

2024-09-28 05:45 UTC, Mingyum-Kim commented on app/src/main/java/com/techcourse/controller/annotation/RegisterController.java
현재 ManualHandlerMapping과 AnnotationHandlerMapping 두 곳에 `/register` 엔드포인트가 연결되어있는데요, 

사용자가 해당 API로 요청을 보내면 어떻게 될까요? 
테스트도 작성해주시면 감사하겠습니다!

2024-09-28 09:42 UTC, devhoya97 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/adapter/ControllerAdapter.java
> +        return new ModelAndView(view);
```java
public interface Controller {
    String execute(final HttpServletRequest req, final HttpServletResponse res) throws Exception;
}
```

컨트롤러 인터페이스의 execute 메서드의 반환값은 항상 `String viewName;` 이기 때문에 JspView외에 다른 View 구현체를 사용할 일이 없을 거라 생각했어요. 또한 Adapter는 항상 ModelAndView를 반환해줘야 하기 때문에 어떤 뷰를 사용할 지 정하는 역할돌 Controller와 DispatcherServlet의 연결다리 역할을 하는 Adapter가 수행해야 한다고 이해했습니다!

현재 구조에서 Controller 인터페이스를 사용하는 컨트롤러들이 JspView 외에 다른 View를 이용하고 싶다면 execute 메서드의 반환타입이 변경되어야 한다고 생각하는데 안나의 생각은 어떤가요?!

2024-09-28 09:50 UTC, devhoya97 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
> -        }
> 매번 HandlerMapping 구현체에서 예외를 던지기보다 Registry 에서 한번에 처리하는 것이 나을 것 같기도 하네요 😀 카고도 이를 의도하고 하신 게 맞죠?

맞습니다! HandlerMappingRegistry라는 일급컬렉션이 등장했기 때문에, 하나의 HandlerMapping에서 handler를 찾지 못했다고 해도 다음 HandlerMapping에서 handler를 찾을 가능성이 있습니다. 따라서 모든 HandlerMapping을 순회했는데도 handler를 찾지 못했을 경우 예외를 던지도록 구현했습니다!
```java
// HandlerMappingRegistry.class
    public Object getHandler(HttpServletRequest request) {
        return handlerMappings.stream()
                .map(handlerMapping -> handlerMapping.getHandler(request))
                .filter(Objects::nonNull)
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("HttpServletRequest에 대응하는 handler를 찾을 수 없습니다. requestURI = " + request.getRequestURI()));
    }
```

2024-09-28 13:03 UTC, devhoya97 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
말씀해주신대로 AnnotationHandlerMapping의 initialize 과정에서 책임 분리가 더 필요할 것 같아요.

MethodScanner와 RequestMappingResolver라는 객체에게 역할을 분담하는 방식으로 반영했습니다!

2024-09-28 13:08 UTC, devhoya97 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
> +            methods.forEach(method -> addHandlerExecution(controllers.get(controllerClass), method));
리플렉션으로 클래스를 가져오는 책임을 ControllerScanner에게 위임하면서, 컨트롤러 인스턴스를 생성하는 책임까지 함께 위임했습니다. AnnotationMappingHandler 입장에서는 초기화를 위해 Class<?>도 필요하고 인스턴스도 필요한 상황이라 Map으로 받으면 더 편리하게 활용할 수 있더라구요!

2024-09-28 13:50 UTC, devhoya97 commented on app/src/main/java/com/techcourse/controller/annotation/RegisterController.java
AnnotationHandlerMapping에 등록된 컨트롤러가 동작합니다! handlerMappingRegistry에 먼저 등록되었기 때문입니다.

Mock을 사용해서 테스트코드 추가했습니다! 뭔가 정확하게 테스트하려면 Spy같은 걸 활용해서 Annotation기반 컨트롤러의 메서드가 호출되었는지 확인하는 것이 이상적일 것 같은데 테스트 코드에 대한 공부가 좀 더 필요할 것 같아요...!

2024-09-29 00:36 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/adapter/ControllerAdapter.java
> +        return new ModelAndView(view);
> 현재 구조에서 Controller 인터페이스를 사용하는 컨트롤러들이 JspView 외에 다른 View를 이용하고 싶다면 execute 메서드의 반환타입이 변경되어야 한다고 생각하는데 안나의 생각은 어떤가요?! 

저도 동의해요 ~
뷰는 자주 바뀔 수 있는 부분이기 때문에 확장성 있게 두는 것이 좋다는 생각에서 리뷰 남겼습니다.

어떻게 변경되야할 지 잘 알고 계신 것 같아 해당 리뷰는 resolve 처리하겠습니다!

2024-09-29 00:36 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/adapter/ControllerAdapter.java
> +        return new ModelAndView(view);
> 현재 구조에서 Controller 인터페이스를 사용하는 컨트롤러들이 JspView 외에 다른 View를 이용하고 싶다면 execute 메서드의 반환타입이 변경되어야 한다고 생각하는데 안나의 생각은 어떤가요?! 

저도 동의해요 ~
뷰는 자주 바뀔 수 있는 부분이기 때문에 확장성 있게 두는 것이 좋다는 생각에서 리뷰 남겼습니다.

어떻게 변경되야할 지 잘 알고 계신 것 같아 해당 리뷰는 resolve 처리하겠습니다!

2024-09-29 00:55 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
> -        }
좋습니다! 일급 컬렉션에게 검증 역할을 잘 위임하신 것 같아요. 👍

2024-09-29 00:57 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
오 코드가 너무 깔끔해졌네요! 테스트코드도 추가하신 부분 확인했습니다.
꼼꼼한 반영 너무 좋습니다 👍👍👍

2024-09-29 01:03 UTC, Mingyum-Kim commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java
> +            methods.forEach(method -> addHandlerExecution(controllers.get(controllerClass), method));
아하 인스턴스 생성의 역할을 ControllerScanner로 위임하게 되면서 생긴 변화이군요!
이해했습니다 👍

2024-09-29 01:08 UTC, Mingyum-Kim commented on app/src/main/java/com/techcourse/controller/annotation/RegisterController.java
같은 URL과 Method를 가지고 있는 컨트롤러가 두 개 이상인 게 괜찮은 설계인지 고민해봤으면 좋겠어요. 
사용자가 실수로 같은 URL을 매핑했다는 상황을 가정했을 때, 프레임워크 단에서 에러 없이 어노테이션 기반의 컨트롤러만 우선시한다면 실수를 감지하기 어렵게 한다고 생각해요.

2024-09-29 01:09 UTC, Mingyum-Kim approved these changes
안녕하세요 카고 ~ 

리뷰 반영하신 부분 확인했습니다. 
반영한 부분에 대해 테스트코드도 꼼꼼하게 잘 짜주셨네요 👍 굿입니다

더 반영할 부분은 없는 것 같아 이만 머지하겠습니다 😀 
코멘트 하나 남겨놓은 부분만 고민해봐주시면 될 것 같아요 ~

3단계 미션도 화이팅입니다!

2024-09-29 01:09 UTC, merged

2024-09-29 07:28 UTC, devhoya97 commented on app/src/main/java/com/techcourse/controller/annotation/RegisterController.java
생각해보지 못했는데, 좋은 관점이네요! 현재 Registry는request를 보고 handler를 결정하는 로직이 Registry 내에 등록된 HandlerMapping의 순서에 의존하고 있어요. 즉 첫 번째 HandlerMapping에서 Handler를 찾았다면, 두 번째 HandlerMapping은 검사하지도 않습니다.

> 사용자가 실수로 같은 URL을 매핑했다는 상황을 가정했을 때, 프레임워크 단에서 에러 없이 어노테이션 기반의 컨트롤러만 우선시한다면 실수를 감지하기 어렵게 한다고 생각해요.

말씀에 동감합니다! 다만 사용자의 실수로 같은 URL을 매핑했는지 확인하기 위해 Registry에 등록된 모든 HandlerMapping을 검사할 것인지는 고민되는 것 같아요. 서버로 들어오는 모든 Http request에 대해 적절한 Handler를 찾기 위한 Registry 순회가 필요해지기 때문이에요. 미미하다고 생각할수도 있지만 실제 운영 환경에서 무조건 거쳐야 하는 로직이 추가되기에 고민해볼 포인트 인 것 같아요. 결국 트레이드 오프라고 생각합니다!