[MVC 구현하기 - 2단계] 호티(윤주호) 미션 제출합니다.
woowacourse/java-mvc pull request #773
Opened 2024-09-28 03:16 UTC by Ho-Tea

안녕하세요 애쉬 🙇‍♂️
데모데이와 일정이 겹쳐져 미션 제출이 늦어졌습니다 🥲
요구사항 만족을 우선적으로 구현하였고, 
달라진점은 크게 `HandlerMapping`, `HandlerAdapter` 인터페이스가 추가되었다는 점 입니다!
이번에도 잘부탁드립니다 🔥

2024-09-28 10:57 UTC, ashsty requested changes
안녕하세요 호티~~ 
데모데이 준비하시느라 많이 바쁘셨죠!! ㅇ0ㅇ 
바쁜 와중에도 틈틈이 미션하시느라 고생하셨습니다!

현재 완성된 코드 기준으로 간단한 코멘트 남겨두었어요.

그런데 지금 application이 제대로 돌아가지 않고 있는 것 같아요! 👀

어떤 상황에서 돌아가지 않고 있는지 확인해보시고,
아래 세 가지를 추가로 수행하신 이후 다시 리뷰 요청 주시면 좋을 것 같아요. 

- RegisterController를 LMS에 나와있는 `@RequestMapping` 어노테이션 기반으로 수정한다
(ManualHandlerMapping 일부 메서드도 수정되어야 합니다!)
- application을 띄운 뒤 `login`, `register` 등의 페이지가 정상적으로 동작하는지 확인한다

추가로 `DispatcherServlet` 테스트도 작성되면 어떨까 하는 생각이 드네요!
테스트가 작성되었다면 application에서 발생하는 오류도 발견할 수 있었겠죠?! 

주말이지만 조금만 더 힘내봅시다! 💪
미션하느라 고생하셨어요~~

2024-09-28 10:57 UTC, ashsty commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java
> +    private final Map<Class<?>, Object> controllers = new ConcurrentHashMap<>();
`ConcurrentHashMap<>()` 👍

2024-09-28 10:57 UTC, ashsty commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +        AnnotationHandlerMapping annotationHandlerMapping = new AnnotationHandlerMapping(basePackage);
`AnnotationHandlerMapping`은 `HandlerMappingRegistry`에서 추가, 초기화되고 있고
`ManualHandlerMapping`은 `DispatcherServlet`에서 추가, 초기화되고 있는 것 같아요!

이렇게 단계가 나뉘게 된 특별한 이유가 있을까요?

2024-09-28 10:57 UTC, ashsty commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +        this.handlerMappings.add(annotationHandlerMapping);
만일 생성자 안에서 이 작업이 이루어진다고 하면 `addHandlerMapping` 메서드를 활용해봐도 좋겠네요~!

2024-09-28 10:57 UTC, ashsty commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final Object handler = handlerMappingRegistry.getHandler(request).get();
`getHandler`에서 `Optional`이 아닌 `Object`를 바로 반환할 수 있게 해주어도 좋을 것 같아요! 👀

2024-09-28 10:57 UTC, ashsty commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +    public HandlerExecution(Method method) {
해당 생성자는 사용되지 않고 있는 것 같아요!

현재 상태에서는 이 생성자 + `createInstance` 메서드가 사용될 일이 없을 것 같은데, 
남겨주신 이유가 있을까요? 👀

어떤 상황에서 쓰일 수 있을까요?

2024-09-29 04:48 UTC, Ho-Tea commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +        AnnotationHandlerMapping annotationHandlerMapping = new AnnotationHandlerMapping(basePackage);
`AnnotationHandlerMapping` 과 `HandlerMappingRegistry` 가 존재하는 곳은 `MVC 프레임워크` 이고, `ManualHandlerMapping`은 `application` 딴에 정의가 되어있었습니다. 
`DispatcherServlet`이 `handlerMappingRegistry`를 생성할 때 내부적으로 어떠한 `handlerMapping` 종류들이 구현되어있는지 최소한으로 알게하고 싶어 위와 같이 구성했습니다!
또한 `HandlerMappingRegistry` 는 프레임워크에 존재하기에 `app` 에 존재하는 `class`를 참조할 수 없어 주어진 `ManualHandlerMapping`은 `DispatcherServlet`을 통해 등록하게 되었습니다

2024-09-29 04:50 UTC, Ho-Tea commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
> +        this.handlerMappings.add(annotationHandlerMapping);
`addHandlerMapping` 을 호출하면 결국에는 다시 리스트에서 제공되는 메서드 를 활용한 `handlerMappings.add(annotationHandlerMapping);` 가 호출되기에 위와 같이 구성하였습니다!

2024-09-29 04:53 UTC, Ho-Tea commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final Object handler = handlerMappingRegistry.getHandler(request).get();
핸들러를 찾지 못한 경우 `null`을 반환할지 `Optional`을 반환할지 고민되었지만, `null`을 반환하는 것보다 `Optional`을 반환해 명시적으로 `null`일 수 있음을 표시하는 것이 적절하다고 생각되었습니다. 
또한 `404`페이지를 바로 렌더링되게 하기위해 아래와 같이 구성하였는데, 어색한 부분이 있다면 말씀 부탁드리겠습니다 🙇‍♂️
``` java
            Optional<Object> unExpectedHandler = handlerMappingRegistry.getHandler(request);
            if (unExpectedHandler.isEmpty()) {
                render(new ModelAndView(NOT_FOUND_VIEW), request, response);
                return;
            }
            Object handler = unExpectedHandler.get();
            final HandlerAdapter handlerAdapter = handlerAdapterRegistry.getHandlerAdapter(handler);
```

2024-09-29 04:59 UTC, Ho-Tea commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +    public HandlerExecution(Method method) {
`HandlerExecution`이 현재 프레임워크에 포함되기에 처음 지원되었던 형식 (`Method`를 인자로 받는 형식)이 유지되어야 한다는 생각이 들어 남겨놓았습니다! 
기존 프레임워크에서도 향후 버전에서 제거될 가능성이 있는 경우 `Deprecated` 를 명시한 후 제거되는 것과 같이, 현재 사용되어지지 않는 메서드이므로 제거하였습니다 👍

2024-09-29 06:25 UTC, ashsty commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final Object handler = handlerMappingRegistry.getHandler(request).get();
기존 코드에서는 `get()`을 통해 `Object` 핸들러를 꺼내고 있어서 해당 라인이 `Optional`을 반환한다는 사실을 한눈에 알아보기 어려웠는데, 리팩토링을 통해 아래처럼 구조가 바뀌게 된 점 확인했어요! 👍 

한 눈에 `Optional` 객체인 점을 확인할 수 있어 좋은 것 같네요.

```java
 Optional<Object> unExpectedHandler = handlerMappingRegistry.getHandler(request);
```

---

추가적으로 404 렌더링 관련해서는 저도 조금 찾아보았는데요!

[예외 핸들링 1](https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-exceptionhandlers)
[예외 핸들링 2](https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc)

이 글들에 따르면 404 에러를 보통 `DispatcherServlet`에서 바로 렌더링하지는 않는 것 같아요.
Spring MVC에서는 어떤 방식으로 404 에러를 처리하고 있는지 한 번 공부해보는 것도 도움이 되겠네요! ^_^
(알게 되면 간략하게 알려주세요~~)

호티가 이런 처리 방식을 택하신 이유가 있을까요? 🤔

2024-09-29 06:47 UTC, ashsty requested changes
안녕하세요 호티~ 간단한 피드백과 추가 코멘트 달아두었습니다.
`application`도 정상 동작하는 점 확인했어요. 🥳

혹시 코멘트 확인한 이후 코드적으로 추가하고 싶으신 부분이 있으실지 몰라 한 번 더 rc 드립니다!
다음 요청 때는 머지할 계획이니 반영을 원하시는 부분까지 반영하신 후 편하게 요청 주세요~
(요청 후 3단계 진행하고 계셔도 좋을 것 같네요!)

감사합니다~~

2024-09-29 06:47 UTC, ashsty commented on README.md
완료되었다면 체크 표시를 해줘도 좋겠네요! ✅

2024-09-29 06:47 UTC, ashsty commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        return Optional.ofNullable(handlerExecution);
저도 같은 부분에서 걸려 넘어져가지고... 시간 조금 썼습니다 호티 짱!👍

2024-09-29 06:47 UTC, ashsty commented on mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java
> +    public ModelAndView(final String viewName) {
`viewName`을 사용하는 생성자를 새로 추가하셨네요! `ManualHandlerAdapter`에서도 변경된 점 확인했는데요.

[질문] 그렇다면 호티는 `ModelAndView(View view)`와 `ModelAndView(String viewName)`이 각각 어떤 상황에서 쓰이는 게 알맞다고 생각하시나요? 

기존처럼 `View`를 생성해서 `ModelAndView`를 생성하는 방식과 `viewName`으로 생성하는 방식에 차이가 있다고 생각하셨던 걸까요? 👀

2024-09-29 06:47 UTC, ashsty commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        if (!Objects.isNull(view)) {
`nonNull`을 활용할 수도 있겠네요!

2024-09-29 16:37 UTC, Ho-Tea commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final Object handler = handlerMappingRegistry.getHandler(request).get();
이번 기회에 `Spring MVC`가 `404 상태코드`를 반환할 때 어떠한 과정을 거치는지 알아볼 수 있어 좋았습니다 👍
제가 알아본 바로는 `DispatcherServlet`이 요청을 처리할 수 있는 핸들러를 찾지 못하는 경우 크게 두가지 방식으로 `404 에러`를 처리한다고 합니다.

## 1. **NoHandlerFoundException 발생**
- 예외가 발생하려면 기본적으로 `DispatcherServlet`의 설정에서 `throwExceptionIfNoHandlerFound` 속성이 `true` 여야하며, 이 설정은 핸드러를 찾지 못햇을 때 단순히 상태코드 404 를 반환하지 않고 예외가 발생하여 처리됩니다
- `NoHandlerFoundException` 이 발생하게 되면 스프링은 일반적으로 `HandlerExceptionResolver` 를 통해 예외를 처리하게 됩니다. 
  - `HandlerExceptionResolver`는 예외가 발생했을 때 이를 가로채고, 커스텀 로직을 적용하여 응답을 제어할 수 있는 클래스라고 합니다!
- `HandlerExceptionResolver` 가 수행되는 부분은 `DispatcherServlet`의 `processHandlerException` 메서드 내에 존재했습니다.
  - `processHandlerException 메서드` : 핸들러에서 예외가 발생했을 때 예외를 처리하기 위해 호출

![image](https://github.com/user-attachments/assets/a773c1ec-e9e8-44ce-a226-6012a60ded2b)

``` java
    // 여기서 handlerExceptionResolvers를 순회하며 예외 처리기를 호출
    if (this.handlerExceptionResolvers != null) {
        Iterator var6 = this.handlerExceptionResolvers.iterator();
        
        while (var6.hasNext()) {
            HandlerExceptionResolver resolver = (HandlerExceptionResolver) var6.next();
            exMv = resolver.resolveException(request, response, handler, ex);
            if (exMv != null) {
                break; // 예외가 처리되면 더 이상 다른 처리기를 호출하지 않음
            }
        }
    }
... -> 예외가 처리된 경우 ModelAndView를 반환
```
- `resolveException` 메서드를 호출하여 해당 예외가 처리될 수 있는지 확인하는 과정을 거치면서, 만약 어떠한 `HandlerExceptionResolver`도 예외를 처리하지 못한다면 해당 예외는 500에러로 처리될 수 있습니다.
- 스프링은 기본적으로 404 에러를 처리하는 `HandlerExceptionResolver`를 제공해주지 않아서 `HandlerExceptionResolver`을 따로 정의해주어야 한다고 합니다. 
  - 1.1 `HandlerExceptionResolver`을 구현하여 `resolveException`을 오버라이딩 한 후 `WebMvcConfigurer`를 구현한 클래스에 해당 Resolver를 등록하는 방법
  - 1.2 저희가 흔히 아는 방법으로 `@ControllerAdvice`를 통해 예외를 전역적으로 처리 (더 편리함)


## 2. 404 상태코드 반환
- `throwExceptionIfNoHandlerFound` 속성이 `false`로 설정된 상태(기본값)에서는 적합한 핸들러를 찾지 못하면 SpringMVC는 예외를 발생시키지 않고 바로 404상태코드를 반환합니다.

![image](https://github.com/user-attachments/assets/a3f36f27-ff38-4d6c-8633-e18c46b1da4f)

- HttpServletResponse에 404 상태코드를 설정한 후 기본적으로 서버에 설정된 에러페이지를 보여줍니다. (Spring Boot에서는 기본적으로 제공되는 `Whitelabel Error Page`) -> `BasicErrorController`를 통해 작동
- `sendError()`가 호출되면 서블릿 컨테이너가 이를 감지하고 다시 해당 상태코드에 맞는 에러처리 페이지 혹은 컨트롤러를 찾고 실행한다고 합니다 
- `SpringBoot`에서는 `/error` 경로가 기본적으로 설정되며, 톰캣은 이 경로로 요청을 포워딩하여 최종적으로 `BasicErrorController`까지 넘어가게 된다고 합니다
- 물론 이것 또한 커스텀할 수 있다고 합니다.
  - 2.1 커스텀 에러 페이지 정의
    - Spring Boot에서는 `src/main/resources/templates/error` 경로에 상태 코드에 맞는 `HTML` 파일을 두면 해당 파일을 커스텀 에러 페이지로 사용할 수 있습니다. (ex `404.html`을 정의하면, `404` 상태 코드에 대해 해당 페이지가 렌더링)
  - 2.2 `ErrorController` 커스텀
    - 별도로 `ErrorController`를 구현하지 않거나 `ErrorMvcAutoConfiguration`을 비활성화하지 않는다면, `Spring Boot`가 기본적으로 제공하는 `Whitelabel Error Page`와 같은 기본 에러 처리 페이지가 활성화
    - `ErrorController`를 직접 구현하게 되면 `Spring Boot`는 이 빈을 자동으로 감지하고, 기본적으로 제공되는 `BasicErrorController` 대신 사용자가 정의한 `ErrorController`를 우선적으로 사용

- 이러한 방식 말고도 톰캣의 기본에러페이지를 사용하는 등의 방법이 있지만.. 그 부분까지는 현재 중요하지 않다고 생각되었습니다.(커스텀 할 수 있는 방법이 정말 많더라구요 🥲) 
- 결론적으로 스프링은 기본적으로 `404` 상태코드를 반환하고 미리 정의되어있는 `ErrorController`가 이를 잡아 기본적으로 제공되는 `Whitelabel Error Page`를 렌더링하는 형식으로 이해되었습니다.
- 현재 MVC 구조를 생각해보았을 때 서블릿 컨테이너에 에러 요청을 다시 포워딩하는 등의 작업은 이번 미션과 거리감이 있다고 생각되어(어렵기도 할 것 같습니다..ㅎ) `DispatcherServlet` 상에서 새로운 `ErrorHandler`를 반환하여 렌더링하는 것으로 리팩토링해보았습니다!

2024-09-29 17:13 UTC, Ho-Tea commented on README.md
급한 마음이 여기서 들어난 것 같네요..🥲

2024-09-29 17:25 UTC, Ho-Tea commented on mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java
> +    public ModelAndView(final String viewName) {
처음 `ModelAndView`가 `viewName`을 통해 생성하게 된 이유는 아래와 같았습니다
``` java
// 변경 전
    @Override
    public ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        String viewName = ((Controller) handler).execute(request, response);
        JspView jspView = new JspView(viewName);
        return new ModelAndView(jspView);
    }
// 변경 후
    @Override
    public ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        String viewName = ((Controller) handler).execute(request, response);
        return new ModelAndView(viewName);
    }
```
- 기존 `Legacy MVC`는 `viewName`을 반환하는데 현재 `ModelAndView`는 오로지 `View` 객체를 통해서만 생성될 수 있었습니다.
- 그렇게 할려면 `ModelAndView`를 생성하기 이전에 어떠한 뷰 객체를 쓸것인지 먼저 정의하고 `ModelAndView`를 생성해야하는데 이부분이 어색하게 다가왔습니다.
- `ModelAndView`는 컨트롤러에서 처리된 결과 데이터와 렌더링할 뷰 정보를 담고있는 객체라 판단되어 해당 뷰 정보(이름 혹은 객체)를 기준으로 뷰 객체를 찾고 해당 뷰에게 결과 데이터를 넘겨준 후 렌더링되어야 될 것 같다고 판단하여 위와 같이 구성하였습니다!

+) 실제 `ModelAndView` 도 여러 생성자를 지원하고 있더라구요!
![image](https://github.com/user-attachments/assets/74b27755-c4d3-44ea-bbcf-282c9b782a79)

2024-09-30 04:18 UTC, ashsty commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final Object handler = handlerMappingRegistry.getHandler(request).get();
우와 😳
엄청나게 꼼꼼하게 학습하셨네요! 
조금 부담이 될 수 있을 지도 모르겠다고 생각해서 걱정이 되었는데 정말 멋지게 수행해주신 것 같습니다 👍 

말씀해주신 것처럼 스프링에서는 `resolver` / `controller` 두 가지를 통해 404 에러를 핸들링하고 있는 것 같아요.

사실 호티가 처음 구현해주신 것처럼 `DispatcherServlet`에서 해당 에러를 처리해도 저희 미션에서는 큰 지장이 없다고 생각되지만,
기존의 시스템을 재구축하고 있는 만큼 원본이 어떤 지 확인해보아도 좋을 것 같다는 생각에서 드렸던 질문이었어요 ☺️

지금 변경하신 방식도 충분히 좋은 방식이라고 여겨지네요 👍👍👍
늦은 시간까지 고생하셨습니다!

2024-09-30 04:47 UTC, ashsty commented on mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java
> +    public ModelAndView(final String viewName) {
[반영하지 마세요!]

> 실제 ModelAndView 도 여러 생성자를 지원하고 있더라구요!

맞아요!

그리고 실제 MVC에서는 이 렌더링 과정이
1. `DispatcherServlet`이 `mav`가 가지고 있는 `viewName`을 적절한 `ViewResolver`에 넘겨주고, 
2. 해당 `ViewResolver`가 `View`를 반환하면 
3. 다시 `DispatcherServlet`이 그 `View`를 이용해 클라이언트에게 렌더링된 응답을 넘겨주는 식으로 동작합니다.

![image](https://github.com/user-attachments/assets/0daa018e-d5e7-45b1-a616-ffbd428c05b7)
(출처: 하단 링크 블로그)

`viewName`을 가지고 `view`를 반환하는 역할이 과연 `DispatcherServlet`의 몫일까? 하는 질문을 던져봐도 좋겠네요 🤔
(Spring은 해당 역할을 `ViewResolver`가 수행)

물론 지금 미션에서까지 반영되어야 하는 내용은 아니라고 생각하고,
지식 공유 차원에서 코멘트 남겨보아요~~ ☺️

[ViewResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/ViewResolver.html)
[Spring MVC request 흐름도 (다이어그램이 예뻐서)](https://hyos-dev-log.tistory.com/21)

2024-09-30 04:48 UTC, ashsty approved these changes
안녕하세요 호티~
엄청난 학습 과정이 담긴 코멘트 👍 주말 늦은 시간까지 미션하시느라 고생 많으셨어요.

이번 단계 요구사항은 모두 만족했다고 생각되어 이만 머지하겠습니다!
다음 단계에서 다시 만나요~~

2024-09-30 04:48 UTC, merged