[MVC 구현하기 - 3단계] 초코칩(권기호) 미션 제출합니다.
woowacourse/java-mvc pull request #775
Opened 2024-09-28 05:08 UTC by Chocochip101

안녕하세요, 산초! 일주일이 바쁘게 지나갔네요 😂

지난 리뷰에서 기본적인 커밋 단위 나누는 것을 지키지 못해 죄송한 마음이 컸습니다 🥲 
이번 리뷰에서는 변경사항이 적긴하지만, 이전 리뷰에서 놓쳤던 부분들을 보완해보려고 노력했습니다!

마지막 스탭의 리뷰 잘 부탁드립니다 🙇

## 변경 사항
- 모든 컨트롤러 어노테이션 기반 매핑으로 변경
- tobe 패키지 제거: ManualHandlerMapping이 필요없어져서 tobe와 asis의 구분이 불필요하다고 느껴져서 제거했습니다.
- JsonView 구현

2024-09-29 08:16 UTC, nayonsoso requested changes
안녕하세요 초코칩🍪
커밋도 / 패키지도 / 테스트코드도 정말 퍼팩트하게 작성해주셨네요!! 💯
그런데 컨트롤러들이 등록이 안되는지, 페이지에 들어가면 404 NotFound 가 뜹니다😅
그리고 구구가 2단계에 대한 힌트들을 LMS 에 추가해주셨는데, 
이 부분을 참고해서 리팩터링해봐도 좋을 것 같습니다.
(2단계 힌트 적용은 선택사항입니다.)

2024-09-29 08:16 UTC, nayonsoso commented on app/src/main/java/com/techcourse/controller/HomeController.java
> +import com.interface21.webmvc.servlet.mvc.view.JspView;
[반영 안해도 됨]
많은 클래스들을 servlet.mvc 패키지 아래에 옮기면서 servlet.mvc 패키지 아래에 많은 클래스들이 있게 되었네요.
하위 패키지를 만들어서 분류를 해보는건 어떨까요?

2024-09-30 03:47 UTC, Chocochip101 commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/DispatcherServlet.java
> +    private static final String BASE_PACKAGE = "com.techcourse";
오... 생각치 못했는데, 디스패처 서블릿이 구체적인 패키지명을 알면 안된다는 생각이 들었어요. 
구체적인 패키지명은 개발자에 의해 얼마든지 바뀔수가 있는 부분인데, 그때마다 서블릿의 코드가 바뀐다는 의미이니 매우 비효율적이겠네요!

디스패처 서블릿이 아닌 DispatcherServletInitializer가 디스패처 서블릿 생성자에 주입할 수 있도록 변경했습니다!

2024-09-30 03:48 UTC, Chocochip101 commented on app/src/main/java/com/techcourse/controller/HomeController.java
> +import com.interface21.webmvc.servlet.mvc.view.JspView;
webmvc.servlet.mvc 패키지에 모두 뒀었는데, 이를 webmvc의 하위 패키지로 분류했어요!

어색한 부분이 있으면 알려주세요 🙇

2024-09-30 05:01 UTC, Chocochip101 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        return model.size() == 1;
제가 생각한 장점은 간경성이에요 (사실 다른 이유가 생각나지 않네요 😅)

데이터가 하나일 경우, 굳이 Map형식이 아니라 단일 값만을 반환하는 것이 클라이언트측에서 처리하기 쉽다고 느껴져요. 반면 데이터가 두 개 이상일 경우, Key-Value쌍으로 구분이 가능해야 하니 Map으로 보내는게 합리적이여서 그런것 같아요.

산초는 어떻게 생각하시나요?

2024-09-30 14:39 UTC, Chocochip101 commented
리뷰 꼼꼼하게 봐주셔서 감사해요!

2단계 힌트 적용은 수정해야할 부분이 많아서, 개인적인 학습보다는 팀플이 더 급하다고 생각해서 적용하지 않았습니다. 
다만 언급해주신 부분들은 고민해보고 적용해봤습니다 :)

2024-10-01 22:43 UTC, nayonsoso commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        return model.size() == 1;
사실 제 질문의 의도는
이 요구사항이 스프링이 Jackson을 사용해서 JSON 을 처리하는 것을 그대로 반영한 요구사항이었으며,
스프링의 MappingJackson2JsonView 클래스의 동작을 확인해보시길 바란거였습니다.

⬇️ 스프링이 Jackson 으로 JSON 을 처리할 때도 map의 원소가 하나일 때와 여러개일때 다르게 응답합니다. 
![image](https://github.com/user-attachments/assets/fbb38947-ef8e-4eef-990c-32318cf25265)
초코칩이 테스트 코드에서도 잘 작성해주신 것처럼요👍

---

그런데 초코칩이 더 본질적인 답변을 해주신 것 같아요.
"스프링이 이렇게 동작하기 때문에" 가 아니라, "왜 이 방법이 효율적일 수 있는지" 에 대해서 답변해주셨네요😊
제 생각에도 이렇게 설계가 된 이유는 JSON 응답을 더 효율적으로 만들기 위해서였다고 생각합니다.
값이 하나라면, 감싸서 보내지 않고 하나의 값만 보내는게 더 효율적일 것 같아요.

질문에 잘 답변해주셔서 감사합니다!👏👏

2024-10-01 22:54 UTC, nayonsoso commented on app/src/main/java/com/techcourse/controller/HomeController.java
> +import com.interface21.webmvc.servlet.mvc.view.JspView;
확인했습니다! 적절한 것 같습니다🙆🏻‍♀️

2024-10-01 22:57 UTC, nayonsoso commented
안녕하세요 초코칩! 
리뷰 드렸던 부분들 반영해주신 것 확인했습니다😁
학습 테스트 통과도 확인했습니다. 스트림을 사용해서 깔끔하게 작성해주셨네요👍
이번 단계에서 학습하실 부분들은 모두 학습하신 것 같아 이만 머지합니다.
초코칩의 코드로 많이 배울 수 있었습니다 감사합니다🍪

2024-10-01 22:57 UTC, merged