[MVC 구현하기 - 3단계] 커찬(이충안) 미션 제출합니다.
woowacourse/java-mvc pull request #778
Opened 2024-09-28 10:10 UTC by leegwichan

안녕하세요 리비! 커찬입니다.
바쁘신 것 알지만 3단계 PR 날려봅니다!

혹시 이해 안되시거나 궁금한 점 있으시면 DM 또는 직접 찾아와주세요!

2024-10-01 15:49 UTC, Libienz requested changes
안녕하세요 커찬! 3단계 미션 진행 고생하셨습니다~ 

깔끔하게 구현해주셨다고 생각해요~ 다만 학습테스트를 진행한 이력이 없어서 첨부해서 신청 다시 주세요!

다음 요청 때에는 Merge할 것 같습니다! 
화이팅~

2024-10-01 15:49 UTC, Libienz commented on app/src/main/java/com/techcourse/controller/UserController.java
> +    }
어노테이션 기반의 컨트롤러 매핑이 이루어지고 있지만 뷰 이름만이 반환되고 있네요.
저는 ModelAndView를 반환하는 것이 미션의 의도로 알고 있는데 커찬의 다른 시각이 있었을까요?

2024-10-01 15:49 UTC, Libienz commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/HandlerExecution.java
> +        throw new HandlerExecutionException();
클라이언트가 자유롭게 개발하고 반환된 뷰의 형태에 따른 분기 제어권은 프레임워크가 가져갔군요!

다만 뷰를 일관적으로 처리하지 못한다는 점에서 객체지향을 깨트리는 부분 같은데 커찬이 고민하신 부분을 제게 조금 더 들려주실 수 있을까요?

2024-10-01 15:49 UTC, Libienz commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonUtils.java
> +        return OBJECT_MAPPER.writeValueAsString(model);
요구 사항 적용도 굳!

2024-10-06 06:07 UTC, leegwichan commented on app/src/main/java/com/techcourse/controller/UserController.java
> +    }
처음에는 `ModelAndView`를 만들어서 반환하도록 코드를 작성했는데, 기존 컨트롤러에서 바뀌는 모든 부분에 `new ModelAndView(new JspView("..."))` 부분이 추가되었습니다. 저는 이 부분이 중복이라고 생각되어 `HandlerExecution`에서 처리하도록 변경했습니다!

2024-10-06 06:45 UTC, leegwichan commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/HandlerExecution.java
> +        throw new HandlerExecutionException();
저는 "코드를 편하게 사용한다" >> "객체지향" 이라고 생각합니다.
객체지향을 지키는 것은 코드를 편하게 사용하고, 추후 유지 보수를 위해서라 생각합니다.

이 부분이 객체지향을 깨트린다고 보는 리비의 입장도 이해되는데요. 내가 만든 코드로 개발자가 편하게 사용할 수 있다면, 그것도 올바른 방향 아닐까요?

이 코멘트에 대한 리비의 생각도 궁금합니다! (제가 좀 두서없이 쓴 것 같아서, 추가적으로 만나서 의논해보고 싶어요!)

2024-10-06 06:47 UTC, leegwichan reviewed
안녕하세요 리비! 같은 강의장 쓰는 커찬입니다.
리비가 준 코멘트의 제 나름대로 의견을 달아보았습니다.
추가로 di 학습 테스트도 진행했습니다.
의문가는 점이나 이해 안되는 점은 코멘트 달아주세요! 추가적으로 누락된 부분이나 연락할 부분 있으면 DM이나 자리로 직접 찾아와주세요!

2024-10-06 16:45 UTC, Libienz approved these changes
고생하셨습니다 커찬 👍

커찬의 코드는 의도가 잘 보이는 코드라 특히 좋았어요~
커찬의 시각을 확인하며 리뷰하다가 저도 많이 배웠답니다!

다음 미션도 화이팅이고요! 얼마 남지 않은 우테코도 마지막까지 화이팅입니다 🔥🔥

2024-10-06 16:45 UTC, Libienz commented on app/src/main/java/com/techcourse/controller/UserController.java
> +    }
예전에 봤을 때 저는 ModelAndView의 제어권을 클라이언트로부터 뺏어가는 것은 아닌지 우려되는 부분이 있었어요~

커찬의 의견을 듣고 나서 한번 더 HandlerExecution을 보니 개발자의 자유도를 높여준 구현이라고 생각되네요!
다만 그 대가로 HandlerExecurion의 객체지향을 조금 포기한 것 같습니다.

해당 부분의 트레이드 오프에 대한 생각은 개발자마다 다를 수 있을 것 같아요~
저와는 생각이 다르긴 하지만 커찬이 저울질 하고 내린 결론을 존중할 수 있을 것 같아요.
좋은 의견 공유해주셔서 감사합니다 👍

2024-10-06 16:45 UTC, Libienz commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/HandlerExecution.java
> +        throw new HandlerExecutionException();
스프링은 지속적으로 발전하고 버전이 업데이트 되는 프레임워크입니다.
즉, 클라이언트 코드 뿐만 아니라 스프링 프레임워크 또한 유지보수되는 대상이라고 생각해요.

객체지향을 잘 지킨 코드가 유지보수가 쉬운 만큼 현재의 구현은 저는 아직 어색하게 보이기는 합니다!
> 뷰 타입이  추가되는 경우 새로운 뷰타입 작성과 함께 해당 부분 역시 수정지점으로 잡히겠네요

다만 커찬의 의견도 꽤나 합리적이라고 생각합니다.
결론적으로 위에서 드린 코멘트와 맥락이 비슷한데요~
커찬이 트레이드 오프 지점을 명확히 이해하고 한쪽을 선택한 것이라고 생각되요. 객체지향을 살며시 포기한 대신 클라이언트 개발자의 편의를 생각했다면 100점짜리 구현이라고 생각합니다 💯

2024-10-06 16:45 UTC, merged