[MVC 구현하기 - 2단계] 알파카(최휘용) 미션 제출합니다.
woowacourse/java-mvc pull request #794
Opened 2024-09-29 07:26 UTC by slimsha2dy

안녕하세요 이상!
핑계지만 예비군이랑 데모데이가 겹쳐 이전 단계 이후로 너무 늦게 리뷰 요청을 보내드리게 된 점 죄송합니다..ㅜㅜ
이번 단계도 잘 부탁드립니다!!

2024-09-29 09:29 UTC, kunsanglee requested changes
안녕하세요 알파카!
테스트도 꼼꼼히 작성해 주시고, 구현도 상당히 잘해주셨어요 읽기 편했습니다 😄
고민해 볼 만한 점 코멘트로 남겨봤는데, 같이 고민해 보면 좋을 것 같습니다.
다시 리뷰 요청 주세요!

2024-09-29 09:29 UTC, kunsanglee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        instances.forEach(this::registerController);
오 분리하셨군요! 좋네요 👍

2024-09-29 09:29 UTC, kunsanglee commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScannerTest.java
> +    }
테스트용 컨트롤러를 두고 테스트 하셨군요 💯

2024-09-29 09:29 UTC, kunsanglee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handlerAdapter/ControllerHandlerAdapter.java
> +    }
알파카가 handle 메서드 내부에서 isSupported 메서드를 수행하지 않은 이유는 무엇인가요?
아마도 HandlerMappingRegistry에서 getHandler 메서드 구현에 따라 이런 형태가 되었겠죠?
그럼 isSupported 메서드와 handle 메서드가 나뉘어서 public interface 로 존재하면 어떤 문제가 발생할 수 있을까요? 🤔 저도 구현은 이런 방식으로 해놨는데 한 번 고민해보면 좋을 것 같아서 질문 드립니다!

2024-09-29 09:29 UTC, kunsanglee commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        this.handlerAdapterRegistry = new HandlerAdapterRegistry();
외부에서 주입받는 방식 대신 생성자 내부에서 생성한 이유는 무엇인가요? 🤔

2024-09-29 09:29 UTC, kunsanglee commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerAdapterRegistry.addHandlerAdapter(executionHandlerAdapter);
init 메서드 내부에서 add 메서드를 통해서 handlerMapping, handerAdapter를 추가하는 방식으로 구현한 이유는 무엇인가요? 이 방식이 아닌 방법과의 차이도 같이 생각해보면 좋을 것 같아요! 😀

2024-09-29 09:29 UTC, kunsanglee commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.getView().render(modelAndView.getModel(), request, response);
알파카가 생각하는 DispatcherServlet이 가져야 하는 책임은 어디부터 어디까지 인가요?

2024-09-29 16:43 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.getView().render(modelAndView.getModel(), request, response);
큰 그림에서 생각해보자면 사용자의 Http 요청을 받고 그에 맞는 Http 응답을 내려주는 것이라고 생각하는데요.
이를 위해 해당 `service()` 메서드의 각 한 줄 한 줄이 이러한 책임에 필요한 각 단계와 일치할 것 같습니다.
1. 요청에 맞는 핸들러를 찾고
2. 핸들러에 맞는 핸들러 어댑터를 찾고
3. 핸들러를 실행
4. 뷰를 렌더링하여 최종 응답 생성

이렇게 될 것 같은데 혹시 제가 놓친 부분이 있을까요?

2024-09-29 17:07 UTC, slimsha2dy commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handlerAdapter/ControllerHandlerAdapter.java
> +    }
지금 당장 생각나는 문제로는 외부에서 `handle()`을 호출할 때 인자로 `Controller`가 아닌 다른 객체를 넣어줄 때 발생할 것 같네요.
현재 레지스트리에서는 `isSupported()`를 통해 지원되는 객체만 인자로 넣어주고 있지만 만약 레지스트리가 없다면 이를 장담할 순 없으므로 어떻게 보면 외부의 레지스트리에 의존하는 형태(두 public 메서드가 같이 호출돼어야만 하는 형태)라고 볼 수도 있겠네요.
물론 인터페이스를 통해 확인할 수 있기 때문에 이를 사용하는 개발자는 `isSupported`를 같이 호출해주면 되겠지만 이 또한 추가적인 인지 비용이 필요한 만큼 깔끔한 형태는 아니라고 생각합니다.
하지만 내부에서만 `isSupported`를 호출할 수 있다면 `handle`을 실행했을 때 매번 오류가 터지는지로 어떤 객체를 지원하고 있는지 확인할 수 있다는 점에서 또 반드시 더 좋다고만 할 수는 없을 것 같아요. `isSupported`만으로 확인할 수 있는 사실을 try-catch를 통해 확인해야 하니까요. 그런 점에서는 trade-off가 존재한다고 생각합니다.
어쨌든 현재 구현에서는 레지스트리에서 stream을 통해 쉽게 어댑터를 찾을 수 있다는 점과 추후에 확장되더라도 레지스트리 없이 어댑터만 사용될 일은 쉽게 생기지 않을 것이라는 점에서는 괜찮다고 생각합니다.
이상의 생각도 궁금한데 제가 놓친 점이나 알고계신 부분 남겨주시면 감사하겠습니다.

2024-09-29 17:24 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        this.handlerAdapterRegistry = new HandlerAdapterRegistry();
외부에서 주입받는 방식에 비해 생성자 내부에서 생성하는 것은 다음과 같은 장단점이 있을 것 같아요
### 장점
- 구현 및 유지보수 관점에서 편하다(관리 포인트가 비교적 적음)
- 항상 일관된 동작을 보장한다(주입을 신경쓰지 않아도 된다)

### 단점
- 유연성이 떨어진다(내부적으로 정해진 레지스트리만 사용할 수 있다)
- 위의 이유로 인해 테스트가 좀 더 까다로워진다
- 마찬가지로 위의 이유로 인해 확장에 쉽게 대처하기 힘들다

장단점만 보면 단점이 더 크다고 생각될 수 있지만, 미션 상황에서 보면 마감 기한이 있어서 빠른 구현이 요구된다는 점, 스프링 mvc의 구조를 크게 벗어날 일이 없다면 현재 레지스트리 구조가 바뀌기는 힘드므로 현실적으로 확장성에 큰 비중을 두지 않아도 된다는 점을 고려해 보면 단점이 크게 와닿지 않는다고 생각합니다. 이상의 생각은 어떠신가요?

2024-09-29 18:48 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerAdapterRegistry.addHandlerAdapter(executionHandlerAdapter);
지금 이상이 여쭤보신 건 두 가지 포인트가 있는 것 같은데요.

첫 번째, `DispatcherServlet`의 `init` 메서드 내부에서 추가한 이유는 결국 관리의 용이성이 가장 큰 것 같습니다.
현재 저희 미션에서는 레거시 코드도 같이 관리할 수 있도록 레지스트리에 관련 어댑터와 매핑 객체를 추가해주어야 하는데 현재 이를 알고 있는 건 `com.techcourse` 패키지에 존재하는 `DispatcherServlet`이라고 봐도 될 것 같아요.
현재 구조에서 어플리케이션 개발자는 저희의 mvc를 사용하기 위해 `DispatcherServlet` 코드를 수정해야 하는데, 여기서 레거시 컨트롤러를 추가해주어야 합니다. 이에 따라 기존의 `ManualHandlerMapping`은 `DispatcherServlet`에서 추가해주어야 하는데, 핸들러 매핑이나 어댑터 등의 레지스트리 내부 객체들을 추가하는 로직이 여러 군데 흩어져 있으면 관리할 때 아주 불편함이 생길 것 같아요.
이에 따라 모든 관련 로직을 사용자인 어플리케이션 개발자가 수정해야 하는 하나의 클래스로 모으기 위함이라고 말씀드릴 수 있겠네요.
물론 차후에 이 추가 로직이 방대해진다면 분리를 생각해볼 수도 있겠지만 지금 당장은 크게 필요성을 느끼지 않아서 일단 안에 두어도 될 것 같아요.

그리고 생성자가 아닌 add 메서드를 통해 추가하는 방식으로 구현한 이유는 사실은 미션 LMS에 나와있는 힌트의 인터페이스 구조를 참고한 이유가 가장 크긴 합니다..ㅎㅎ
아무튼 각 방법에 대해 생각해 보면, 생성자를 통해 생성할 경우 객체의 일관성을 보장할 수 있고(생성자만으로 온전한 객체를 보장), 추가 메서드를 통해 생성할 경우 객체의 유연성과 확장성을 챙길 수 있을 것 같아요. 물론 단점은 서로 그 반대가 될 수 있겠죠?
하지만 지금 상황에서는 레지스트리 객체들이 동적으로 어떤 다른 구조를 가질 필요는 없으므로 유연성과 확장성은 장점이 되기 힘들 것 같고, 레지스트리가 쓰이는 곳은 한정적이므로 객체의 일관성을 보장하는 것도 그닥 큰 메리트가 되지는 않을 것 같아요.
그렇다면 단점을 따져보는 것이 좋을 것 같은데, 사실 레지스트리가 일종의 컬렉션이라고 생각하면 객체의 일관성을 보장하지 않는다는 점이 저는 큰 단점이라고 생각되지는 않습니다.
아무튼 말이 길어졌는데 결론은, 트레이드오프를 고려해봤을 때 어떤 큰 차이가 느껴지지는 않는 부분이긴 하네요. 그래서 일단은 인터페이스 예시를 따라가볼 생각인데 이상의 생각도 궁금합니다. 혹시 제가 놓친 부분이나 다른 생각 갖고 계시다면 공유 부탁드릴게요!

2024-09-29 23:37 UTC, kunsanglee approved these changes
답변도 너무 잘 해주셨습니다 😀
늦은 시간까지 고생 많았어요 알파카 👍
3 단계도 화이팅입니다!

2024-09-30 01:09 UTC, kunsanglee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handlerAdapter/ControllerHandlerAdapter.java
> +    }
>하지만 내부에서만 isSupported를 호출할 수 있다면 handle을 실행했을 때 매번 오류가 터지는지로 어떤 객체를 지원하고 있는지 확인할 수 있다는 점에서 또 반드시 더 좋다고만 할 수는 없을 것 같아요. isSupported만으로 확인할 수 있는 사실을 try-catch를 통해 확인해야 하니까요. 그런 점에서는 trade-off가 존재한다고 생각합니다.
저도 비슷하게 생각해요! `handle` 메서드 내에서 `isSupported` 메서드를 사용하게 하고, 예외를 던지지는 대신`Optional`을 통해 반환하는 것도 좋은 대안이 될 수 있을 것 같아요 👍

2024-09-30 01:15 UTC, kunsanglee commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        this.handlerAdapterRegistry = new HandlerAdapterRegistry();
의존성 주입을 위한 코드가 없어서 코드가 간결해지긴 하지만, 알파카가 말씀해 주신 대로 테스트 시 Mock 객체를 주입하기 어렵겠죠?
현재 미션 상황을 고려하면 문제가 된다고 생각하지 않습니다 👍

2024-09-30 01:31 UTC, merged

2024-09-30 01:52 UTC, kunsanglee commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerAdapterRegistry.addHandlerAdapter(executionHandlerAdapter);
```java
// DispatcherServlet.class

...

private void initHandlerMappings(ApplicationContext context) {
        this.handlerMappings = null;
        if (this.detectAllHandlerMappings) {
            Map<String, HandlerMapping> matchingBeans = BeanFactoryUtils.beansOfTypeIncludingAncestors(context, HandlerMapping.class, true, false);
            if (!matchingBeans.isEmpty()) {
                this.handlerMappings = new ArrayList(matchingBeans.values());
                AnnotationAwareOrderComparator.sort(this.handlerMappings);
            }
        } else {
            try {
                HandlerMapping hm = (HandlerMapping)context.getBean("handlerMapping", HandlerMapping.class);
                this.handlerMappings = Collections.singletonList(hm);
            } catch (NoSuchBeanDefinitionException var4) {
            }
        }

        if (this.handlerMappings == null) {
            this.handlerMappings = this.getDefaultStrategies(context, HandlerMapping.class);
            if (this.logger.isTraceEnabled()) {
                this.logger.trace("No HandlerMappings declared for servlet '" + this.getServletName() + "': using default strategies from DispatcherServlet.properties");
            }
        }

        Iterator var6 = this.handlerMappings.iterator();

        while(var6.hasNext()) {
            HandlerMapping mapping = (HandlerMapping)var6.next();
            if (mapping.usesPathPatterns()) {
                this.parseRequestPath = true;
                break;
            }
        }

    }

...

```
우선 실제 Spring의 `DispatcherServlet`를 들여다보면 `initHandlerMappings`, `initHandlerAdapters` 와 같은 메서드 내부에서 조건에 따라 초기화하고 있습니다. 저희가 코드를 작성할 때 객체를 지향을 하면서 생성자 주입을 통한 객체 초기화를 고집한 이유와는 달리, 프레임워크 관점에서는 기본 설정을 제공하고 필요에 따라 커스터마이즈 할 수 있도록 설계되어 있다고 합니다. 그리고 생성자 주입을 통해 `DispatcherServlet`을 초기화한다면 엄청나게 복잡하겠죠? 😇 두 방식 모두 현재 미션에 적용하는데 문제 없다고 생각합니다!