[MVC 구현하기 - 3단계] 아톰(이하늘) 미션 제출합니다.
woowacourse/java-mvc pull request #798
Opened 2024-09-29 11:11 UTC by le2sky

2024-09-30 03:24 UTC, Minjoo522 requested changes
안녕하세요 아톰! 리브입니다.
3단계 빠르게 구현 해주셨네요. 깔끔하게 잘 구현해주시고 테스트도 동작도 이상 없어서 남길 코멘트가 많이 없지만 같이 몇 가지만 이야기 해보도록 합시다.

그리고 아래는 아톰이 PR 남겨주신 내용에 대한 답변입니다.

> 팀내에서 합의된 규칙이 있다면 따를려고 노력할 것 같아요. 개인적으로 선호하는 것은 따로 없습니다.
가독성이 나아보이는 편을 선택하거나, 방어적 복사의 경우에는 필드에서 인스턴스를 생성합니다.
리브는 어떤 방법을 선호하시나요?

저도 아톰과 동일합니다 ㅎㅎ 팀 컨벤션을 따르는 편입니다!

> 이 부분은 리브의 의견을 더욱 듣고 반영하고 싶어요. 일반 코드라면 append를 지우고 생성자를 유지하는 방식을 택했을 것 같은데요.
프레임워크의 코드이기 때문에 망설여지는 부분이 있어요. 가령 ArrayList는 add로 추가도 가능하고, 생성자에서 collection을 주입 받기도 합니다. 제가 놓치고 있는 부분이 있다면 추가 피드백 부탁 드립니다.

저도 `일반 코드라면 append를 지우고 생성자를 유지하는 방식을 택했을 것 같은데요.` 이 부분에 공감합니다. 그럼에도 불구하고 현재 시점에서 굳이 사용하지 않는 코드는 남겨두지 않으려고 하는 것 같아요. 어떤 것을 사용해야 하는지 다른 개발자로 하여금 고민하게 한다고 생각하기 때문이에요. 만약 생성자가 없고 append만 있다면 아무 고민 없이 append를 택하게 되겠죠. 😊

> 제가 역량이 부족하여 리브의 의도를 정확히 이해하지 못했어요. 주어진 핸들러의 처리를 위임할 수 있는 어댑터를 반환하는 테스트 코드는 이미 존재하는데, 이를 더욱 정확하게 작성하라는 의도일까요?

2 단계에서 `ManualHandlerAdapter`와 `AnnotationHandlerAdapter`가 공존했었는데요~ 그래서 handler가 `Controller` 인스턴스이면 `ManualHandlerAdapter`를 리턴하고, `HandlerExecution`이면 `AnnotationHandlerAdapter`를 리턴하는지 테스트하면 좋겠다고 남겼었습니다! 😊 이번 단계에서 레거시 코드를 지우면서 필요 없는 테스트가 되었네요. 😅

2024-09-30 03:24 UTC, Minjoo522 commented on mvc/src/main/java/com/interface21/webmvc/servlet/DispatcherServlet.java
> +        handlerAdapters.appendHandlerAdapter(viewNameHandlerExecutionAdapter);
지난 단계에서 미처 못 남긴 코멘트가 있어 다른 위치지만 찍고 남깁니다 😭
`DispatcherServlet` 클래스의 `service` 메서드 `try` 문 안에서 핸들러를 가져오고 핸들러 어댑터를 가져오고 modelAndView를 받아온 뒤 렌더까지 하고 있는데요~
렌더하는 부분만이라도 메서드 분리한다면 의미있는 이름을 주고 내부 로직은 신경쓰지 않아도돼서 좋을 것 같은데 아톰은 어떻게 생각하시나요?

2024-10-01 02:26 UTC, le2sky commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +    @RequestMapping(value = "/login", method = RequestMethod.POST)
좋은 것 같습니다! 현재는 LoginController를 통합하고, 일부 메서드 이름(excute 였던)을 개선했습니다.

2024-10-01 02:31 UTC, le2sky commented on mvc/src/main/java/com/interface21/webmvc/servlet/DispatcherServlet.java
> +        HandlerAdapter viewNameHandlerExecutionAdapter = new ViewNameHandlerExecutionAdapter();
HandlerExecutionAdapter는 내부에서 반환값이 ModelAndView, String, ResponseEntity 등등 다양한 리턴 타입이 등장하게 되면, HandlerExecutionAdapter에 코드가 쌓이게 되니 분리했습니다.

2024-10-01 02:51 UTC, le2sky commented on mvc/src/main/java/com/interface21/webmvc/servlet/DispatcherServlet.java
> +        handlerAdapters.appendHandlerAdapter(viewNameHandlerExecutionAdapter);
리브가 말씀하시는 것은 아래 중 어떤 느낌일까요!?

```java
Object handler = handlerMappings.getHandler(request);
HandlerAdapter handlerAdapter = handlerAdapters.getHandlerAdapter(handler);
ModelAndView mv = handlerAdapter.invoke(handler, request, response);
renderView(request, response, mv);
``` 

```java
Object handler = handlerMappings.getHandler(request);
HandlerAdapter handlerAdapter = handlerAdapters.getHandlerAdapter(handler);
ModelAndView mv = handlerAdapter.invoke(handler, request, response);
mv.render(request, response);
```

> 렌더하는 부분만이라도 메서드 분리한다면 의미있는 이름을 주고 내부 로직은 신경쓰지 않아도돼서 좋을 것 같은데 아톰은 어떻게 생각하시나요?

현재 View, Adpater, Mapping이 추상화되어 있는데요. 어떤 부분이 내부 로직인지 모르겠습니다. 그리고, 메서드로 분리하면 어떤 이점이 있는지 생각이 나지 않아요. 오히려, mvc 협력이 숨겨지는 게 아닌지 염려됩니다. 추가 피드백 주시면, 제 성장에 큰 도움이 될 것 같아요. 🙇🏻‍♂️

2024-10-02 01:18 UTC, Minjoo522 requested changes
안녕하세요 아톰!
빠르게 리뷰 반영해주셨네요.

구현, 리뷰 반영 잘 해주셨고 테스트 코드도 잘 동작합니다!
미션이 @mvc 구현이라 사소한 부분인가? 싶긴하지만 이왕이면 사소한 부분이라도 잘 작동했으면 좋겠는 마음에서 리뷰 남깁니다. ㅠㅠ

아래 회원 가입 화면에서 하단의 로그인 하러 가기 버튼을 클릭하면 500이 뜹니다.
![image](https://github.com/user-attachments/assets/a350c77e-ac4b-421f-9c21-9a2409b119b3)

이 부분만 수정 해주시고 리뷰 요청 다시 주시면 머지할 수 있을 것 같습니다! 😊

2024-10-02 01:18 UTC, Minjoo522 commented on mvc/src/main/java/com/interface21/webmvc/servlet/DispatcherServlet.java
> +        handlerAdapters.appendHandlerAdapter(viewNameHandlerExecutionAdapter);
저는 첫 번째를 생각하고 제안드렸습니다!
ModelAndView에서 View와 Model을 get 해와서 하는 과정이 따로 분리돼 있는게 더 가독성이 좋다고 생각했어요!
첫 번째 코드를 읽을 땐 핸들러를 가져오고 어댑터를 가져온 다음에 ModelAndView를 만들고 뷰를 렌더링하는 구나~라고 읽히는게 읽는 사람 입장에서 훨씬 편하다고 생각했습니다.
이 부분은 개인차가 있는 부분이라서 굳이 반영하지 않아도 괜찮습니다!

2024-10-03 05:47 UTC, Minjoo522 approved these changes
안녕하세요 아톰~
이번 미션은 여기서 마무리 하도록 하겠습니다!
다음 미션도 화이팅입니다.

2024-10-03 05:47 UTC, merged