[MVC 구현하기 - 3단계] 새양(양경호) 미션 제출합니다.
woowacourse/java-mvc pull request #819
Opened 2024-09-30 02:00 UTC by geoje

안녕하세요 미아,

드디어 마지막 미션 제출이네요~
이번 구현 사항에 대한 주요 항목들은 아래와 같습니다! 🤩

### 1. JsonView 클래스를 구현한다.
- `JsonMapper` 사용
다른 기능들을 많이 사용하지 않으니 `ObjectMapper` 를 상속하고 있는 구체화 클래스인 `JsonMapper` 를 사용하여 객체와 JSON 간의 매핑만 딱 처리할 수 있도록 하였습니다.

- 브라우저로 API 요청
`/api/user` 접속 시 아래와 같이 `JSON` 을 보여주게 됩니다.
![image](https://github.com/user-attachments/assets/159657a2-1760-4971-80b2-52386b9c65b0)

- `ArgumentHandlerExceptionResolver` 생성
`DispatcherServlet.service()` 동작 중 예외가 발생할 경우 기본적으로 예외를 해결할 수 있는 클래스를 생성하였습니다.
`UserControllerTest` 에 전부 작성해두었지만 존재하지 않는 계정 정보로 브라우저에서 요청 시 아래와 같이 보여지게 됩니다.
![image](https://github.com/user-attachments/assets/110b58fc-3bb1-432b-b514-974a499e6ff0)
~~어라? API 요청이니 응답도 JSON으로 했어야 했나...~~

### 2. Legacy MVC 제거하기

2024-10-01 03:10 UTC, jongmee requested changes
안녕하세요 새양! pr description과 코드 모두 너무 꼼꼼하네요 ☺️ 덕분에 리뷰하기 수월했어요! 이번에는 argument resolver까지 만들어주셨군요 💯

아주 작은 리뷰 하나 때문에 일단 다시 RC 드려요!! 고생하셨습니다 😊

2024-10-01 03:10 UTC, jongmee commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        response.getWriter().write(json);
> model에 데이터가 1개면 값을 그대로 반환하고 2개 이상이면 Map 형태 그대로 JSON으로 변환해서 반환한다.

이 부분만 추가되면 완벽할 것 같네요!

2024-10-02 07:17 UTC, geoje commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        response.getWriter().write(json);
https://github.com/geoje/java-mvc/commit/ac51700275b657d1ed20be82f99a1eb145e6242b

넵! `key` 를 반환하지 않는게 마음에 들지 않아 요구사항을 무시했는데 딱 걸렸군요 😅
해당 사항 반영 하였습니다!!

2024-10-02 07:31 UTC, jongmee approved these changes
고생하셨어요 새양!!! 새양의 코드를 리뷰할 수 있어서 즐거웠습니다 😊 😊

다음 미션도 화이팅👍

2024-10-02 07:31 UTC, jongmee commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        response.getWriter().write(json);
ㅋㅋㅋㅋ 그런거였군요 저도 키가 왜 없어야 하는지는.. 모르겠네요 🤔 굿 👍

2024-10-02 07:32 UTC, merged