[MVC 구현하기 - 3단계] 도도(김도선) 미션 제출합니다.
woowacourse/java-mvc pull request #847
Opened 2024-09-30 08:43 UTC by ehtjsv2

2024-10-02 00:31 UTC, skylar1220 requested changes
안녕하세요 도도~ 학습테스트까지 꼼꼼히 3단계 구현해주셨군요!
몇가지 질문 남겼는데 이와 함께 2단계 마지막 어프로브 때 남겼던 코멘트도 함께 확인 부탁해요😋
마지막까지 화이팅!!!

2024-10-02 00:31 UTC, skylar1220 commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +                .orElse(new ModelAndView(new JspView("redirect:/401.jsp")));
1. new JspView 부분이 컨트롤러 내에서 중복으로 발생하고 있어요.
2. 그렇다면 어떤 view 구현체를 선택해야하는지가 컨트롤러의 책임일까? 생각이 들어요

도도의 생각은 어떤지 궁금합니다 :)

2024-10-02 00:31 UTC, skylar1220 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        }
> model에 데이터가 1개면 값을 그대로 반환하고 2개 이상이면 Map 형태 그대로 JSON으로 변환해서 반환한다.

현재는 map 형태 그대로가 아닌 두 줄의 json 응답으로 반환되는 것 같아요!
```
{"id":1,"account":"","password":"","email":""}
{"id":1,"account":"gugu","password":"password","email":"hkkang@woowahan.com"}
```

2024-10-02 00:31 UTC, skylar1220 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
(ModelAndView 클래스에 대해 남기는 코멘트입니다! 현재 pr에는 존재하지 않네요ㅎㅎ)
1. View 클래스 뿐만아니라 ModelAndView 클래스에도 render의 책임이 있습니다. ModelAndView가 render의 책임을 갖는 것이 적절한지 고민되어요.
2. ModelAndView이 어떤 역할을 하는 객체인가 정의가 필요할 것 같습니다! 단순 데이터를 담아주는 하나의 상자 역할만 하는가, 아니면 어떤 로직을 처리하는 역할을 갖는 객체인가 말이죠 :) 

도도의 생각이 궁금합니다💭

2024-10-03 03:18 UTC, ehtjsv2 commented on mvc/src/main/java/com/interface21/webmvc/servlet/DispatcherServlet.java
시간에 쫓기다 보니 패키지 구조를 신경 못썼는데요! 저는 오히려 인터페이스와 구현체를 같은 패키지에 넣는 것을 좋아합니다!
그게 더 명확하다고 느끼기도 하고, 인터페이스를 상위패키지에 한다면, 많은 인터페이스가 한곳에 모여있을 것 같은 상상이 되네요.
현재는 아래와 같이 바꿨습니다.
```
servlet
 ㄴmvc
     ㄴ handlerMapping
         ㄴ HandlerMapping.java
         ㄴ AnnotationHandlerMapping.java
     ㄴ handlerAdapter
         ㄴ HandlerAdapter.java
         ㄴ annotationHandlerAdapter.java
 ㄴDispathcerSevlet
 ㄴ View
```

그럼에도 상위패키지에 놓는 장점도 생각해봤는데요,
만약 handlerMapping의 구현체가 2개 있고 각 구현체별로 도와주는 클래스가 2개 이상씩 있다고 생각하면 각 역할이 분명하게 인터페이스를 상위패키지에 두는 것은 좋다고 생각해요.
아래와 같은 상황에서요!
```
servlet
 ㄴmvc
     ㄴ handlerMapping
         ㄴ HandlerMapping.java
         ㄴ annotationHandlerMapping
             ㄴ AnnotationHandlerMapping.java
             ㄴ AnnotationHandlerMappingSupport1.java
             ㄴ AnnotationHandlerMappingSupport2.java
         ㄴ anotherHandlerMapping
             ㄴ AnotherHandlerMapping.java
             ㄴ AnotherHandlerMappingSupport1.java
             ㄴ AnotherHandlerMappingSupport2.java
 ㄴDispathcerSevlet
 ㄴ View
```

2024-10-03 03:21 UTC, ehtjsv2 commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +                .orElse(new ModelAndView(new JspView("redirect:/401.jsp")));
두개의 코멘트를 합쳐서 답변드리자면, 어떤 view 구현체를 선택해야하는 지는 매핑된 메서드의 책임이라고 생각합니다.
해당 메서드가 Json을 반환해야한다면, JsonView를 JspView를 반환해야한다면 JspView를 반환한다고 생각하고 있습니다.
그에따라, new JspView 부분이 중복발생하지만, 각 메서드별로 본인의 반환값에 맞게 넣어줘야하니까 중복이라고 생각하지 않습니다.

2024-10-03 03:33 UTC, ehtjsv2 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        }
엇, 이부분은 저랑 출력이 다른데, 저는 1개일 때, 2개일 때 아래와 같이 나옵니다
값이 한개일 때,
![image](https://github.com/user-attachments/assets/5e8a9858-cab5-40c6-80dc-af25197e415f)

값이 두개일 때,
![image](https://github.com/user-attachments/assets/982797a6-f4ce-4bf1-9aab-d842151499d0)

제가 Postmand으로 했었는데 postmas은 디폴트가 pretty print였네요..! raw형식도 json으로 나오게 수정했습니다!

2024-10-03 03:45 UTC, ehtjsv2 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
저는 ModelAndView를 하나의 비즈니스 로직을 수행할 수 있는 객체로 바라봤었어요. 그랬기에 해당 데이터를 가지고 있는 View와 Model 데이터를 가지고 있는 ModelAndView에서 render하는 게 자연스럽다고 느꼈습니다!

질문을 듣고 다시 코드를 보니까, app모듈의 Controller에서 ModelAndView를 반환하고, mvc모듈에서 dispatcherServlet이 해당 ModelAndView를 받아서 처리하는 모습이, 오히려 ModelAndView가 비즈니스 로직을 가지고 있으면 안된다고 생각이 드네요.

지금의 설계로는 ModelAndView는 DTO에 더 가깝고, 두 모듈을 아우르는 ModelAndView가 render()를 들고 있으면, 어느 부분에서도 render를 할 수 있다는 점에서 설계상 잘못 됐다고 생각합니다!

좋은 인사이트 감사합니다~!

2024-10-03 03:47 UTC, ehtjsv2 commented
커비 ModelAndView 질문 재밌었습니다!! 객체지향을 주제로 두고 깊이 고민하는 게 얼마 만인지,,,감사합니다~!

2024-10-03 23:25 UTC, skylar1220 requested changes
도도 답변 남겨주신 것 모두 확인했습니다~
도도의 생각을 알 수 있어서 좋았어요!
학습 테스트가 실패하는 부분이 있어서 이 부분만 수정하고 요청 주시면 어프로브 가겠습니다🚀🚀

2024-10-03 23:25 UTC, skylar1220 commented on study/src/test/java/di/stage4/annotations/DIContainer.java
stage4Test가 실패하고 있습니다~ 더불어 ClassPathScanner를 활용하면 좋겠네요!

2024-10-07 06:30 UTC, ehtjsv2 commented
stage4Test를 ClassPathScanner까지 활용해서 완료시켰습니다!

2024-10-07 23:26 UTC, skylar1220 approved these changes
도도 수고 많았습니다!! 여러 부분을 고민해서 코드를 작성하는 게 느껴져서 많이 배워갑니다ㅎㅎ
남은 미션도 화이팅입니다👏👏

2024-10-07 23:26 UTC, merged