[MVC 구현하기 - 3단계] 타칸(최원준) 미션 제출합니다.
woowacourse/java-mvc pull request #848
Opened 2024-09-30 08:43 UTC by jhon3242

안녕하세요 제제! 
빠르게 3단계 구현해보았습니다! 
잘 부탁 드립니다!!

2024-10-02 01:39 UTC, JINU-CHANG requested changes
안녕하세요 타칸 이번 단계도 잘 구현해주셨네요 👍
전반적으로 잘 구현해주신 것 같아 사소한 피드백 몇가지만 드렸습니다!
확인 부탁드려요 ~

2024-10-02 01:39 UTC, JINU-CHANG commented on app/src/main/java/com/techcourse/controller/LoginController.java
>      public String execute(final HttpServletRequest req, final HttpServletResponse res) throws Exception {
반환타입을 ModelAndViewr가 아닌 String 타입으로 유지하신 이유가 무엇인가요?

2024-10-02 01:39 UTC, JINU-CHANG commented on app/src/main/java/com/techcourse/controller/LoginViewController.java
> +    @RequestMapping(value = "/login/view", method = RequestMethod.GET)
이제 @RequestMapping을 사용하게 되었으니 LoginController쪽으로 메서드를 이동시켜보는 것은 어떤가요?
그리고 value값으로 매핑 메서드를 구분하는 것이 아닌 method를 활용해보는 건 어떤가요? (ex /login/view -> /login)

2024-10-02 01:39 UTC, JINU-CHANG commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandler.java
> +public class AnnotationHandler implements Handler{
컨트롤러 클래스가 바로 ModelAndView를 반환하게 된다면 해당 클래스는 필요하지 않겠네요 👀

2024-10-02 01:39 UTC, JINU-CHANG commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ManualHandler.java
> +public class ManualHandler implements Handler{
지금 사용되고 있는 부분이 있나요??

2024-10-02 12:29 UTC, jhon3242 reviewed
안녕하세요 제제! 커멘트 남겨주신 부분들 반영했습니다! 
리뷰 부탁드려요!

2024-10-03 06:54 UTC, JINU-CHANG commented on app/src/main/java/com/techcourse/controller/LoginViewController.java
> +    @RequestMapping(value = "/login/view", method = RequestMethod.GET)
미션 방향에 대해서 동의합니다. 더 좋은 코드에 대해 고민하면서 코멘트 남기기는 했는데 변경되면서 바뀔 부분들에 대해서는 깊게 생각해보지 못했네요. 앤드포인트가 바뀌면 프론트단의 코드도 바뀌어야 하니 필요하지 않다면 기존의 코드를 최대한 유지하는 것도 좋은 방향인 것 같습니다 ㅎㅎ

2024-10-03 06:57 UTC, JINU-CHANG approved these changes
안녕하세요 타칸! 답변주신 부분 모두 확인해보았습니다 😊
마지막 단계 미션까지 정말 수고많으셨습니다. 이만 머지하도록 할게요!! 다음 단계도 화이팅~

2024-10-03 06:57 UTC, merged