[MVC 구현하기 - 3단계] 알파카(최휘용) 미션 제출합니다.
woowacourse/java-mvc pull request #851
Opened 2024-09-30 08:45 UTC by slimsha2dy

안녕하세요 이상.
드디어 마지막 단계가 되었네요..
제가 리뷰 요청이 좀 느렸음에도 이상께서 빠르게 좋은 리뷰들을 남겨주셔서 금방 진행할 수 잇었던 것 같아 정말 감사드립니다 ㅎㅎ
이번 단계도 잘 부탁드릴게요!

2024-09-30 12:24 UTC, kunsanglee requested changes
안녕하세요 알파카! 🦙😇
엄청 빨리 깔끔하게 구현해주셨네요!
3단계는 학습 차원에서 짚어볼 만 한 코멘트만 남겨봤습니다.
미션 구현 사항 테스트와 학습 테스트는 이후 다시 리뷰 요청 주실 때 함께 포함 해주세요!
고생 하셨습니다! 💯

2024-09-30 12:24 UTC, kunsanglee commented on app/src/main/java/com/techcourse/DispatcherServletInitializer.java
> +        final var dispatcherServlet = new DispatcherServlet(servletContext);
오 이렇게 설정하신 이유를 설명해주실 수 있을까요? 😮

2024-09-30 12:24 UTC, kunsanglee commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        writer.close();
명시적으로 close 해주셨군요! 
try-with-resources 문으로 묶으면 더 깔끔하겠네요! 반영은 안하셔도 됩니다! 😄

2024-09-30 12:24 UTC, kunsanglee commented on mvc/src/test/java/com/interface21/webmvc/servlet/view/JsonViewTest.java
> +        model.put("user2", new TestUser("HaeSsee", 7));
이상해씨를 넣어주셨네요 감사합니다 알파카~ 🤣😇

2024-09-30 12:24 UTC, kunsanglee commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/DispatcherServlet.java
> +        this.basePackage = (String) servletContext.getAttribute("basePackage");
`DispatcherServletInitializer`에서 넣은 `basePackage`를 바탕으로 꺼내서 `HandlerMapping`을 생성하는군요! 이와는 별개로 학습 차원에서 `DispatcherServlet`과 `DispatcherServletInitializer` 클래스의 패키지 위치가 다른 이유와, `DispatcherServletInitializer`가 `DispatcherServlet`을 초기화하고 실행하는 과정에 대해서 알아볼까요? 😇

2024-10-03 05:21 UTC, kunsanglee approved these changes
안녕하세요 알파카 😇
구현 깔끔하게 잘 해주셨어요!
MVC 미션 정말 고생 많으셨어요 이만 머지하겠습니다.
마지막 JDBC 미션과 프로젝트 모두 화이팅입니다~~ 👍

2024-10-03 05:21 UTC, kunsanglee commented on study/src/test/java/di/stage4/annotations/DIContainer.java
> +        }
stage3와 4의 코드에서 이 부분이 달라졌는데, 어떤 이유 때문에 메서드 구현이 달라졌나요?
그리고 어느 상황에도 동작하게 만드려면 어떻게 하면 될까요? 😇

2024-10-03 05:21 UTC, merged

2024-10-03 07:22 UTC, slimsha2dy commented on app/src/main/java/com/techcourse/DispatcherServletInitializer.java
> +        final var dispatcherServlet = new DispatcherServlet(servletContext);
결국에는 base package 정보를 `DispatcherServlet`이 알아야 하는데 이를 직접 인자로 받게 된다면 변경과 확장에 유연하지 않은 구조가 될 것 같아서 이렇게 구현했습니다!
어플리케이션 단의 정보가 추가적으로 필요하게 되더라도 `servletContext`에 정보를 추가해주는 것만으로 쉽게 이 정보를 받아서 사용할 수 있고 basePackage의 정보를 `servletContext`에서 알고 있는 것도 어색하지 않다고 생각했습니다!

2024-10-03 08:04 UTC, slimsha2dy commented on study/src/test/java/di/stage4/annotations/DIContainer.java
> +        }
stage3와 stage4의 가장 큰 차이점은 **어떤 필드를 초기화해야 하는지**를 알고 있는가라고 생각했습니다.
stage4에서는 어노테이션을 통해 `DIContainer`가 어떤 필드를 초기화해야 하는지 알고 있는 반면 stage3에서는 이를 알 수가 없습니다. 그 일례로 stage3에서 `InMemoryUserDao`의 `dataSource`는 필드이지만 di 컨테이너에서 초기화해주면 안됩니다. 물론 final이 붙어 있기 때문에 컨테이너가 초기화하면 안된다고 생각할 수 있지만 그렇다고 final이 없는 필드를 전부 초기화해야 한다고 장담할 수는 없고, 실제로 저희가 스프링 프레임워크를 사용할 때는 final 필드를 생성자를 통해 컨테이너로부터 주입받고 있습니다.
그렇기 때문에 stage3에서는 한 개의 public 생성자 정보를 통해 주입받을 필드 정보를 알아내는 방식으로 `DIContainer`가 동작하도록 구현했습니다! 하지만 stage4에서는 초기화할 필드를 알고 있기 때문에 해당 필드만 초기화하는 방식으로 구현하게 되면서 저렇게 차이가 생기게 되었습니다.

2024-10-03 08:18 UTC, slimsha2dy commented on study/src/test/java/di/stage4/annotations/DIContainer.java
> +        }
제 생각에 현재 코드에서 오류가 발생하는 경우는 주입받아야 할 빈을 등록하지 않거나 순환참조가 발생하는 경우에 재귀로 인해 스택 오버플로우가 발생하는 경우인 것 같은데요. 실제 스프링에서도 이런 경우에는 제대로 된 동작이 되지 않는 것으로 알고 있습니다.
혹시 현재 코드에서 추가적으로 동작하지 않는 경우가 어떤 것인지 좀만 더 힌트를 부탁드려도 괜찮을까요?

2024-10-04 05:03 UTC, kunsanglee commented on study/src/test/java/di/stage4/annotations/DIContainer.java
> +        }
아 저는 알파카가 작성한 코드에 문제가 있다는 의미는 아니었습니다 😅
다만 생성자의 유무, 생성자가 기본 생성자인 경우, 기본 생성자가 없는 경우 고려해야할 부분이 좀 있을 것 같아서 질문 드렸어요!
한 번 생각해보고 넘어가면 좋을 것 같아서요~