[MVC 구현하기 - 3단계] 리비(이근희) 미션 제출합니다.
woowacourse/java-mvc pull request #853
Opened 2024-09-30 08:45 UTC by Libienz

안녕하세요 아루 🔥
시간에 맞추다 보니 조금 급한 구현이 되었을지도 모르겠네요.

이번 단계도 잘 부탁드립니다~

2024-09-30 10:10 UTC, donghoony requested changes
안녕하세요 리비~! 3단계 빠르게 잘 적용해주셨습니다 👏🏻 
학습 테스트에서 할 이야기가 많은데, 하나씩 적용해가며 이야기해보아요 🥹

`DispatcherServlet`을 이제 `mvc` 패키지로 옮겨 주세요! 그때부터 몇 가지를 제안드려보겠습니다 😈

2024-09-30 10:10 UTC, donghoony commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        String body = objectMapper.writeValueAsString(model);
개수에 따른 분기를 한 이유가 있을까요?
```suggestion
        objectMapper.writeValue(response.getWriter(), model);
```

2024-09-30 10:10 UTC, donghoony commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +            throws Exception {
인터페이스에서는 `Exception`을 던진다고 했으나, 구현체에서는 실제 던질 것만 명시하면 좋겠네요!

2024-09-30 10:10 UTC, donghoony commented on app/src/main/webapp/index.jsp
파일에 변화가 있었을까요? 아니면 단순하게 스타일이 적용된 것인가요?

2024-09-30 10:10 UTC, donghoony commented on app/src/main/java/com/techcourse/controller/HomeController.java
> +    }
👍🏻 레거시 코드를 완벽하게 제거했네요!

2024-09-30 10:10 UTC, donghoony commented on study/src/test/java/di/stage3/context/DIContainer.java
> +            }
이번 학습에서는 각각의 `constructor`가 예외를 어떻게 던질 지에 대해서보다는 DI Container 그 자체를 학습하는 성격이 강해요. 그래서 실제 코드에서도 `FunctionWrapper`, `ConsumerWrapper`를 제공하고 있습니다. 이를 활용해서 인덴트를 줄여 볼까요?

2024-09-30 10:10 UTC, donghoony commented on study/src/test/java/di/stage3/context/DIContainer.java
> +                .orElseThrow();
정확한 예외를 던져 봅시다!

2024-09-30 10:10 UTC, donghoony commented on study/src/test/java/di/stage4/annotations/ClassPathScanner.java
> +        result.addAll(serviceAnnotated);
메서드 이름은 `AllClasses`인데, 내부에서 어노테이션을 기준으로 나누고 있네요. 이 부분을 해당 객체가 행하는 게 맞을 지 생각해봅시다!

2024-09-30 17:50 UTC, donghoony commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        String body = objectMapper.writeValueAsString(model);
오 이 부분은 제가 힌트 아래를 안 봐서 몰랐네요. 반영하지 않아도 됩니다 ✅

2024-09-30 18:23 UTC, donghoony commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        String body = objectMapper.writeValueAsString(model);
> model에 데이터가 1개면 값을 그대로 반환하고 2개 이상이면 Map 형태 그대로 JSON으로 변환해서 반환한다.

다시 보니 살짝 애매하긴 하네요. 일반적인 `Json`을 생각한다면 value만 뽑아내는 것이 어색하기도 하고요. **값을 그대로 반환**한다는 건 Model의 Key-Value를 하나의 값으로 보았을까요? 🤔 저는 그렇게 생각해서 전부 담긴 했습니다. Jackson이 알아서 해 주니깐요..

2024-10-02 08:06 UTC, Libienz commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        String body = objectMapper.writeValueAsString(model);
Model의 key-value를 모두 담기 시작하는 순간 아루가 제안주신 것처럼 모델 사이즈에 따른 분기가 필요없겠네요.

저도 해당 요구사항의 의도를 파악하진 못했는데요.. 우선은 값을 Model map의 키값이 없는 값만으로 해석하기는 했습니다~
나중에 구구에게 의도를 물어봐야겠군요 🤔

2024-10-02 08:06 UTC, Libienz commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +            throws Exception {
합리적이네요! 던질 수 있는 예외를 세부적으로 명시하고 메서드에서 고려되어야 할 점들을 명세로서 명확히 드러내겠습니다 👍

2024-10-02 08:06 UTC, Libienz commented on app/src/main/webapp/index.jsp
앗 파일에 변화가 있었는데요..! 스타일이 적용된 것 같습니다.

GET `login/view` 요청에서 로그인 페이지를 반환하다가 GET `login`으로 명세를 수정했거든요..!
그러다가 스타일이 적용되어 수정되지 않았나 싶네요.

살펴보시기 쉽게 다시 원복해놓겠습니다..!

2024-10-02 08:55 UTC, Libienz commented on study/src/test/java/di/stage3/context/DIContainer.java
> +            }
코드가 좀 심했죠..? 인덴트 개선하려고 생각은 하고 있었습니다! 다만 기한까지 완성된 만큼 제출하다 보니 인덴트가 매우 깊어졌네요.

개선해야지라고 생각은 하고 있었지만 FunctionWrapper, ConsummerWrapper는 처음 만나는 개념이네요~ 
Wrapper가 람다식을 다음의 목적으로 감싸는 개념으로 학습했습니다.

- 예외 처리: 함수 실행 중 발생하는 예외를 한 곳에서 처리하여 코드의 중복을 줄입니다.
- 로깅(logging): 함수 호출 전후로 로그를 남겨 디버깅이나 모니터링에 활용합니다.
- 입출력 검증: 입력 값의 유효성을 검사하거나 결과 값을 검증합니다.

적용해서 개선하겠습니다~

2024-10-02 08:57 UTC, Libienz commented on study/src/test/java/di/stage3/context/DIContainer.java
> +                .orElseThrow();
반영했습니다! 
그런데 아루에게 궁금한 점이 있어요.

저는 매번 헷갈리는 부분인데요 자바가 제공하는 예외를 사용해야 할 지 커스텀 예외를 사용할지 여부입니다.
이번에는 IllegalArgument를 적용하도록 했는데요~ 아루만의 기준이 있으면 설명해주실 수 있을까요?

2024-10-02 14:47 UTC, Libienz commented on study/src/test/java/di/stage4/annotations/ClassPathScanner.java
> +        result.addAll(serviceAnnotated);
classPathScanner의 역할을 축소하고 (모든 클래스 반환) 애너테이션이 붙은 클래스를 파싱하는 역할을 DIContainer로 위임하였습니다!

2024-10-02 15:03 UTC, donghoony commented on study/src/test/java/di/stage3/context/DIContainer.java
> +            }
ㅎㅎㅎ `FunctionWrapper`와 `ConsumerWrapper`는 `Stream` 내에서의 예외 처리를 보다 간단하게 하기 위해서 등장한 도우미(?)라고 생각해요. 이 함수들의 도움이 없었다면 내부에서 Checked Exception을 처리해야 했겠죠 🤔

2024-10-02 15:06 UTC, donghoony commented on study/src/test/java/di/stage3/context/DIContainer.java
> +                .orElseThrow();
저번에 리비와 추상화 수준에 대해서 이야기한 적 있는데요, 그 맥락과 아주 비슷해요.
저희는 프레임워크 (JDBC에서는 라이브러리겠죠?)를 만들고 있고, 사용자는 저희 프레임워크를 사용하게 될 거예요. 내부 구조가 어떻게 돌아가는지는 사용자(웹 개발자) 입장에서는 알 필요가 없죠.

나는 빈을 찾고 싶을 뿐인데, `NoSuchElement`라는 예외가 나온다면 너무 구체적인 예외가 아닐까요? 어떻게 보면 컬렉션의 예외 같기도 하네요. **빈 컨테이너**라는 개념이 새롭게 등장한 이상, 그에 맞는 예외를 만들면 사용자가 해결하기 더 수월하겠다고 생각했어요. `NoSuchBeanFoundException`이나 `BeanNotFound`나 ... 에러 메시지에서 처음 보는 예외 클래스의 이름으로 어떤 상황인지를 유추할 수 있어야 하니까요. 유추하는 과정에서 추상화 수준의 차이가 너무 많이 나게 되면, 프레임워크를 사용하는 사람은 디버깅에 꽤나 애를 먹겠습니다.

그런 이유로 저는 대부분의 경우에서 높은 추상화 수준을 가지는 예외를 선언해 변환해서 던져주고 있어요!

2024-10-03 07:51 UTC, donghoony requested changes
안녕하세요 리비~ mvc 마지막을 달려가고 있네요 👍🏻 이번 RC는 마지막이 되겠습니다! 몇 가지 생각해볼 점을 남겨 두니 확인해주세요!

2024-10-03 07:51 UTC, donghoony commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DispatcherServlet.java
> +package com.interface21.webmvc.servlet.mvc.tobe;
사용하지 않는 `Controller`도 삭제하고, `tobe` 패키지도 바깥으로 옮겨 보죠!

2024-10-03 07:51 UTC, donghoony commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DispatcherServlet.java
> +package com.interface21.webmvc.servlet.mvc.tobe;
나아가 인터페이스와 그 구현체가 각각 어떤 패키지에 있으면 좋을지 생각해 봐도 좋겠습니다. `HandlerAdapter`와 `HandlerMapping`은 어떤 클래스가 사용하나요?

2024-10-03 10:39 UTC, Libienz commented on study/src/test/java/di/stage3/context/DIContainer.java
> +                .orElseThrow();
예외 선정에서 추상화 수준을 고려하시는 군요. 

해당 예외가 어떤 깊이로 이해되어야 하는지 공감하는 입장에서 아루의 기준이 저도 마음에 드네요~
앞으로의 예외 작업에서 저도 소신을 가지고 작업할 수 있을 것 같습니다!

2024-10-03 10:55 UTC, Libienz commented on study/src/test/java/di/stage3/context/DIContainer.java
> +                .orElseThrow(() -> new NoSuchElementException("bean을 찾을 수 없습니다"));
상세한 예외 중요하다고 생각합니다 👍

예외의 추상화 수준을 맞추고 자세한 예외 전달할 수 있도록 수정했는데요~ 잘 개선되었는지 다음 리뷰요청에 확인해주시면 감사하겠습니다 🙇🏻‍♂️

2024-10-03 11:23 UTC, Libienz commented
안녕하세요 아루 🔥
마지막 리뷰요청이라니 슬프네요 🥲

아루는 기술의 상세를 이해하려고 노력하는 참된 개발자라고 생각해요~
그러한 개발자가 되고 싶은 1인으로써 지난 2주동안 동기부여도 많이 받고, 기술적으로도 많이 배울 수 있었습니다.
이 기회가 참 소중했던 것 같아요.

even하게 익은 아루의 코멘트로부터 지난 아루에게 정말 많이 배웠습니다.
앞으로의 미션과 프로젝트 모두 건승하시길 바래요~

감사합니다 🙇🏻‍♂️

2024-10-03 12:27 UTC, Libienz commented
안녕하세요 아루 🔥
마지막 리뷰요청이라니 슬프네요 🥲

아루는 기술의 상세를 이해하려고 노력하는 참된 개발자라고 생각해요~
그러한 개발자가 되고 싶은 1인으로써 지난 2주동안 동기부여도 많이 받고, 기술적으로도 많이 배울 수 있었습니다.
이 기회가 참 소중했던 것 같아요.

even하게 익은 아루의 코멘트로부터 지난 아루에게 정말 많이 배웠습니다.
앞으로의 미션과 프로젝트 모두 건승하시길 바래요~

감사합니다 🙇🏻‍♂️

2024-10-03 12:41 UTC, donghoony approved these changes
안녕하세요 리비! 두 번째 미션이 막을 내리겠네요 🙇🏻 어떠셨나요? 프레임워크를 만들어나가는 과정이 생각보다 정말 어렵고, 그 중에서도 추상화라는 게 참 아름답다고 느꼈습니다. 리비는 어떤 것을 얻어가면서 미션을 진행했는지 궁금하네요 😁 

> 아루가 생각하는 인터페이스와 그 구현체의 패키지는 무엇인가요!? 간단하게 힌트만 주셔도 도움이 많이될 것 같습니다.

`import`문 하나만으로도 객체가 얼마나 얽혀 있는가? 를 확인할 수 있습니다. 같은 패키지에 존재하지 않으면 import해야 하는 자바의 특성 상 그러한데요.

`DispatcherServlet`은 핸들러와 어댑터를 알지, 그 구체 클래스를 몰라도 됩니다. 제 의견을 조금 더 보태자면, **몰라야 합니다**. 자세한 구현체의 모습을 아는 순간 구현체의 전파가 사용하는 곳으로 고스란히 전해집니다. 유지보수하기 어려운 코드가 되겠네요.

그럼 그 안다/모른다 를 어떻게 판단할까요? 코드가 직접 판단하지는 않을 테니, 정확한 판단 기준이 어딘가에 존재합니다. 그게 `import`라고 생각해요. 그리고 이는 곧 의존성과도 직결합니다. `import`하는 순간, 해당 클래스의 변경이 내 클래스에도 전파된다는 의미입니다.

만약 `HandlerAdapter` 인터페이스가 `adapter` 패키지에 존재한다면 어떻게 될까요? `DispatcherServlet`은 `mvc.adapter` 패키지를 알게 됩니다. 직접적이지는 않겠지만, 간접적으로라도 패키지의 변화가 나에게 전파될 것임을 암시하는 `import`문이 추가되겠네요. 하지만 사용하는 쪽과 같은 클래스에 두고, 구체 클래스를 다른 곳에 두면 어떤가요? `import`문은 생기지 않고, `DispatcherServlet`은 구체 클래스를 아예 모른 채 잘 굴러갑니다. 의존성을 어디선가 넣어줄 테니, 자신의 관심사에 알맞은 행동을 계속 해나갈 수 있습니다.

이는 확장성과도 연관이 있다고 생각해요. 추가로 다른 사람이 프레임워크에서 제공하는 `HandlerAdapter`를 직접 implement한다고 합시다. 그렇다면 `import com.interface21.webmvc.servlet.mvc`를 가져오겠죠? 어떤 식으로 `HandlerAdapter`가 굴러가는 지 궁금하다면, 그 패키지에서 다른 패키지로 오가지 않고도 흐름을 파악할 수 있습니다. `DispatcherServlet`이 `HandlerAdapter`를 이렇게 사용하는구나~ 라고 알 수 있어요. 만약 adapter 패키지에 인터페이스가 들어 있다면 사용자는 해당 패키지 내부에서 구현체를 둘러보면서 인지 부하를 겪을 수도 있습니다. 흐름을 알고싶지만 이를 어디에서 활용하는 지 알기 위해 추가적인 탐색이 필요하겠네요.

[토스ㅣSLASH 22 - 지속 성장 가능한 코드를 만들어가는 방법](https://www.youtube.com/watch?v=RVO02Z1dLF8)이라는 영상이 있어요. 한 번 가볍게 시청하시는 것도 추천합니다! 🚀

조금 길게 고봉밥이 되었는데,, 납득이 될 지 모르겠네요 ㅎㅎ 댓글 알림은 켜져 있으니 더 이야기해보고 싶다면 댓글로 말씀해주시거나 DM으로 주세요!

이번 미션 수고 많았습니다! 머지할게요 🚀

2024-10-03 12:42 UTC, merged

2024-10-03 12:48 UTC, donghoony commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DispatcherServlet.java
> +package com.interface21.webmvc.servlet.mvc.tobe;
어프룹 메시지에 담아두었습니다 🚀