[MVC 구현하기 - 3단계] 잉크(이예찬) 미션 제출합니다.
woowacourse/java-mvc pull request #858
Opened 2024-09-30 08:51 UTC by yechop

안녕하세요 프린
마감시간까지 최대한 해보았는데 많이 부족하네요 ㅠㅠ
POST /login 요청에 대한 핸들러를 찾지 못하는 문제가 있는데 아직 해결하지 못한 상태입니다.
마지막 3단계도 잘 부탁드립니다~!

2024-10-02 05:01 UTC, GIVEN53 requested changes
안녕하세요 잉크! 마지막 단계까지 고생 많으셨습니다
학습 테스트도 👍🏻
요구사항 및 테스트 모두 만족해주셨지만 몇 가지 코멘트가 있어서 먼저 RC 드립니다 편하게 답변해주세요
그리고 컨트롤러 엔드포인트가 수정되었지만 jsp 파일에는 반영되지 않아 애플리케이션에서 연결된 페이지로 이동할 때 에러가 발생합니다 확인 한 번 부탁드려요!

2024-10-02 07:32 UTC, yechop commented on app/build.gradle
> +    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.17.2'
패키지를 잘못보고 추가했네요. 제거했습니다!

2024-10-02 07:36 UTC, yechop commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
> JsonView 인스턴스마다 개별적인 ObjectMapper가 필요할까요?

static으로 변경했습니다

> ObjectMapper는 어떤 방식으로 직렬화를 수행할까요? `http://localhost:8080/api/user?account=gugu`로 요청을 보냈을 때 `UserController`는 User 객체를 ModelAndView에 담아서 보냈지만 response body에 account만 있는 이유와 함께 고민해보면 좋을 것 같아요

3단계 힌트 마지막에 `model에 데이터가 1개면 값을 그대로 반환하고 2개 이상이면 Map 형태 그대로 JSON으로 변환해서 반환한다.` 라는 문구를 보고 넣어준 값을 그대로 반환해주도록 했습니다. 
조금 애매하게 느껴지는데 id account password email 전부 반환해주어야 한다고 생각하시나요?

2024-10-02 07:53 UTC, yechop commented on study/src/test/java/di/stage3/context/DIContainer.java
> +                .filter(aClass::isInstance)
isAssignableFrom()은 두 상속 관계를 비교하고 isInstance()는 특정 클래스의 인스턴스인지 확인합니다.
isInstance()가 적절하다고 생각해 사용했습니다

2024-10-02 08:42 UTC, yechop commented on study/src/test/java/di/stage3/context/DIContainer.java
> +                for (Object o : beans) {
InMemoryUserDao의 필드(Logger, Map, JdbcDataSource)는 beans에 등록되지 않았습니다. 
아래처럼 getBean()을 활용해 리팩토링 하면 이 필드들을 getBean() 할때 발생하는 예외를 처리하는게 애매해지는데 처리할 수 있는 좋은 방법이 있을까요?

```
for (Object bean : beans) {
            Field[] declaredFields = bean.getClass().getDeclaredFields();
            for (Field declaredField : declaredFields) {
                declaredField.setAccessible(true);
                try {
                    final Object fieldBean = getBean(declaredField.getType());
                    declaredField.set(bean, fieldBean);
                } catch (NoSuchElementException e) {
//여기를 어떻게 처리할까요
                }
            }
        }
```

2024-10-03 15:56 UTC, GIVEN53 approved these changes
잉크 마지막 단계까지 끝났네요
2주동안 재밌었고 많이 배웠습니다 :)
다음 미션, 프로젝트 모두 화이팅입니다!

2024-10-03 15:56 UTC, GIVEN53 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
ObjectMapper가 어떻게 동작하는지 알아보면 어떨지하는 차원에서 남긴 코멘트였어요 정책에 따라 다르겠지만 패스워드만큼은 리턴하지 않는게 맞는 것 같습니다
왜 getter만 있는 필드는 response body에 반환되고 나머지는 그러지 않을까? 이 것 때문에 getter 쓰기 싫은데, getter없이는 반환할 수 없을까? 의 고민과 함께 ObjectMapper의 직렬화 방식을 찾아보면 좋을 것 같아요!

2024-10-03 15:56 UTC, GIVEN53 commented on study/src/test/java/di/stage3/context/DIContainer.java
> +                for (Object o : beans) {
bean이 아닌 필드는 따로 예외 처리할 필요없이 무시해도 되지 않을까요?
try-catch를 가져간다면
```java
try {
    // ...
} catch (NoSuchElementException ignored) {
}
```
예외 변수로 표현할 수 있지 않을까 생각해요

2024-10-03 15:56 UTC, merged