[MVC 구현] 프람(김민종) 3단계 미션 제출합니다.
woowacourse/java-mvc pull request #859
Opened 2024-09-30 08:51 UTC by koust6u

안녕하세요. 조이썬 !! 
이번 미션을 시간을 정말 빠뜻하게 구현했네요.
원하는 퀄리티 100% 코드는 아니지만.. 어찌저찌 요구사항은 맞게 구현했습니다.

또 이번 테스트에서 MockHttpServletRequest, reponse를 사용하지 않고 mock() 처리한 부분이 있는데요.

MockHttpsServletResponse에서 getContentType을 호출하면 이상하게 ClassNotFound  예외가 발생했어요.
시간이 빠듯하여 알아보지 못하고 mock()을 사용했어요. 이 문제를  알아낸다면 추후에 조이썬에게 알려드릴게요 🥲

또 오늘 수업에서 설명받은 학습 테스트도 모두 진행하고 제출합니다. 학습 테스트도 같이 봐주시면 감사하겠습니다 👍

2024-10-01 09:23 UTC, youngsu5582 requested changes
쁘람. 프로젝트 한다고 좀 늦었네용 🥲🥲
코드적 으로는 솔직히 매우 잘 짜여서
가볍게 의견을 나누고 넘어가봅시다 🫡🫡

2024-10-01 09:23 UTC, youngsu5582 commented on mvc/src/test/java/com/interface21/webmvc/servlet/view/JsonViewTest.java
> +        view.render(new HashMap<>(Map.of("fram", "handsome")), request, response);
의도적으로 `HashMap`을 감싼 걸까요?
( Map 을 직접적으로 건든걸 못본거 같아서용 )

2024-10-01 09:23 UTC, youngsu5582 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/ViewResolver.java
> +        if (Objects.nonNull(response.getContentType()) && response.getContentType()
추가로, 가볍게 얘기만 해보자면
Header 중에 `Consumes` 과 `Produces` 라는게 있는데
<img width="582" alt="image" src="https://github.com/user-attachments/assets/bbd6c099-a189-487a-afb7-9355381ecfd6">

해당 헤더들도 처리해야 한다면 어떻게 해나가야 할까요?
( `ViewResolver` 가 담당하는게 아니라고 생각한다던지 )
( `resolve` 에 request 를 추가해야 한다던지 )

다양한 의견을 듣고 싶습니당 🙂

2024-10-01 09:23 UTC, youngsu5582 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/ViewResolver.java
> +public class ViewResolver {
ViewResolver 가 탄생하게 된 계기가 있나요?

2024-10-03 08:42 UTC, koust6u commented on mvc/src/test/java/com/interface21/webmvc/servlet/view/JsonViewTest.java
> +        view.render(new HashMap<>(Map.of("fram", "handsome", "hello", "world")), request, response);
[애교]
애교로 봐주세요. 🥲

2024-10-03 08:44 UTC, koust6u commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/ViewResolver.java
> +public class ViewResolver {
[의도]
이건 json view 요구 사항이 생기면서 Mime타입에 따라 view를 찾아주는 객체가 있으면 좋을거 같아 만들게 되었지만, 사실 상 현재는 의미 없는 객체입니다.

2024-10-03 08:47 UTC, koust6u commented on mvc/src/test/java/com/interface21/webmvc/servlet/view/JsonViewTest.java
> +        view.render(new HashMap<>(Map.of("fram", "handsome")), request, response);
[의도]
아 요친구는 위에 설명했듯이 MockHttpServletResponse .setContentType을 했을 때 이유 모를 예외가 발생해서, 불변 Map이 문제가 되었나? 싶어서 넣어봤어요. 지워도 될 코드입니다. !!

2024-10-03 08:55 UTC, koust6u commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +    private void renderPlaintext(final Map<String, ?> model, final HttpServletResponse response) throws IOException {
조이썬 알려주세셔서 한번 해보았습니다. 
값을을 문자열로 감싸서 반환해주는군요. 
좋은 정보 감사합니다 👍 

renderPlaintext에도 String::cast 가 아닌 writeValueAsString이 가능하겠어요.

2024-10-03 09:01 UTC, koust6u commented on study/src/test/java/di/stage4/annotations/ClassPathScanner.java
>  public class ClassPathScanner {
오우아 정말 좋은 지적이십니다. classPathScanner가 몰라도될 불필요한 객체 의존관계가 있었네요. 즉각 수정하겠습니다. !! 짱

2024-10-03 09:02 UTC, koust6u commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        final String json = mapper.writeValueAsString(model);
동의합니다. 불필요하게 생성을 미리 시킬 필요없을거 같아요

2024-10-03 09:14 UTC, koust6u commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/ViewResolver.java
> +        if (Objects.nonNull(response.getContentType()) && response.getContentType()
> Header 중에 Consumes 과 Produces 라는게 있는데

이 것은 SpringMVC RequestMapping의 애노테이션에서 요청 때 필요한 Content-type과 응답 때의 Content-tpye을 지정하는 메서드를 말씀하시는게 맞을까요?  [RequestMapping docs](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestMapping.html)

만약 해당 RequestMapping의 기능을 말씀하신거라면 말 그대로 잘못 설계된것은 맞아요. 
또 응답되는 요청을 ViewResolver에서 처리하는 것은 설계상  올바르지 않다는 것도 인정합니다. 😂
수정 제출하겠습니다. 

조이썬이 말씀한대로 해당 VIewResolover는 올바른 역핳을 하고 있진 않고 있군요. 전반적으로 수정해볼게요 😁

2024-10-03 09:16 UTC, koust6u commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/ViewResolver.java
> +        if (Objects.nonNull(response.getContentType()) && response.getContentType()
또 ViewResolver는 과도한 추상화를 하려다 발생한 실패작인거 같네요 .😭

2024-10-03 09:19 UTC, koust6u commented
안녕하세요. 조이썬 남겨주신 코멘트가 전부 쏙쏙 알맹이만 잘 말씀해주셧네요. 😁  전반적으로 부족한 부분이 있다면 언제든지 추가 코멘트 남겨주세요. 감사합니다. 즐거운 휴일 보내세요

2024-10-03 13:45 UTC, youngsu5582 requested changes
프람~
저번 리뷰 에서 제가 놓친게 하나 있어서 RC 남깁니다. ( 이거만 해결하면 바로 Approve 하겠습니당 )
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/726b259c-9ef8-499a-b40e-710faf33106a">
( UserController 가 없는거 같습니다. )

그리고, `DispatcherServletInitializer` 는 같이 옮기지 않은 것으로 보이는데
이 `ServletInitializer` 의 역할이 뭔지 가볍게 알려주세요~ 
( 옮기면 안된다는건 확인했습니당☺️☺️ )

2024-10-03 13:45 UTC, youngsu5582 commented on mvc/src/main/java/com/interface21/handler/DispatcherServlet.java
>              view.render(Map.of(), request, response);
해당 부분에서 빈 Map 이 들어가서 렌더링이 제대로 안될 거 같습니다~~

2024-10-03 13:45 UTC, youngsu5582 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        final ObjectMapper mapper = new ObjectMapper();
ObjectMapper 는 계속 만들 필요가 있나용?

2024-10-03 13:45 UTC, youngsu5582 commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        final ObjectMapper mapper = new ObjectMapper();
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/e493025d-ee51-4435-b4dc-a8199e67a4b5">
꽤나 많이 나가는듯용~ ( 이건 내가 궁금해서 삽질해본거 )

2024-10-05 13:19 UTC, koust6u commented on mvc/src/main/java/com/interface21/handler/DispatcherServlet.java
>              view.render(Map.of(), request, response);
그렇군습니다. 해당 부분은 모델로 채웠습니다. 👍

2024-10-05 13:20 UTC, koust6u commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        final ObjectMapper mapper = new ObjectMapper();
와우 Object Mapper 생각보다 무겁네요. 필드로 빼줄 필요가 있겠어요.

고급 정보 고마워요 조이썬 😁

2024-10-05 13:41 UTC, koust6u commented
안녕하세요 조이썬!! 
프로젝트나, 글쓰기 등등 여러가지 상황이 겹쳐 조금 늦어졌네요.
죄송합니다.🥲

그리고 좋은 질문을 남겨주셨네요!!! 
제공 코드를 보면 DispatcherServletInitializer는 WebApplicationInitializer을 확장하고 있는데요.
WebApplicationInitializer는 was(톰캣)에서 쓰일 설정들을 자바 코드로 진행할 수 있도록 해주는 역할을 가지고 있어요.
즉, 기존 Spring의 경우에는 Web.xml을 통해 servlet들의 정보들을 작성해야하 했지만, 이런 것들을 코드로 할 수 있게 해주는 역할인듯 합니다.

또 DispatcherServletInitializer는 그중 DispatcherServlet의 정보를 코드로 자동 설정해주는 코드로 보입니다.

혹시 틀린 정보나 추가 정보가 있다면, 언제든 피드백 주세요. 

이번 리뷰도 감사합니다 
😁

2024-10-06 05:17 UTC, youngsu5582 approved these changes
프람 이제는 아쉽지만 보내줄때군요 😢😢

질문의 의도대로 잘 답변해주셨습니다!
![image](https://github.com/user-attachments/assets/6fdd09fe-4a55-4435-802b-36b4729f53e6)
이와 같이, Java 코드 단위로 설정을 가능하게 해주는거 같더라구요.

저도, 프람한테 억까 질문을 하기 위해 & 궁금함을 물으면서 더 성장을 많이 한 거 같네요! 이상입니다.
( 힘내야해🥲🥲 )

2024-10-06 05:17 UTC, merged