[MVC 구현하기 - 3단계] 레모네(이지현) 미션 제출합니다.
woowacourse/java-mvc pull request #860
Opened 2024-09-30 08:54 UTC by JiHyeonL

안녕하세요 시소~~~!!
드디어 마지막 단계네요 😄 

추후 학습테스트와 테스트를 추가할 예정입니다!

2024-10-02 08:25 UTC, shin-jisong requested changes
안녕하세요 레모네!
아직 저도 DI 테스트의 숙지가 덜 되어서 코드 관련 간단한 리뷰 남기고
다음 턴에 테스트 해 주신 것에 관련해서 더 꼼꼼하게 보도록 하겠습니다
(사실 이변이 없으면 다음 요청 시에는 머지될 것 같네요)

2024-10-02 08:25 UTC, shin-jisong commented on mvc/src/test/java/com/interface21/webmvc/servlet/view/JsonViewTest.java
> +class JsonViewTest {
테스트를 꼼꼼하게 진행해 주셨네요!

2024-10-02 08:25 UTC, shin-jisong commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
DispatcherServlet의 패키지를 변경해 보라는 요구사항이 있었던 것 같아요 👀

2024-10-03 09:09 UTC, JiHyeonL commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
반영하였습니다!
`DispatcherServlet` 위치가 `mvc`로 바뀌면서 `app`패키지를 찾지 못하는 문제가 있었습니다.
그래서 `DispatcherServlet` 안에서 `basePackage` 경로를 찾지 않고,
생성자 인자로 `basePackage`를 받아 사용하였습니다.

`DispatcherServletInitializer`도 `mvc` 패키지 안으로 이동시키고 싶었는데,
`AppWebApplication Initializer`가 시작되지 않는 문제가 있어 `DispatcherServletInitializer`는 `app`에 그대로 두었습니다!

2024-10-04 00:30 UTC, shin-jisong approved these changes
수고하셨습니다 레모네!
다음 미션도 파이팅입니다 👍

2024-10-04 00:31 UTC, merged