[MVC 구현하기 - 3단계] 메이슨(김경원) 미션 제출합니다.
woowacourse/java-mvc pull request #867
Opened 2024-09-30 09:16 UTC by masonkimseoul

안녕하세요 조조!
3단계 요구사항을 우선적으로 적용했습니다.
추후 학습 테스트와 테스트 코드도 더 추가하겠습니다!
감사합니다.

2024-09-30 16:11 UTC, eun-byeol requested changes
메이슨! 3단계 빠르게 구현해주셨네요! 고생하셨습니다~
몇가지 리뷰와 질문 남겼어요. 요구사항 거의 다 만족해주셨는데, 한 가지 놓친 부분 있어서 리뷰 남겼으니 확인해주세요!
테스트코드와 학습테스트도 추가 후 리뷰요청해주세요~
마지막까지 화이팅합시다🙌

2024-09-30 16:11 UTC, eun-byeol commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DispatcherServlet.java
❓render()에서 View에 대한 처리를 하고 있는데요, 스프링에서 View를 처리하는 방식과 어떤 차이점이 있을까요?
힌트 : ViewResolver
저도 받았던 질문이었는데, 학습에 도움이 되어 메이슨께도 질문드립니다~

2024-10-05 08:09 UTC, masonkimseoul commented on app/src/main/java/com/techcourse/controller/LogoutController.java
> +        return redirect("redirect:/");
이걸 놓쳤네요... ㅎㅎ 감사합니다

2024-10-05 10:22 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        String jsonResult = objectMapper.writeValueAsString(model);
반영했습니다. 감사합니다!

2024-10-05 10:31 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        response.getWriter().write(jsonResult);
`getWriter()`는 문자 데이터를 처리할 때 사용하고, `getOutputStream()`은 바이트 스트림을 처리할 때 사용합니다. 현재는 String으로 `jsonResult`를 가져오고 있어서 `getWriter()`을 사용했습니다.

2024-10-05 10:39 UTC, masonkimseoul commented on mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistryTest.java
> -    @DisplayName("지원하는 타입의 HandlerAdapter가 존재하지 않으면 예외가 발생한다.")
Controller를 사용해야 한다고만 생각했었던 것 같아요 🥲 감사합니다.

2024-10-05 10:49 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java
> +        String jsonResult = objectMapper.writeValueAsString(model);
ObjectMapper에서 직렬화를 할 때, public 필드나 public으로 설정된 getter메서드를 사용해 직렬화를 진행합니다. private 필드만 있거나 getter 메서드만 존재한다면, 그 필드는 JSON으로 직렬화되지 않고 누락됩니다.
이를 해결하기 위해 @JsonProperty 어노테이션을 사용하거나, 필드에 접근할 수 있도록 public으로 바꿔주거나 public getter을 만들어주는 방법이 있습니다.

2024-10-05 11:09 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DispatcherServlet.java
>          setHandlerMappingRegistry(new AnnotationHandlerMapping(BASE_PACKAGE));
문자열로만 관리하는게 불편하긴 했는데, 좋은 방법인 것 같네요~ 반영 완료했습니다.

2024-10-05 11:37 UTC, masonkimseoul commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DispatcherServlet.java
스프링은 다음 순서로 View를 처리합니다.
1. Controller가 ModelAndView를 통해 View의 이름을 반환합니다.
2. DispatcherServlet이 ViewResolver에게 반환 받은 View 이름을 처리하도록 요청합니다. 이 과정에서 적합한 ViewResolver를 순차적으로 조회하여 찾습니다.
3. 찾은 ViewResolver는 resolveViewName을 호출합니다.

반면 현재는 받아온 ModelAndView에서 View를 꺼내고, 바로 render 메서드를 호출해 View를 처리합니다!

2024-10-05 11:55 UTC, masonkimseoul commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +        return new ModelAndView(new JspView(path));
Controller 자체를 상속 구조로 가져가는 것을 생각해보았는데요, 간단한 메서드 하나만 분리하기 위함이라면 좋은 구현은 아니라 생각합니다. 이 정도 중복은 가져가는 것도 나쁘지 않다고 생각하는데요, 어떻게 생각하시나요?

2024-10-06 04:46 UTC, eun-byeol commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +        return new ModelAndView(new JspView(path));
메이슨 의견에 동의해요. 저도 상속으로 빼진 않았을 것 같네요ㅎㅎ 중복 코드에 대한 고민 해보시면 좋을 것 같아 리뷰 남겼습니다~🙂

2024-10-06 05:12 UTC, eun-byeol approved these changes
메이슨 안녕하세요~
꼼꼼하게 리뷰 반영해주셨네요. 추가 커밋한 내용도 확인했고 간단한 리뷰 하나 남겼으니 확인해주세요
요구사항은 다 만족해서 이만 머지하겠습니다!
고생하셨고, 코드 보면서 저도 많이 배울 수 있었어요👍
새로운 미션도 화이팅합시다💪

+) 리뷰어 피드백 하는거 잊지 않으셨죠?^0^

2024-10-06 05:12 UTC, merged